import type {Build,Product} from './types.ts';
import {bestOffer,costForQuantity} from './domain.ts';
export interface ExampleBuild {id:string;name:string;useCase:string;description:string;highlights:string[];included:string;remaining:string;build:Build;sources:{label:string;url:string}[];}
const panel='shopsolar-46271524241548';
export const exampleBuilds:ExampleBuild[]=[
 {id:'portable-solar',name:'Portable solar & weekend backup',useCase:'Portable',description:'A DELTA 2 Max and folding solar panel for portable loads, camping and backup at the station’s outlets.',highlights:['400 W solar','2.048 kWh nominal storage'],included:'One DELTA 2 Max + one 400 W portable panel, sold as one retailer bundle.',remaining:'Confirm included solar cable and plug compatibility with the retailer. This example does not include a home transfer connection.',build:{name:'Portable solar & weekend backup',settings:{purpose:'offgrid',mount:'ground'},lines:[{productId:'santan-solar-delta2max-400w1',quantity:1}]},sources:[{label:'EcoFlow system details',url:'https://us.ecoflow.com/collections/solar-generators-nav/products/delta-2-max-400w-portable-solar-panel'}]},
 {id:'cabin-solar',name:'Cabin solar with rack storage',useCase:'Off-grid',description:'A modular equipment selection built around the EG4 6000XP, eight rigid panels and two rack batteries.',highlights:['3.28 kW solar','10.24 kWh nominal storage','6 kW inverter'],included:'8 × RICH SOLAR MEGA 410 panels, 1 × EG4 6000XP, 2 × EG4 LifePower4 V2 batteries.',remaining:'Add site-specific mounting, battery rack, cables, protection and grounding. Set string layout and temperature limits in the builder; battery communication and load requirements need review.',build:{name:'Cabin solar with rack storage',settings:{purpose:'offgrid',mount:'ground'},lines:[{productId:panel,quantity:8},{productId:'eg4-6000xp',quantity:1},{productId:'santan-solar-eg4-lifepower4v2-48v-100ah',quantity:2}]},sources:[{label:'EG4 battery specifications',url:'https://eg4electronics.com/categories/batteries/lifepower4-48v-v2/'},{label:'6000XP battery compatibility',url:'https://eg4electronics.com/wp-content/uploads/2024/04/EG4-6000XP-Battery-Compatibility-List.pdf'},{label:'MEGA 410 specifications',url:'https://richsolar.com/collections/solar-panels/products/mega-410-410-watt-24-volt-solar-panel'}]},
 {id:'home-backup',name:'Home solar with expanded storage',useCase:'Hybrid / backup',description:'A larger core equipment list pairing the EG4 18kPV with sixteen panels and two indoor wall batteries.',highlights:['6.56 kW solar','32 kWh nominal storage'],included:'16 × RICH SOLAR MEGA 410 panels, 1 × EG4 18kPV, 2 × EG4 16 kWh Indoor WallMount batteries.',remaining:'Add roof mounting, wiring, disconnects, rapid shutdown where required and service/transfer equipment. Confirm string sizing, inverter firmware, battery settings and utility approval for the exact installation.',build:{name:'Home solar with expanded storage',settings:{purpose:'hybrid',mount:'roof'},lines:[{productId:panel,quantity:16},{productId:'eg4-18kpv',quantity:1},{productId:'santan-solar-eg4-16kw-indoor',quantity:2}]},sources:[{label:'EG4 battery manual',url:'https://eg4electronics.com/wp-content/uploads/2025/04/EG4-WallMount-Indoor-314Ah-Battery-User-Manual.pdf'},{label:'18kPV system diagrams',url:'https://eg4electronics.com/wp-content/uploads/2024/09/EG4-18kPV-System-Wiring-Diagrams.pdf'}]},
];
const wall='santan-solar-eg4-16kw-indoor';
const moduleSource={label:'MEGA 410 specifications',url:'https://richsolar.com/products/mega-410-410-watt-24-volt-solar-panel'};
function hybrid(id:string,name:string,inverter:string,panels:number,batteries:number):ExampleBuild{return {id,name,useCase:'Hybrid / backup',description:'Grid-connected solar with indoor battery storage; configure backup circuits for your loads.',highlights:[`${(panels*410/1000).toFixed(2)} kW solar`,`${batteries*16} kWh nominal storage`],included:`${panels} × MEGA 410 panels, 1 × ${name.split(' · ')[0]} inverter, ${batteries} × EG4 16 kWh Indoor WallMount batteries.`,remaining:'Core equipment only. Add mounting, cables, disconnects, rapid shutdown, battery interconnects and service/transfer equipment. Confirm string layout, cold Voc, current limits, firmware, exact ESS certification and utility approval. Backup power depends on the battery discharge limit and selected loads.',build:{name,settings:{purpose:'hybrid',mount:'roof'},lines:[{productId:panel,quantity:panels},{productId:inverter,quantity:1},{productId:wall,quantity:batteries}]},sources:[moduleSource,{label:'EG4 indoor battery manual',url:'https://eg4electronics.com/wp-content/uploads/2025/04/EG4-WallMount-Indoor-314Ah-Battery-User-Manual.pdf'},{label:'EG4 system documentation',url:inverter==='eg4-12kpv'?'https://eg4electronics.com/wp-content/uploads/2024/09/EG4-12kPV-Wiring-Diagrams.pdf':'https://eg4electronics.com/categories/batteries/eg4-wallmount-314ah-indoor-battery/'}]};}
function enphase(panels:number):ExampleBuild{const name=`Enphase IQ8MC · ${panels}-panel grid-tied`;return {id:`enphase-${panels}`,name,useCase:'On-grid',description:'Solar-only Enphase system for a 240 V grid connection. No battery or outage backup.',highlights:[`${(panels*410/1000).toFixed(2)} kW solar`,`${(panels*.32).toFixed(2)} kW AC continuous`],included:`${panels} × MEGA 410 panels, ${panels} × IQ8MC microinverters (one per panel), 1 × IQ Combiner 6C with gateway.`,remaining:'No outage backup. Add compatible IQ trunk cable, connectors/terminators, branch breakers, roof mounting, junction boxes, grounding and site wiring. Confirm the exact module with the Enphase compatibility calculator, temperature limits and local interconnection approval. Design multiple AC branches where required; do not place all 16 microinverters on one 20 A branch. Commissioning and utility permission are required.',build:{name,settings:{purpose:'gridtie',mount:'roof'},lines:[{productId:panel,quantity:panels},{productId:'santan-solar-iq8mc',quantity:panels},{productId:'santan-solar-enphase-x-iq-am1-240-6c',quantity:1}]},sources:[moduleSource,{label:'IQ8MC ratings (US)',url:'https://enphase.com/download/iq8mc-microinverter-data-sheet-0'},{label:'IQ Combiner 6C specifications',url:'https://enphase.com/download/iq-combiner-6c-data-sheet'},{label:'Solar-only system: no backup',url:'https://enphase.com/en-gb/node/867'}]};}
exampleBuilds.push(
 hybrid('hybrid-12kpv','EG4 12kPV · starter hybrid','eg4-12kpv',8,1),
 hybrid('hybrid-flex18','EG4 FlexBOSS18 · balanced hybrid','eg4-flexboss18',16,1),
 hybrid('hybrid-flex21','EG4 FlexBOSS21 · extended backup','eg4-flexboss21',24,3),
 enphase(8),enphase(16),
);
export function exampleBudget(total:number,unpriced:number):'Low'|'Mid'|'High'|'Unpriced'{return unpriced?'Unpriced':total<5000?'Low':total<10000?'Mid':'High';}
export function exampleProducts(products:Product[]){const ids=new Set(exampleBuilds.flatMap(e=>e.build.lines.map(l=>l.productId)));return products.filter(p=>ids.has(p.id)).map(p=>({...p,specification:undefined,description:'',images:[]}));}
export function resolveExample(example:ExampleBuild,products:Product[],now=Date.now()){
 const selections=example.build.lines.map(line=>{const product=products.find(p=>p.id===line.productId);const offer=product?bestOffer(product,line.quantity,now):undefined;return {line,product,offer,cost:offer?costForQuantity(offer,line.quantity):undefined};});
 return {selections,total:Math.round(selections.reduce((sum,s)=>sum+(s.cost?.subtotal??0),0)*100)/100,unpriced:selections.filter(s=>!s.offer).length,missing:selections.filter(s=>!s.product).length,build:{...example.build,settings:{...example.build.settings},lines:selections.map(s=>({...s.line,...(s.offer?{offerId:s.offer.id}:{})}))}};
}
