import foundations from '../data/guide-foundations.json';
import {extendedLessons} from './guide-lessons';
export type Source={label:string,url:string};
export type GuideSection={title:string,paragraphs?:string[],bullets?:string[],formula?:string,columns?:string[],rows?:string[][],sources?:Source[]};
export type GuideArticle={slug:string,title:string,topic:string,level:'Beginner'|'Experienced'|'All levels',kind:'Guide'|'News & analysis',summary:string,outcome?:string,reviewed:string,eventDate?:string,origin?:string,image?:string,sections:GuideSection[],sources:Source[],tool?:{label:string,href:string},quiz?:{question:string,options:string[],answer:number,explanation:string}};
const source=(label:string,url:string):Source=>({label,url});
const wiring=source('Victron · DC wiring and protection','https://www.victronenergy.com/media/pg/The_Wiring_Unlimited_book/en/dc-wiring.html');
const theory=source('Victron · Electrical theory','https://www.victronenergy.com/media/pg/The_Wiring_Unlimited_book/en/theory.html');
const controller=source('Victron · SmartSolar MPPT 150/60–250/70 specifications','https://www.victronenergy.com/media/pg/Manual_SmartSolar_MPPT_150-60_up_to_250-70/en/technical-specifications.html');
const ground=source('Victron · Grounding and electrical safety','https://www.victronenergy.com/media/pg/The_Wiring_Unlimited_book/en/ground,-earth-and-electrical-safety.html');
const doe=source('DOE · Inverters and grid services','https://www.energy.gov/cmei/systems/solar-integration-inverters-and-grid-services-basics');
const staubli=source('Stäubli · Cross-mating of PV connectors','https://www.staubli.com/content/dam/ecs/pictures/solar-photovoltaics/RE-Statement-PV-CrossConnection-ProductLiability-EN.pdf');
const irs=source('IRS · 2025 Form 5695 instructions and credit cutoff','https://www.irs.gov/instructions/i5695');
const iea=source('IEA · Energy Technology Perspectives 2026','https://www.iea.org/reports/energy-technology-perspectives-2026/executive-summary');
const longi=source('LONGi · June 15, 2026 back-contact announcement','https://www.longi.com/en/news/60gw-bc-commercial-milestone/');
const catl=source('CATL · June 22, 2026 TENER Sodium announcement','https://www.catl.com/en/news/6861.html');
const anker=source('Anker SOLIX · E10 system specifications','https://www.ankersolix.com/e10-whole-home-backup-solution');
const china=source('China Ministry of Finance / State Taxation Administration · Announcement 2026 No. 2 (Chinese)','https://szs.mof.gov.cn/zhengcefabu/202601/t20260109_3981637.htm');
const advanced:GuideArticle[]=[
 {slug:'panel-technology',title:'Mono, bifacial, TOPCon and back contact: choose the panel, not the acronym',topic:'Panels & technology',level:'All levels',kind:'Guide',reviewed:'2026-10-04',summary:'Separate cell material, cell architecture, panel face and physical format. Build a shortlist using roof area, electrical limits and delivered cost.',image:'/guide/learn-module-anatomy.webp',tool:{label:'Compare solar panels',href:'/?category=panels'},sources:[source('DOE · Solar photovoltaic cell basics','https://www.energy.gov/cmei/systems/solar-photovoltaic-cell-basics'),source('DOE · Perovskite research directions','https://www.energy.gov/cmei/systems/perovskite-research-directions'),longi],sections:[
 {title:'Four labels that answer different questions',paragraphs:['A product can be an n-type, back-contact, bifacial module at the same time. These are different attributes. Monocrystalline describes the silicon crystal structure; monofacial describes which faces collect useful light. Confusing the two hides real options in a comparison. Treat technology labels as ways to organize candidates, then verify the actual model datasheet.'],columns:['Attribute','What it describes','Examples'],rows:[['Cell type','Semiconductor doping / material','p-type silicon, n-type silicon; perovskite is a different material family'],['Cell architecture','How the cell is constructed','PERC, TOPCon, HJT, back contact / IBC / HPBC'],['Panel face','Front-only or front-and-rear collection','Monofacial, bifacial'],['Physical format','Size and installation context','Compact portable, residential-size, large commercial-size']]},
 {title:'Start with the usable surface',paragraphs:['A larger watt number may simply mean a larger panel. Compare watts per usable square metre when roof space is scarce, and check the rectangle you can actually fit between setbacks and obstructions. An efficient panel that leaves unusable gaps can lose to a slightly lower-efficiency format that fits the roof better. Module efficiency is not the same as inverter efficiency or a promise of annual energy.','Consider a hypothetical 440 W module occupying 2.0 m² and a 550 W module occupying 2.6 m². Their densities are 220 W/m² and about 212 W/m². The larger module produces more nameplate watts per piece, but the smaller one has higher density in this example. Handleability, mounting support zones and wind-load documentation still matter.'],formula:'Power density = rated front-side W ÷ module area in m²'},
 {title:'Decide whether rear-side production has a useful opportunity',paragraphs:['Bifacial modules can collect rear-side irradiance. The opportunity depends on reflected light, height, rear shading, tilt and the surrounding surfaces. A closely mounted module above a dark opaque roof presents a different rear environment from a raised ground array. Do not add an advertised bifacial percentage to every installation. Model the site and use the current assumptions required for equipment sizing.','Separate the front-side STC rating from a rear-gain illustration on a brochure. Additional available current can matter to an input limit even when a shopping table uses only front-side watts. A glass-glass construction or attractive black appearance does not by itself establish the rear-side gain.']},
 {title:'Use new cell technology as a shortlist signal',paragraphs:['Back-contact designs move contacts to the rear of the cell; TOPCon and HJT describe different cell structures. Product labels alone cannot settle module temperature behavior, degradation, warranty exclusions or mismatch losses. Record those fields rather than assuming a universal ranking. LONGi’s 2026 announcement is evidence of its reported commercial expansion, not independent proof that every back-contact module beats every alternative.','Perovskite and tandem research is promising, but a laboratory cell record differs from a certified outdoor module available in your market. Check independently documented reliability, local supply, warranty responsibility and compatible mounting before treating an emerging design as a drop-in purchase.']},
 {title:'The practical comparison record',bullets:['Exact model, wattage bin, dimensions, mass, frame depth and approved clamp zones.','Voc, Vmp, Isc, Imp, temperature coefficients and connector family.','Front-side rating, rear-gain assumptions and the source of each claim.','Product warranty versus performance warranty; exclusions and responsible local seller.','Delivered cost for the actual quantity, not just the pallet-normalized price.']}]},
 {slug:'mppt-envelope',title:'String sizing: cold Voc, hot Vmp and the complete MPPT envelope',topic:'Electrical design',level:'Experienced',kind:'Guide',reviewed:'2026-10-04',summary:'A wattage match is only one check. Work through voltage, current, temperature, tracker allocation and battery acceptance.',tool:{label:'Run the array and controller tools',href:'/guide/calculators?tool=controller'},sources:[controller,source('Sandia PVPMC · Performance modeling','https://pvpmc.sandia.gov/modeling-guide/')],sections:[
 {title:'Build a limits sheet before changing the string count',paragraphs:['Record the exact module revision and the receiving inverter or controller. Separate absolute maximum input voltage, startup voltage, MPPT operating range, maximum operating current and maximum PV short-circuit current. If the device has multiple connector pairs, determine whether they feed independent trackers or parallel into one tracker. The number of sockets is not a tracker count.','For every proposed tracker, list modules per series string, parallel strings, orientation and shade pattern. Keep unmatched modules or different roof faces separate during the review. A product’s advertised total PV input allowance may not tell you the allowance per tracker.']},
 {title:'A worked cold-voltage example',paragraphs:['Use fictional modules rated Voc 49.5 V at 25°C, with a −0.28%/°C Voc coefficient. At −15°C, the linear multiplier is 1 + 0.0028 × 40 = 1.112. Two modules in series give 110.088 V; three give 165.132 V. A 150 V absolute input limit rejects the three-module string before watts are considered. Equality to an absolute maximum is not design headroom.','Use the selected manufacturer’s method, tolerances and locally required design temperature. The calculation is only as defensible as those inputs. A general outdoor air temperature does not describe every cell operating condition.'],formula:'Cold Voc ≈ module Voc × series count × [1 + |coefficient| / 100 × (25 − minimum cell temperature)]'},
 {title:'Hot operating voltage is a separate boundary',paragraphs:['Suppose fictional module Vmp is 41.7 V and its Vmp coefficient is −0.35%/°C. At a 70°C cell-temperature assumption, two in series provide approximately 70.26 V. Compare that with the equipment’s startup and operating requirements at the actual battery charging voltage. A 48 V-class battery may charge above 48 V, so nominal voltage is not the required PV voltage.','The workshop’s Victron comparison checks a documented startup margin for its small catalog. That margin is model-specific. Use your inverter’s own input range instead of applying it to every hybrid, microinverter or power station.'],formula:'Hot Vmp ≈ module Vmp × series count × [1 + signed Vmp coefficient / 100 × (maximum cell temperature − 25)]'},
 {title:'Current, clipping and output acceptance',paragraphs:['Series voltage scales with module count; parallel strings add current. With fictional Imp 9.6 A and Isc 10.4 A, two matched parallel strings give 19.2 A operating and 20.8 A short-circuit values at the stated conditions. Review required corrections and bifacial-current assumptions separately.','Then review battery charge acceptance and thermal derating. PV oversizing can lead to power clipping, but clipping permission does not waive an absolute voltage or current limit. The controller workshop checks one complete array at a time and reports power above catalog nominal separately; it does not divide a string among imaginary fractional controllers.']},
 {title:'Keep the review reproducible',bullets:['Save model numbers, manual revisions and the limits used.','Record minimum / maximum cell-temperature assumptions and coefficient units.','Check each tracker, connector and string protective arrangement.','Retest the envelope after any module, quantity, orientation or battery change.']}]},
 {slug:'inverter-architectures',title:'Choose an inverter architecture that does the job you actually need',topic:'Inverters & backup',level:'Experienced',kind:'Guide',reviewed:'2026-10-04',summary:'Compare string, microinverter, hybrid and standalone systems through backup behavior, battery interfaces and the AC service.',image:'/guide/learn-equipment-wall.webp',tool:{label:'Browse inverters',href:'/?category=inverters'},sources:[doe,source('DOE · Distributed resources and microgrids','https://www.energy.gov/cmei/systems/solar-integration-distributed-energy-resources-and-microgrids-basics')],sections:[
 {title:'Topology changes the questions',columns:['Architecture','What to investigate'],rows:[['String inverter','PV tracker envelopes, string allocation and grid-interconnection approval'],['Microinverter','Exact module voltage/current match, branch limits and supported backup ecosystem'],['Optimizer system','Approved optimizer/inverter pairing and system-specific string rules'],['Hybrid inverter','Battery interface, transfer controls, backup output and permitted export'],['Standalone inverter/charger','AC charging / generator support plus separate solar charging if required']],paragraphs:['The term hybrid is not a complete wiring diagram. Write down what happens in normal operation, grid failure, battery depletion and recovery. A unit that imports grid power does not necessarily have approval to export. A microinverter installation does not automatically remain energized during an outage.']},
 {title:'Power at the right voltage and duration',paragraphs:['Match the AC system: 120 V, 120/240 V split phase and 230 V single phase are different arrangements. Battery voltage, PV input voltage and AC output voltage are also separate specifications. A 51.2 V nominal LFP pack belongs to a common 48 V-class battery system; it does not mean the AC service is 48 V.','List simultaneous running demand and motor starting requirements. A 6 kW continuous rating does not establish how long a higher surge can last, whether one split-phase leg is limiting or whether the battery can deliver the required DC current. As a planning example, 6 kW AC at 90% efficiency from 48 V needs about 139 A before voltage sag. This is arithmetic, not a conductor or fuse specification.'],formula:'DC input current ≈ AC watts ÷ (battery operating volts × inverter efficiency)'},
 {title:'Backup, grid forming and transfer behavior',paragraphs:['Grid-following conversion synchronizes with an existing AC reference; grid-forming equipment can establish one under supported conditions. Home backup still needs the manufacturer-approved isolation and transfer arrangement. Ask which circuits are supplied and which operating modes require storage or control accessories.','Draw distinct conceptual energy paths for grid-connected and islanded operation. Have the designer resolve neutral/ground behavior, service topology, generator interaction, AC coupling and protection. Do not backfeed a home receptacle to create an improvised utility connection.']},
 {title:'The battery ecosystem and ownership questions',paragraphs:['For low-voltage storage, check operating voltage, continuous and peak charge/discharge limits, approved BMS communication, firmware and fallback behavior. For proprietary high-voltage storage, confirm the exact battery family and mandatory control components. Expansion batteries are not interchangeable just because their nominal capacities match.','Ask what remains available without cloud service: local controls, alarms, schedules and a documented recovery process. Keep warranties for the inverter, batteries and transfer equipment together with the owner handover record. Installed-cost comparisons should include the entire required ecosystem.']},
 {title:'Questions to send to the supplier',bullets:['Can this exact configuration export, island, black start and recover after empty storage?','What is the continuous output per phase/leg, and the documented surge duration?','Which battery, transfer, generator and communication combinations are approved?','Which certifications, utility settings and installation clearances apply to this region?']}]},
 {slug:'dc-wiring-protection',title:'DC wiring, fuses, busbars and grounding: four checks that belong together',topic:'Electrical design',level:'Experienced',kind:'Guide',reviewed:'2026-10-04',summary:'Understand resistance, corrected ampacity, fault interruption and bonding before comparing electrical hardware.',tool:{label:'Open voltage-drop and protection calculators',href:'/guide/calculators?tool=voltage'},sources:[theory,wiring,ground],sections:[
 {title:'Voltage drop and ampacity answer different questions',paragraphs:['Resistance consumes voltage and dissipates heat; ampacity determines permissible current under the actual installation conditions. Passing a drop target does not establish ampacity. Record conductor material, cross-section, insulation, temperature assumptions, raceway arrangement and terminal limits before selecting a candidate.','For a hypothetical 48 V, 30 A load at 40 ft one-way length and 0.3951 Ω per 1,000 ft conductor resistance, the pair loses 0.94824 V, or about 1.98%. Doubling the length doubles the modeled drop. The current-path length includes both conductors; contact losses are additional. This example does not specify a cable gauge.'],formula:'Drop V = 2 × one-way ft × current A × resistance Ω/1,000 ft ÷ 1,000'},
 {title:'A planning fuse number is not a protection design',paragraphs:['A continuous-load example using 125% produces 50 A from 40 A. A 50 A device still needs the correct DC voltage and interrupt capability, compatibility with the conductors and terminals, and coordination with equipment limits. PV-source circuit rules and equipment instructions can require a different calculation.','Interrupt capability addresses the fault current a device can safely interrupt. Its normal ampere rating addresses another property. Do not substitute a household AC breaker for a battery DC protective device because both say 50 A. If the next modeled size exceeds corrected conductor ampacity, the workshop shows a conflict rather than approving the combination.']},
 {title:'Busbars and disconnects are interfaces',paragraphs:['Choose a documented covered busbar with suitable voltage/current ratings and terminals; count every incoming and outgoing current path. Include the protection for branches and the short unprotected portions of source conductors in the design. A busbar photo does not reveal its continuous rating or permissible lug arrangement.','A fuse holder is not automatically a load-break disconnect. Disconnect polarity, voltage rating, current rating and environmental suitability must fit the actual circuit. Keep PV-source, battery and AC protective boundaries distinct in a reviewable one-line diagram.']},
 {title:'Bonding and grounding are not synonyms for adding a rod',paragraphs:['Bonding maintains a required conductive fault path between exposed conductive parts. Grounding references the system to earth as specified by the design. A new earth rod cannot compensate for a missing required equipment bonding connection. Use the evaluated mounting, clamp, splice and lug combination for module/racking bonding.','Neutral-to-ground arrangements depend on service and inverter transfer behavior. A generic instruction to add or remove a bond can be wrong in another architecture. Have qualified personnel resolve the actual system and applicable requirements. This article organizes purchasing questions; it is not an energization or live-testing procedure.']},
 {title:'What to save in the parts record',bullets:['Conductor data and the corrected ampacity calculation, separate from drop.','Protective-device model, DC/AC rating, interrupt capacity and source fault assumptions.','Disconnect duty, polarity and enclosure/environment requirements.','Busbar and terminal hardware ratings, approved torque and assembly records.','One-line diagram showing bonding and transfer boundaries.']}]},
 {slug:'connectors-and-terminations',title:'PV connectors and battery lugs: a matching shape is not a matching connection',topic:'Electrical design',level:'Experienced',kind:'Guide',reviewed:'2026-10-04',summary:'Build a documented connection assembly: cable, contact, body, seal, tooling, lug and terminal all need to match.',tool:{label:'Browse wiring and connectors',href:'/?category=wiring'},sources:[staubli,wiring],sections:[
 {title:'Treat a PV connector as an assembly',paragraphs:['The connector body is only one part of the assembly. Record cable conductor size and outer diameter, contact, seal, body family, crimp die, locator, approved tool and current assembly instructions. A connector advertised as compatible by a seller is not the same as a documented approved mating pair.','Stäubli explicitly warns about cross-mating PV connector brands. Use the exact evaluated pair; do not infer compatibility from a successful click. Inspect supplied panel leads when comparing module variants, because a brand name or a photograph can hide a different connector family.']},
 {title:'The battery connection has its own limits',paragraphs:['Battery cables have to match the allowed conductor class and terminal system. Confirm the lug barrel, conductor material, stud size, terminal geometry and specified tooling. A tool that can physically crush a lug does not establish a qualified connection. Keep the manufacturer’s crimp and torque requirements attached to the work record.','High-current routing should avoid pulling on terminals, unsupported cable weight and abrasive movement. Terminal hardware and the lug seating arrangement need to follow the selected equipment instructions. Do not prescribe one generic torque or hardware stack for every battery.']},
 {title:'Diagnose the paperwork before the connection',paragraphs:['A useful incoming-parts check starts with traceability: model and part numbers, conductor markings, packaging condition and whether the seller has substituted components. If cable size, insulation diameter or tool compatibility is missing, leave that item unresolved. Resolve questions before installation, not after energization.','Qualified inspection may identify damaged seals, partial seating, displaced strands, contaminated interfaces, discoloration or unsupported leads. Owners should document visible concerns without opening live equipment. PV connectors must not be disconnected under load; follow the equipment-specific isolation and verification procedure through qualified personnel.']},
 {title:'Why very small resistance can matter',paragraphs:['As a hypothetical illustration, a 1 milliohm resistive connection carrying 100 A dissipates 10 W at that location; at 200 A it dissipates 40 W. A small resistance number can create concentrated heating because loss scales with the square of current. The example explains why workmanship matters, not how to measure a live terminal.'],formula:'Resistive loss W = current A² × resistance Ω'},
 {title:'A connection record to request',bullets:['Exact cable, connector/contact or lug and terminal part numbers.','Approved tooling and assembly method references.','Installation torque/crimp record where the manufacturer requires it.','Cable support and strain-relief inspection.','Documented corrective work and updated as-built record after substitutions.']}]},
 {slug:'all-in-one-buying-guide',title:'Portable station or whole-home battery? An all-in-one buying guide',topic:'Batteries & backup',level:'All levels',kind:'Guide',reviewed:'2026-10-04',summary:'Compare Pecron, Anker, EcoFlow and other integrated systems by usable energy, output, solar input and the cost of the complete setup.',tool:{label:'Compare all-in-one batteries',href:'/?category=all-in-one'},sources:[anker,source('DOE · Storage basics','https://www.energy.gov/cmei/systems/solar-integration-solar-energy-and-storage-basics')],sections:[
 {title:'Write the intended use before choosing a brand',paragraphs:['A power station for camping, an appliance backup unit and a permanently connected home storage system can share a product category while serving different jobs. List the loads, voltage, duration and whether you need manual appliance connections or a supported home transfer arrangement. Model names such as E3800, F3800 and C2000 do not replace the actual power and energy specifications.','An integrated station commonly combines storage, charging and an AC inverter. Verify the exact unit: some products are expansion batteries or DC-only packs. A promotional image may include panels, additional storage or a home power panel not included in the advertised base price.']},
 {title:'Compare six practical interfaces',columns:['Field','Question to answer'],rows:[['Energy','Nominal or usable Wh? Is an expansion pack included?'],['AC output','Continuous watts, supported voltage and surge duration?'],['Solar input','Voc maximum, operating range, current and watts per input?'],['Charging','AC charging limits, simultaneous-input behavior and recharge time?'],['Backup integration','Transfer equipment, circuits, supported modes and installed cost?'],['Ownership','Weight, temperature limits, warranty, service and local controls?']]},
 {title:'A runtime and recharge scenario',paragraphs:['A fictional 3.84 kWh station, 90% usable fraction and 90% delivery efficiency provides about 3.11 kWh to loads. At 500 W steady demand it lasts about 6.22 hours without incoming energy or extra idle losses. Whether it starts a compressor is still a separate power check.','Recharging 3 kWh at a sustained net 600 W takes about five hours before additional constraints. An advertised 1,200 W solar input is a ceiling, not a promise that the panel array supplies it every hour. Add the loads running while charging, and check expected weather and temperature.'],formula:'Runtime ≈ nominal kWh × usable fraction × delivery efficiency ÷ running load kW'},
 {title:'Choose panels using the actual input window',paragraphs:['A portable panel carrying the same brand may be convenient, but connector, voltage and current compatibility still decide the combination. Use the exact station’s manual and your module’s cold Voc, not only panel watts. Separate two input channels if the manufacturer gives separate limits.','A larger home system may accept much higher PV voltage than a compact camping station. That changes both the equipment and the installation requirements. Extension-cable voltage drop, connector compatibility and weather protection also belong in the comparison.']},
 {title:'Calculate the total package',paragraphs:['Compare base unit, expansion batteries, panels, required cables, transfer or smart-panel equipment, delivery and installation. Normalize price per usable kWh only when the stated usable capacities are comparable. Check whether maximum output or advertised expansion requires multiple power modules, not just battery packs.','Use the watch list for an exact acceptable configuration and compare observed retailer prices with the final checkout. Manufacturer peak-output claims and independent sustained-load results answer different questions; neither guarantees performance for your particular home.']},
 {title:'Before ordering',bullets:['Save the exact regional model/manual and the list of included components.','Check energy, continuous output and startup separately.','Verify solar voltage/current compatibility and expansion requirements.','Plan home connection through supported transfer equipment and qualified installation.','Compare complete delivered/installed cost, warranty and return logistics.']}]}
];
const briefing=(slug:string,title:string,topic:string,summary:string,sources:Source[],eventDate:string|undefined,sections:GuideSection[]):GuideArticle=>({slug,title,topic,summary,sources,eventDate,sections,level:'All levels',kind:'News & analysis',reviewed:'2026-10-04',origin:'PVPartPicker editorial briefing. Facts are attributed; implications and buying questions are our analysis.'});
const news:GuideArticle[]=[
 briefing('china-export-rebates','China’s solar export rebates changed in 2026. What should a buyer watch?', 'Policy & geopolitics','Separate an exporter tax-policy change from a retailer price forecast, and compare delivered offers.',[china],'2026-01-09',[
 {title:'What the official notice says',paragraphs:['Announcement 2026 No. 2 was dated January 8 and published January 9. It removes VAT export rebates for the listed photovoltaic products from April 1, 2026. For listed battery products, the rebate falls from 9% to 6% during April–December 2026 and is scheduled to end January 1, 2027. The annex lists and export declaration date determine applicability. This is a paraphrase of the official Chinese notice, not customs advice.'],sources:[china]},
 {title:'Our analysis: policy is one input to landed cost',paragraphs:['A rebate reduction does not mathematically require an identical percentage increase at your checkout. Inventory purchased earlier, supplier margins, exchange rates, shipping, destination duties and retailer competition can change how costs are passed through. A fixed retail-price prediction would need evidence from actual offers.','Compare the same regional model and package quantity over time. Separate observed prices from policy forecasts. A cheap overseas quote can omit transport, destination charges, warranty logistics or a local compliance requirement; a domestic warehouse offer can reflect older landed inventory.']},
 {title:'Practical buying questions',bullets:['Is stock already in a domestic warehouse, or is the order importing new supply?','Which delivery charges and import responsibilities are included in the written quote?','How long is the price valid, and who covers damage or warranty return freight?','Does a change on the history chart reflect the same model and package size?']},
 {title:'What remains uncertain',paragraphs:['The notice supports the policy timeline. It does not establish the future price of a particular panel or battery. Use current quotes and dated observed prices before making a decision; revisit the official notice for later amendments.']}]),
 briefing('sodium-storage-2026','Sodium-ion storage moves toward commercial delivery—but is it a home battery option?', 'Technology & products','CATL’s June 2026 announcement is an industrial-storage milestone. It is not proof of a drop-in rack battery.',[catl],'2026-06-22',[
 {title:'The announcement',paragraphs:['On June 22, 2026, CATL announced TENER Sodium. The company described the system as field validated and said first Chinese deliveries were planned for September 2026, with international deliveries scheduled for June 2027. Those are manufacturer statements and a schedule, not our independent confirmation that deliveries have occurred.'],sources:[catl]},
 {title:'Our analysis: availability is a system question',paragraphs:['An industrial energy-storage announcement does not establish a residential 48 V battery for sale in your region. Look for the actual enclosure, battery management, approved inverter interface, installation documentation, certifications and service arrangement. Chemistry alone does not answer those questions.','A new chemistry could diversify a future shortlist, but waiting for a headline has a cost if you need backup now. Compare an available, documented configuration against your load schedule. Avoid treating an anticipated product as a purchase option with a fabricated price.']},
 {title:'A useful evidence ladder',bullets:['Announcement: what the manufacturer claims and the intended market.','Production/delivery evidence: what has actually shipped and where.','Regional product: exact model, datasheet and approved installation.','System evidence: output, usable energy, operating temperature and service terms.','Observed offer: seller, condition, stock and actual complete cost.']},
 {title:'What to watch next',paragraphs:['Track published regional manuals and confirmed deliveries rather than assigning sodium-ion a universal performance rank. A future residential product can be evaluated in the same energy, power and interface framework as today’s storage.']}]),
 briefing('back-contact-commercial-scale','Back-contact panels are scaling: how to read the 2026 headlines', 'Technology & products','LONGi reported a commercial milestone in June. Use it as context, then compare the exact available module.',[longi],'2026-06-15',[
 {title:'The reported milestone',paragraphs:['On June 15, 2026, LONGi reported that its back-contact platform had passed a cumulative 60 GW in commercial sales and shipments. The announcement also includes forward-looking shipment targets. The milestone is company-reported; the targets are not completed deliveries and are not independent performance results.'],sources:[longi]},
 {title:'Our analysis: scale does not choose the module for you',paragraphs:['Commercial scale can expand the range of candidates and supplier experience, but a technology-family headline cannot settle fit, delivered cost or project energy yield. Separate cell architecture from n/p-type material and mono/bifacial face. A shortlist should still identify the exact regional model.','For a tight roof, compare watts per usable area and the resulting layout. For a ground mount, compare mechanical dimensions, clamp zones and rear-light assumptions. For either, check Voc, current, temperature coefficients and the inverter input. The latest acronym cannot waive these checks.']},
 {title:'What a useful product comparison includes',bullets:['Available model and wattage bin, not a laboratory cell record.','Module area, mass, front-side efficiency and published electrical limits.','Manufacturer reliability/warranty documentation and independent evidence where available.','Actual quantity and delivered cost, with installation compatibility.']},
 {title:'The decision',paragraphs:['Treat back contact as a candidate architecture, not a reason to discard an otherwise suitable TOPCon or other module. The right purchase is the documented product that fits the system and budget.']}]),
 briefing('anker-e10-system-brief','Anker SOLIX E10: read the system configuration behind the big numbers', 'Technology & products','Understand continuous output, temporary output and expansion before comparing a whole-home backup bundle.',[anker],'2026-01-12',[
 {title:'Manufacturer specifications, checked October 4',paragraphs:['Anker’s E10 system page lists 120/240 V split-phase output and 7,680 W continuous output for the power module with battery. It lists 10,000 W Turbo Backup for 90 minutes with two batteries. The page describes two PV inputs, each up to 4,500 W, with a 30–450 V DC range and 15 A operating-current limit. Use the exact regional manual and configuration to confirm all boundaries.'],sources:[anker]},
 {title:'Our analysis: compare configurations, not the family maximum',paragraphs:['An expansion headline may require several power modules, multiple batteries and supported transfer equipment. Put those components into the equipment total before comparing a base station with a complete automatic-backup bundle. Continuous and temporary output are not interchangeable.','Build the critical-load list and check startup separately. Check required permits, equipment locations, the service interface, supported grid/generator modes and who installs and services the system. A whole-home label does not establish unlimited duration or operation of every load at once.']},
 {title:'Questions to ask with the quote',bullets:['What output and energy apply to the exact included module/battery count?','Which home connection and automatic transfer equipment is included?','What is the complete installed price, and who owns commissioning and warranty support?','Which local functions remain available if internet service is unavailable?']},
 {title:'Evidence boundaries',paragraphs:['This is a specification-based briefing, not a hands-on review or a product ranking. A manufacturer’s runtime or starting-power claim must be tested against your load and supported system configuration.']}]),
 briefing('residential-credit-2026','Planning a U.S. residential project in 2026? Recheck the tax-credit assumption', 'Policy & geopolitics','The old automatic 30% assumption can distort a new project’s payback calculation.',[irs],undefined,[
 {title:'Current IRS guidance',paragraphs:['The 2025 Form 5695 instructions state that residential clean energy credits cannot be claimed for expenditures made after December 31, 2025. This is a current-policy explainer checked October 4, 2026, not a new announcement today. An unused qualifying prior credit and a new project are different situations. Review the current IRS guidance and the facts of your installation.'],sources:[irs]},
 {title:'Our analysis: build the cash-flow case without an assumed benefit',paragraphs:['The Guide payback tool defaults incentives to zero. Enter only a benefit verified for the project’s owner, location, timing and eligibility. State, utility, financing, business and third-party-ownership arrangements can involve different rules; do not transfer a household assumption to another ownership model.','Compare the installed cash cost before incentives, then enter eligible benefits separately. Include tariff value, self-consumption, export compensation and ongoing costs. A smaller equipment price does not automatically translate into the same payback after a policy change.']},
 {title:'A transparent hypothetical comparison',paragraphs:['For a fictional $20,000 project, assuming a 30% benefit reduces the modeled initial cost to $14,000. At $1,400 annual net savings and no other changes, simple arithmetic gives 10 years instead of about 14.3 years without that assumed benefit. These invented numbers illustrate sensitivity, not an eligibility claim or investment forecast.'],formula:'Simple screening payback = net upfront cost ÷ annual net savings'},
 {title:'Before entering an incentive',bullets:['Record the official program, owner/entity and eligible property.','Confirm timing, caps, qualification and whether the benefit is refundable or usable.','Keep cash purchase, finance charges and third-party ownership economics separate.','Use project-specific tax advice for an eligibility decision.']}]),
 briefing('supply-chain-resilience','Why “made here” is not a complete solar supply-chain story', 'Policy & geopolitics','The IEA’s 2026 report highlights concentration across supply-chain stages; buyers can ask better questions about support and substitutions.',[iea],undefined,[
 {title:'What the report adds',paragraphs:['The IEA’s Energy Technology Perspectives 2026 describes concentrated manufacturing across clean-energy supply chains and warns that the consequences of disruptions vary by technology and production step. Its scenarios are conditional analyses rather than a prediction of a specific shipment delay or retailer price. This briefing draws on the executive summary, checked October 4.'],sources:[iea]},
 {title:'Our analysis: trace the parts that make the system serviceable',paragraphs:['Local final assembly does not necessarily mean every cell, wafer, semiconductor or control component is local. Conversely, an imported product can have a strong local service network. Ask about the actual regional model, stocked replacements, authorized support and responsibility for warranty transport.','Supply interruptions can lead to substitutions. A revised panel current rating or battery firmware requirement can change an otherwise approved equipment match. Keep a record of the model and revision that was quoted, delivered and installed, and recheck compatibility when one changes.']},
 {title:'What to put in the purchasing brief',bullets:['Written model/revision and whether substitution needs approval.','Stock location, realistic lead time and delivery responsibility.','Local warranty contact and replacement-part availability.','Manufacturer compatibility evidence for replacement modules or batteries.','Observed price history, separated from assumptions about future trade policy.']},
 {title:'Avoid the shortcut',paragraphs:['A country label alone cannot prove quality, system compatibility or future price. Choose documented equipment and a complete service arrangement, and revisit source dates when policies or supply conditions change.']}])
];
export const guideArticles:GuideArticle[]=[...(foundations as GuideArticle[]),...advanced,...news].map(a=>({...a,sections:extendedLessons[a.slug]?[...a.sections.slice(0,-2),...extendedLessons[a.slug],...a.sections.slice(-2)]:a.sections}));
export const sectionId=(n:number)=>`section-${n+1}`;
export function readMinutes(a:GuideArticle){return Math.max(3,Math.ceil(JSON.stringify(a.sections).split(/\s+/).length/180));}
export type GuideEntry=Pick<GuideArticle,'slug'|'title'|'topic'|'level'|'kind'|'summary'|'reviewed'|'eventDate'>&{minutes:number};
export const guideEntries:GuideEntry[]=guideArticles.map(({slug,title,topic,level,kind,summary,reviewed,eventDate,...rest})=>({slug,title,topic,level,kind,summary,reviewed,eventDate,minutes:readMinutes({slug,title,topic,level,kind,summary,reviewed,...rest})}));
