import {calculators,moduleFields,moduleDefaults,validateValues,type CalculatorId,type Values} from './solar4u/calculator-config.ts';
import {batteryRuntime,voltageDrop,fuseBreaker,arrayVoltage,cableSizing,touBattery,payback} from './solar4u/calculators.mjs';
import {localEstimate} from './solar4u/model.mjs';
import {controllerShortlist} from './solar4u/controller-catalog.mjs';
export type {CalculatorId,Values};
export const calculatorDefinitions=calculators.map(d=>d.id==='controller'?{...d,description:'Check one complete array against four documented Victron models.',fields:[...moduleFields,...d.fields.map(f=>f.key==='tempCoefficientPercent'?{...f,label:'Module Voc temperature coefficient'}:f.key==='vmpCoefficientPercent'?{...f,label:'Module Vmp temperature coefficient'}:f)],defaults:{...moduleDefaults,...d.defaults}}:d.id==='pv'?{...d,name:'Solar production estimate',description:'Explore production with Solar4U’s simplified seasonal model.',fields:d.fields.filter(f=>['capacityKw','tilt','azimuth','latitude','lossesPercent','peakSunHours','electricityRate'].includes(f.key)),note:'Local estimate only: no weather data is fetched. Seasonal allocation, orientation and tilt factors are simplified. Use PVGIS or PVWatts for a climate-based study; shading, snow and actual equipment need separate modeling.'}:d.id==='cable'?{...d,note:'The catalog uses illustrative example ampacities and resistance values. Actual wiring method, conductor temperature, terminals and local rules determine permissible ampacity. This tool does not quote cable prices.'}:d);
export type Report={stats:{label:string,value:string,unit?:string}[],raw:Record<string,unknown>,notice:string,monthly?:number[],cash?:{year:number,cumulativeSavings:number,annualSavings:number}[],controllers?:{model:string,source:string,preliminaryMatch:boolean,powerLimited:boolean,failures:string[],nominalPower:number}[]};
const fmt=(v:number|null|undefined)=>v==null?'Undefined':v.toLocaleString('en-US',{maximumFractionDigits:2});
const stat=(label:string,v:number|null|undefined,unit='')=>({label,value:fmt(v),unit});
export function calculate(id:CalculatorId,v:Values,material:'copper'|'aluminum'='copper'):Report{
 const d=calculatorDefinitions.find(d=>d.id===id);if(!d)throw new Error('Unknown calculator');
 for(const f of d.fields){const x=v[f.key];if(typeof x!=='number'||!Number.isFinite(x)||x<f.min||x>f.max||(f.step===1&&!Number.isInteger(x))||(f.choices&&!f.choices.includes(x)))throw new Error(`Enter ${f.label} from ${f.min} to ${f.max}${f.unit?' '+f.unit:''}${f.step===1?' as a whole number':''}.`);}
 validateValues(id,Object.fromEntries(Object.entries(v).filter(([key])=>calculators.find(d=>d.id===id)!.fields.some(f=>f.key===key))));
 if(id==='pv'){const r=localEstimate(v);return{raw:{provider:r.provider,providerVersion:r.providerVersion,assumptions:r.assumptions,capacityKw:r.capacityKw,annualKwh:r.annualKwh,monthlyKwh:r.monthlyKwh,grossEnergyValue:r.yearlyBillValue},monthly:r.monthlyKwh,stats:[stat('Annual estimate',r.annualKwh,'kWh'),stat('Annual average per day',r.annualKwh/365,'kWh'),stat('Gross energy value',r.yearlyBillValue,'USD / year')],notice:'Solar4U simplified model · not measured production or a climate-data forecast. Gross value assumes every generated kWh receives the entered value.'};}
 if(id==='battery'){const r=batteryRuntime(v);return{raw:r,stats:[stat('Delivered usable energy',r.usableKwh,'kWh'),stat('Steady-load runtime',r.runtimeHours,'hours'),stat('Equivalent runtime',r.runtimeDays,'days')],notice:r.runtimeHours===null?'No running load: runtime is undefined. Enter a positive load to calculate duration.':'Assumes full starting charge. Running watts do not establish startup or inverter output capability.'};}
 if(id==='voltage'){const r=voltageDrop(v);return{raw:r,stats:[stat('Conductor-pair drop',r.dropVolts,'V'),stat('Voltage drop',r.dropPercent,'%'),stat('Load-end voltage',r.endVoltage,'V')],notice:r.dropVolts>=v.voltage?'This resistance/load case loses the entire source voltage; revise the assumptions.':r.dropPercent>3?'Above the 3% example planning target. Ampacity and installation conditions must also be checked.':'Within the 3% example drop target. This does not establish conductor ampacity.'};}
 if(id==='fuse'){const r=fuseBreaker(v);return{raw:r,stats:[stat('125% planning minimum',r.minimumAmps,'A'),stat('Next example standard size',r.recommendedAmps,'A'),stat('Entered corrected ampacity',v.conductorAmpacityA,'A')],notice:r.recommendedAmps===0?'Zero load: no protective device is selected.':r.conductorSuitable?'Entered ampacity covers this planning size only. Verify DC voltage, interrupt rating, equipment limits and applicable circuit rules.':'No suitable combination: this planning rating exceeds the entered corrected conductor ampacity.'};}
 if(id==='array'){const r=arrayVoltage(v);return{raw:r,stats:[stat('Cold open-circuit voltage',r.coldVoc,'V'),stat('STC operating voltage',r.arrayVmp,'V'),stat('Array short-circuit current',r.arrayIsc,'A'),stat('Array operating current',r.arrayImp,'A'),stat('Vmp × Imp array power',r.arrayWatts,'W')],notice:'Compare cold Voc against the absolute input limit. This tool does not check hot Vmp, MPPT startup, connectors or string protection; the controller tool checks additional limits.'};}
 if(id==='controller'){const r=controllerShortlist(v);return{raw:r,controllers:r.candidates,stats:[stat('Array power',r.array.arrayWatts,'W'),stat('Cold Voc',r.array.coldVoc,'V'),stat('Hot Vmp',r.hotVmp,'V')],notice:'One array per controller; no automatic string splitting. A preliminary match covers only modeled limits. Power above nominal is flagged separately; review oversizing with the manufacturer. Model catalog checked October 4, 2026.'};}
 if(id==='cable'){const r=cableSizing({...v,material});const raw={gauge:r.gauge,material:r.material,requiredAmpacity:r.requiredAmpacity,dropVolts:r.dropVolts,dropPercent:r.dropPercent,conductorFeet:r.conductorFeet,meetsDesignTarget:r.meetsDesignTarget};return{raw,stats:[{label:'Smallest example candidate',value:r.gauge??'No modeled size'},stat('125% planning ampacity',r.requiredAmpacity,'A'),stat('Selected voltage drop',r.dropPercent,'%')],notice:r.gauge?'Example table only: its ampacities are not code ampacities. Verify wiring method, temperature, terminal limits and actual conductor data before selection.':'No modeled conductor meets both constraints. The largest size is not a recommendation. Use actual corrected ampacities and conductor resistance.'};}
 if(id==='tou'){if(v.onPeakSharePercent+v.midPeakSharePercent>100)throw new Error('Peak and mid-peak shares must sum to 100% or less.');const r=touBattery(v);return{raw:r,stats:[stat('Energy shifted daily',r.shiftableKwh,'kWh'),stat('Rate-shifting capacity',r.touBatteryKwh,'kWh'),stat('Full-charge backup capacity',r.emergencyBatteryKwh,'kWh'),stat('Daily rate-shifting value',r.dailySavings,'USD'),stat('Annual rate-shifting value',r.annualSavings,'USD')],notice:r.dailySavings<0?'This rate-shifting scenario costs more than it saves. Battery wear and capital cost are additional.':'Excludes battery wear, capital costs, demand charges and tariff restrictions. Backup assumes full charge; routine shifting reduces outage reserve.'};}
 const r=payback(v);return{raw:r,cash:r.cashFlow,stats:[stat('Net installed cost',r.netCost,'USD'),stat('First-year net savings',r.firstYearSavings,'USD'),{label:'Modeled break-even year',value:r.netCost===0?'No upfront cost':r.paybackYear===null?'Not within 25 years':`${r.paybackYear} years`},stat('25-year net cash flow',r.twentyFiveYearNet,'USD')],notice:'Undiscounted scenario, not an investment forecast. Excludes financing, tax effects and replacements. Default incentive is 0%; verify eligibility before adding incentives.'};
}
