import type {Build,Product} from './types.ts';
import {categories} from './types.ts';
import {productListName} from './part-comparison.ts';
import {bestOffer,costForQuantity,validateBuild} from './domain.ts';
import {selectDrops,type PriceDrop} from './price-drops.ts';
import type {PageCatalog} from './catalog-transport.ts';
type Input=Record<string,unknown>;
export interface WebTool {name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean;consequentialHint:boolean};execute:(input:unknown,options:{signal?:AbortSignal})=>Promise<unknown>;}
export interface ToolRegistry {registerTool:(tool:WebTool,options:{signal:AbortSignal})=>void|Promise<void>;}
export interface PVToolState {path:string;build:Build;compare:string[];watchIds:string[];draftReady:boolean;watchReady:boolean;authenticated:boolean;catalogReady:boolean;}
export interface PVToolHost {state:()=>PVToolState;catalog:()=>Promise<Product[]>;request:(path:string,options?:RequestInit)=>Promise<any>;updateBuild:(fn:(build:Build)=>Build)=>Build;setCompare:(ids:string[])=>void;setWatch:(id:string,watched:boolean)=>Promise<void>;navigate:(href:string)=>void;}
function object(v:unknown,keys:string[]):Input {if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))throw new Error('Invalid tool parameters.');return v as Input;}
function text(v:unknown,max=180,optional=false):string|undefined {if(v===undefined&&optional)return undefined;if(typeof v!=='string'||!v.trim()||v.length>max)throw new Error('Enter a valid text value.');return v.trim();}
function choice(v:unknown,values:readonly string[],fallback?:string):string {if(v===undefined&&fallback!==undefined)return fallback;if(typeof v!=='string'||!values.includes(v))throw new Error('Choose a supported option: '+values.join(', '));return v;}
function integer(v:unknown,min:number,max:number,fallback?:number):number {if(v===undefined&&fallback!==undefined)return fallback;if(typeof v!=='number'||!Number.isInteger(v)||v<min||v>max)throw new Error(`Enter a whole number from ${min} to ${max}.`);return v;}
function bool(v:unknown,fallback=false):boolean {if(v===undefined)return fallback;if(typeof v!=='boolean')throw new Error('Enter true or false.');return v;}
const str=(maxLength=180)=>({type:'string',minLength:1,maxLength}),enm=(values:readonly string[])=>({type:'string',enum:values}),flag={type:'boolean'},limit={type:'integer',minimum:1,maximum:100};
const categoryIds=categories.map(c=>c.id),sections=['home','parts','product','build','builds','saved-builds','community-builds','deals','watchlist','tiers','guide','calculators','comparison'];
const copy=<T>(v:T):T=>structuredClone(v);
const cleanDraft=(value:Build):Build=>({...value,...validateBuild(value)});
export function createToolCatalog(read:()=>PageCatalog,load:()=>Promise<PageCatalog>,adopt:(catalog:PageCatalog)=>void,now:()=>number=Date.now){
 let pending:Promise<PageCatalog>|undefined;
 return async()=>{const current=read();if((current.expiresAt??0)>now())return current.products;
  if(!pending)pending=load().then(data=>{adopt(data);return data;}).finally(()=>{pending=undefined;});
  return (await pending).products;
 };
}
const tool=(name:string,title:string,description:string,properties:object,required:string[],readOnly:boolean,execute:WebTool['execute'],untrusted=true):WebTool=>({name:'pvpartpicker_'+name,title,description,inputSchema:{type:'object',properties,required,additionalProperties:false},annotations:{readOnlyHint:readOnly,untrustedContentHint:untrusted,consequentialHint:false},execute});
export function createPVTools(host:PVToolHost):WebTool[] {
 const known=async(id:unknown,signal?:AbortSignal)=>{signal?.throwIfAborted();const productId=text(id)!;if(!/^[a-zA-Z0-9_-]+$/.test(productId))throw new Error('Invalid product ID.');const p=(await host.catalog()).find(p=>p.id===productId);signal?.throwIfAborted();if(!p)throw new Error('Product not found in the current catalog.');return p;};
 const draft=()=>{if(!host.state().draftReady)throw new Error('Wait for the device draft or resolve its recovery notice.');};
 return [
 tool('get_workspace','Read workspace','Read section, readiness, categories and navigation destinations without loading the catalog or exposing account identity or location.',{},[],true,async(input,{signal})=>{object(input,[]);signal?.throwIfAborted();const s=host.state();return {path:s.path,catalogReady:s.catalogReady,draftReady:s.draftReady,watchReady:s.watchReady,signedIn:s.authenticated,buildName:s.build.name,buildParts:s.build.lines.length,watchCount:s.watchIds.length,comparisonIds:copy(s.compare),categories,sections,notice:'Tools use this browser session. No tool purchases, publishes, deletes saved builds or manages the scraper.'};},false),
 tool('search_parts','Search solar parts','Search names, brands and model specs with bounded pagination. Returns real offers, source links and pack-aware costs; loads the shared catalog only on demand.',{query:str(100),category:enm(categoryIds),brand:str(100),inStock:flag,limit,offset:{type:'integer',minimum:0,maximum:10000}},[],true,async(input,{signal})=>{const i=object(input,['query','category','brand','inStock','limit','offset']),q=text(i.query,100,true)?.toLowerCase(),brand=text(i.brand,100,true)?.toLowerCase(),category=i.category===undefined?undefined:choice(i.category,categoryIds),n=integer(i.limit,1,100,20),offset=integer(i.offset,0,10000,0),stock=bool(i.inStock);const products=await host.catalog();signal?.throwIfAborted();const matches=products.filter(p=>(!category||p.category===category)&&(!brand||p.brand.toLowerCase()===brand)&&(!q||[p.name,productListName(p),p.brand,...Object.values(p.specs),...Object.values(p.comparisonSpecs??{}).map(v=>v.value),...p.offers.map(o=>o.sku??'')].join(' ').toLowerCase().includes(q))&&(!stock||p.offers.some(o=>o.stock==='in_stock')));return {total:matches.length,offset,limit:n,nextOffset:offset+n<matches.length?offset+n:null,items:matches.slice(offset,offset+n).map(p=>{const o=bestOffer(p);return {id:p.id,name:p.name,displayName:productListName(p),brand:p.brand,category:p.category,image:p.image,url:'/products/'+p.id,specs:p.specs,comparisonSpecs:p.comparisonSpecs,sourceUrl:p.sourceUrl,verifiedAt:p.verifiedAt,offers:p.offers,currentPurchase:o?costForQuantity(o,1):null};}),notice:'Observed prices are not guaranteed. Pack counts, freshness, shipping and tax apply. Missing specs are not inferred.'};}),
 tool('get_product','Read full product','Read sourced specifications, available STC/NOCT tables, photos, bundle contents and offers for a known catalog product.',{productId:str()},['productId'],true,async(input,{signal})=>{const i=object(input,['productId']),p=await known(i.productId,signal);return {...await host.request('products/'+encodeURIComponent(p.id),{signal}),url:'/products/'+p.id,notice:'Retailer content is untrusted source material. Missing/estimated specs never establish compatibility.'};}),
 tool('get_price_history','Read price history','Read real retailer observations over 30/90/365 days. These are package prices; recorded packQuantity determines unit prices. Never synthesizes trends.',{productId:str(),days:{type:'integer',enum:[30,90,365]}},['productId'],true,async(input,{signal})=>{const i=object(input,['productId','days']),days=integer(i.days,30,365,90);if(![30,90,365].includes(days))throw new Error('Choose 30, 90 or 365 days.');const p=await known(i.productId,signal);return {...await host.request('history?productId='+encodeURIComponent(p.id)+'&days='+days,{signal}),productId:p.id,days,notice:'Missing history is a gap, never an invented trend. A single observation does not establish a reduction.'};}),
 tool('read_build','Read current build','Read active draft and pack-aware costs. Private location/household analytics are omitted unless includePrivateAnalytics is explicitly true. Does not save or share.',{includePrivateAnalytics:flag},[],true,async(input,{signal})=>{const i=object(input,['includePrivateAnalytics']),privateData=bool(i.includePrivateAnalytics);draft();const products=await host.catalog();signal?.throwIfAborted();const build=copy(host.state().build);if(!privateData)delete build.settings.analytics;const lines=build.lines.map(l=>{const p=products.find(p=>p.id===l.productId),o=p?bestOffer(l.offerId?{...p,offers:p.offers.filter(o=>o.id===l.offerId)}:p,l.quantity):undefined;return {...l,name:p?.name??'Unavailable product',purchase:o?costForQuantity(o,l.quantity):null};});return {build,lines,equipmentSubtotal:lines.reduce((s,l)=>s+(l.purchase?.subtotal??0),0),unpriced:lines.filter(l=>!l.purchase).length,privateAnalyticsOmitted:!privateData,notice:'Selected equipment subtotal only, before shipping/tax. Not a complete installed cost.'};}),
 tool('set_build_quantity','Set draft quantity','Set installed whole units. Zero removes the line; offerId selects a real retailer offer. Persists device draft but does not create a named saved build, purchase or share.',{productId:str(),quantity:{type:'integer',minimum:0,maximum:10000},offerId:str()},['productId','quantity'],false,async(input,{signal})=>{const i=object(input,['productId','quantity','offerId']),qty=integer(i.quantity,0,10000),offerId=text(i.offerId,180,true);signal?.throwIfAborted();draft();const p=await known(i.productId,signal);draft();if(offerId&&!p.offers.some(o=>o.id===offerId))throw new Error('Offer does not belong to this product.');const next=host.updateBuild(b=>{if(qty>0&&!b.lines.some(l=>l.productId===p.id)&&b.lines.length>=100)throw new Error('At most 100 product lines are allowed.');const lines=qty===0?b.lines.filter(l=>l.productId!==p.id):b.lines.some(l=>l.productId===p.id)?b.lines.map(l=>l.productId===p.id?{...l,quantity:qty,...(offerId?{offerId}:{})}:l):[...b.lines,{productId:p.id,quantity:qty,...(offerId?{offerId}:{})}];return cleanDraft({...b,lines});});const line=next.lines.find(l=>l.productId===p.id),o=line?bestOffer(line.offerId?{...p,offers:p.offers.filter(o=>o.id===line.offerId)}:p,qty):undefined,cost=o?costForQuantity(o,qty):null;return {updated:true,productId:p.id,quantity:line?.quantity??0,purchaseCost:cost?.subtotal??null,purchasedUnits:cost?.purchasedUnits??null,savedNamedBuild:false};}),
 tool('update_build','Update build direction','Rename the current draft or set its purpose/mount. Preserves equipment, string plans and analytics. Does not save a named build or publish.',{name:str(100),purpose:enm(['offgrid','hybrid','gridtie']),mount:enm(['roof','ground'])},[],false,async(input,{signal})=>{const i=object(input,['name','purpose','mount']);if(!Object.keys(i).length)throw new Error('Choose a build setting.');const name=text(i.name,100,true),purpose=i.purpose===undefined?undefined:choice(i.purpose,['offgrid','hybrid','gridtie']),mount=i.mount===undefined?undefined:choice(i.mount,['roof','ground']);signal?.throwIfAborted();draft();const b=host.updateBuild(b=>cleanDraft({...b,...(name?{name}:{}),settings:{...b.settings,...(purpose?{purpose:purpose as Build['settings']['purpose']} :{}),...(mount?{mount:mount as Build['settings']['mount']}:{})}}));return {name:b.name,purpose:b.settings.purpose,mount:b.settings.mount};}),
 tool('read_watchlist','Read watch list','Read device or signed-in account watch IDs. Does not create email alerts or disclose account identity.',{},[],true,async(input,{signal})=>{object(input,[]);signal?.throwIfAborted();const s=host.state();if(!s.watchReady)throw new Error('Watch list is loading or unavailable.');return {productIds:copy(s.watchIds),storage:s.authenticated?'account':'device'};}),
 tool('set_watch','Watch or unwatch','Set desired watch state idempotently through the existing device/account flow. Changes watch list; does not subscribe to email alerts.',{productId:str(),watched:flag},['productId','watched'],false,async(input,{signal})=>{const i=object(input,['productId','watched']);if(i.watched===undefined)throw new Error('Choose watched true or false.');const watched=bool(i.watched),p=await known(i.productId,signal);if(!host.state().watchReady)throw new Error('Watch list is not ready.');signal?.throwIfAborted();if(host.state().watchIds.includes(p.id)!==watched)await host.setWatch(p.id,watched);return {productId:p.id,watched,storage:host.state().authenticated?'account':'device'};}),
 tool('read_comparison','Read comparison','Read current comparison product IDs; up to four parts.',{},[],true,async(input,{signal})=>{object(input,[]);signal?.throwIfAborted();return {productIds:copy(host.state().compare)};}),
 tool('set_comparison','Choose comparison parts','Replace comparison with up to four known products; empty list clears it. No build or watch changes.',{productIds:{type:'array',items:str(),maxItems:4}},['productIds'],false,async(input,{signal})=>{const i=object(input,['productIds']);if(!Array.isArray(i.productIds)||i.productIds.length>4)throw new Error('Choose up to four products.');const ids=[...new Set(i.productIds.map(id=>text(id)!))];for(const id of ids)await known(id,signal);signal?.throwIfAborted();host.setCompare(ids);return {productIds:ids,url:'/compare'};}),
 tool('get_price_drops','Find price drops','Read recorded daily/weekly/monthly/latest reductions sorted by dollars, percent or time. Includes package prices and source timestamps.',{period:enm(['day','week','month','latest']),sort:enm(['dollars','percent','latest']),category:enm(categoryIds),minDollars:{type:'number',minimum:0,maximum:1000000},minPercent:{type:'number',minimum:0,maximum:100},limit},[],true,async(input,{signal})=>{const i=object(input,['period','sort','category','minDollars','minPercent','limit']),period=choice(i.period,['day','week','month','latest'],'day'),sort=choice(i.sort,['dollars','percent','latest'],'dollars') as 'dollars'|'percent'|'latest',category=i.category===undefined?undefined:choice(i.category,categoryIds),n=integer(i.limit,1,100,20);const numeric=(v:unknown,max:number)=>{if(v===undefined)return 0;if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max)throw new Error('Invalid drop minimum.');return v;};const minDollars=numeric(i.minDollars,1000000),minPercent=numeric(i.minPercent,100),products=await host.catalog(),result=await host.request('deals?period='+period,{signal});signal?.throwIfAborted();const drops=selectDrops(result.drops as PriceDrop[],{sort,minDollars,minPercent}).filter(d=>!category||products.find(p=>p.id===d.productId)?.category===category);return {period,checkedAt:result.checkedAt,total:drops.length,items:drops.slice(0,n).map(d=>({...d,name:products.find(p=>p.id===d.productId)?.name,url:'/products/'+d.productId})),notice:'Only recorded fresh eligible reductions. Missing data is not zero.'};}),
 tool('open_page','Open a site section','Navigate using the visible router to an allowed section/product/guide. No arbitrary, external, auth or admin URL. Build tab accepts equipment or analytics.',{section:enm(sections),category:enm(categoryIds),query:str(100),productId:str(),slug:str(100),builder:flag,tab:enm(['equipment','analytics'])},['section'],false,async(input,{signal})=>{const i=object(input,['section','category','query','productId','slug','builder','tab']),section=choice(i.section,sections),category=i.category===undefined?undefined:choice(i.category,categoryIds),q=text(i.query,100,true),builder=bool(i.builder),tab=i.tab===undefined?undefined:choice(i.tab,['equipment','analytics']);let href=({home:'/',parts:'/parts',build:'/build',builds:'/builds','saved-builds':'/builds/saved','community-builds':'/builds/community',deals:'/deals',watchlist:'/watchlist',tiers:'/tiers',guide:'/guide',calculators:'/guide/calculators',comparison:'/compare'} as Record<string,string>)[section];const params=new URLSearchParams();if(section==='product'){const p=await known(i.productId,signal);href='/products/'+p.id;if(builder)params.set('builder','1');}if(section==='parts'){if(category)params.set('category',category);if(q)params.set('q',q);if(builder)params.set('builder','1');}if(section==='build'&&tab)params.set('tab',tab);if(section==='guide'&&i.slug!==undefined){const slug=text(i.slug,100)!;if(!/^[a-z0-9-]+$/.test(slug))throw new Error('Invalid guide slug.');const {guideEntries}=await import('./guide-content.ts');if(!guideEntries.some(a=>a.slug===slug))throw new Error('Guide not found.');href='/guide/'+slug;}signal?.throwIfAborted();if(params.size)href+='?'+params;host.navigate(href);return {navigatingTo:href,notice:'Navigation requested; read workspace after page commit to verify arrival.'};}),
 tool('read_tiers','Read researched tier lists','Read existing editorial rankings, evidence and limitations, with fresh eligible price metrics. Rankings are judgments, not compatibility or performance guarantees.',{category:enm(['all-in-one','batteries','panels','inverters']),query:str(100),limit},['category'],true,async(input,{signal})=>{const i=object(input,['category','query','limit']),category=choice(i.category,['all-in-one','batteries','panels','inverters']) as 'all-in-one'|'batteries'|'panels'|'inverters',query=text(i.query,100,true),n=integer(i.limit,1,100,20);const {rankings,filterRankings,tierPrice,valueTier}=await import('./tiers.ts'),products=await host.catalog();signal?.throwIfAborted();const rows=filterRankings(rankings,{category,query});return {total:rows.length,items:rows.slice(0,n).map(r=>{const price=tierPrice(r,products);return {...r,price:price?{productId:price.product.id,retailer:price.offer.retailer,observedAt:price.offer.observedAt,unitPrice:price.unitPrice,purchasePrice:price.purchasePrice,metric:price.metric}:null,valueTier:valueTier(r,price)};})};}),
 tool('find_guides','Find solar guides','Search actual guide metadata; returns titles, review dates, summaries and internal links.',{query:str(100),limit:{type:'integer',minimum:1,maximum:40}},[],true,async(input,{signal})=>{const i=object(input,['query','limit']),q=text(i.query,100,true)?.toLowerCase(),n=integer(i.limit,1,40,15);const {guideEntries}=await import('./guide-content.ts');signal?.throwIfAborted();const entries=guideEntries.filter(a=>!q||[a.title,a.summary,a.topic].join(' ').toLowerCase().includes(q));return {total:entries.length,items:entries.slice(0,n).map(a=>({...a,url:'/guide/'+a.slug}))};}),
 tool('list_calculators','List calculator inputs','List available Solar4U calculator input ranges, defaults and caveats. Does not send location to external services.',{},[],true,async(input,{signal})=>{object(input,[]);const {calculatorDefinitions}=await import('./guide-calculators.ts');signal?.throwIfAborted();return calculatorDefinitions;}),
 tool('calculate','Run a planning calculator','Run an existing Solar4U calculator locally. Omitted fields use documented defaults. PV uses instant seasonal model, not PVGIS. Does not change build or transmit coordinates.',{calculator:str(30),values:{type:'object',additionalProperties:{type:'number'}},material:enm(['copper','aluminum'])},['calculator'],true,async(input,{signal})=>{const i=object(input,['calculator','values','material']),id=text(i.calculator,30),material=choice(i.material,['copper','aluminum'],'copper') as 'copper'|'aluminum';const {calculatorDefinitions,calculate}=await import('./guide-calculators.ts');signal?.throwIfAborted();const d=calculatorDefinitions.find(d=>d.id===id);if(!d)throw new Error('Unknown calculator. Use list_calculators.');const values=i.values===undefined?{}:object(i.values,d.fields.map(f=>f.key));if(Object.values(values).some(n=>typeof n!=='number'||!Number.isFinite(n)))throw new Error('Values must be finite numbers.');return calculate(d.id,{...d.defaults,...values as Record<string,number>},material);}),
 ];
}
export function registerTools(tools:WebTool[],registry?:ToolRegistry,onError:(message:string)=>void=()=>{}) {const controller=new AbortController();if(!registry)return()=>controller.abort();for(const t of tools){try{Promise.resolve(registry.registerTool(t,{signal:controller.signal})).catch(e=>{if(!controller.signal.aborted)onError(`WebMCP ${t.name}: ${String(e)}`);});}catch(e){onError(`WebMCP ${t.name}: ${String(e)}`);}}return()=>controller.abort();}
export function browserToolRegistry():ToolRegistry|undefined {return typeof document==='undefined'?undefined:(document as unknown as {modelContext?:ToolRegistry}).modelContext;}
export function analyticsReadTool(read:()=>Record<string,unknown>):WebTool {return tool('read_analytics_report','Read displayed analytics','Read currently displayed Analytics report and loading/error/invalid status. Only production is returned by default; full household financial results and location require includePrivateAssumptions true. Open Build → Analytics first. Instant estimates are not weather forecasts.',{includePrivateAssumptions:flag},[],true,async(input,{signal})=>{const i=object(input,['includePrivateAssumptions']),privateData=bool(i.includePrivateAssumptions);signal?.throwIfAborted();const r=copy(read());if(!privateData){delete r.settings;const report=r.report as {annualKwh?:number;months?:{month:string;generationKwh:number}[]}|null|undefined;r.report=report?{annualKwh:report.annualKwh,months:report.months?.map(m=>({month:m.month,generationKwh:m.generationKwh}))}:null;}return {...r,privateAssumptionsOmitted:!privateData};});}
