import type {Build,Product} from './types';
import {categories} from './types';
export function registerPVTools(products:Product[],build:Build,setBuild:(updater:(b:Build)=>Build)=>void){
 const registry=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:unknown)=>Promise<void>|void}}).modelContext;if(!registry)return()=>{};const controller=new AbortController();
 const tools=[{name:'pvpartpicker_search_parts',description:'Search the current solar catalog and read documented specs and retailer offers.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100},category:{type:'string',enum:categories.map(c=>c.id)}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:any)=>{if(!input||typeof input!=='object'||(input.query!==undefined&&(typeof input.query!=='string'||input.query.length>100)))throw new Error('Invalid search.');return products.filter(p=>(!input.category||p.category===input.category)&&(!input.query||p.name.toLowerCase().includes(input.query.toLowerCase()))).slice(0,20).map(p=>({id:p.id,name:p.name,specs:p.specs,offers:p.offers}));}},
 {name:'pvpartpicker_read_build',description:'Read the solar build currently open on this device.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>build},
 {name:'pvpartpicker_set_build_quantity',description:'Set a product quantity in the current solar draft. Zero removes it. This does not purchase or save a build.',inputSchema:{type:'object',properties:{productId:{type:'string'},quantity:{type:'integer',minimum:0,maximum:10000}},required:['productId','quantity'],additionalProperties:false},execute:(input:any)=>{if(!input||!products.some(p=>p.id===input.productId)||!Number.isInteger(input.quantity)||input.quantity<0||input.quantity>10000)throw new Error('Invalid part or quantity.');setBuild(b=>({...b,lines:input.quantity===0?b.lines.filter(l=>l.productId!==input.productId):b.lines.some(l=>l.productId===input.productId)?b.lines.map(l=>l.productId===input.productId?{...l,quantity:input.quantity}:l):b.lines.length<100?[...b.lines,{productId:input.productId,quantity:input.quantity}]:b.lines}));return{updated:true};}}];
 for(const tool of tools)Promise.resolve(registry.registerTool(tool,{signal:controller.signal})).catch(()=>{});return()=>controller.abort();
}
