'use client';
import {useRef,useState} from 'react';
import {X} from 'lucide-react';
import type {Product} from '../lib/types';
import {bestOffer,costForQuantity,money} from '../lib/domain';
import {productListName} from '../lib/part-comparison';
import {usePV,api} from './pv-provider';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
export function AlertModal({product,onClose}:{product:Product;onClose:()=>void}){
 const{user,notify}=usePV();const[quantity,setQuantity]=useState(1),[target,setTarget]=useState(''),[email,setEmail]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const previousFocus=useRef<HTMLElement|null>(typeof document==='undefined'?null:document.activeElement as HTMLElement),current=bestOffer(product,quantity);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api('alerts',{method:'POST',body:JSON.stringify({productId:product.id,quantity,target:Number(target),emailEnabled:email})});notify(email&&!r.emailConfigured?'Alert saved. Website notifications are active; email delivery awaits sender configuration.':'Price alert saved.');onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="build-dialog price-alert-dialog" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();previousFocus.current?.focus();}}><div className="modal-header"><DialogTitle>Set a target-price alert</DialogTitle><button className="icon-button" disabled={busy} onClick={onClose} aria-label="Close price alert"><X size={20}/></button></div><DialogDescription>{productListName(product)}</DialogDescription>{user?<form onSubmit={submit}><label className="field">Requested units<input type="number" min="1" max="10000" step="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} required/></label><label className="field">Notify me when equipment cost is $<input type="number" step="0.01" min="0.01" max="1000000" value={target} onChange={e=>setTarget(e.target.value)} placeholder={current?String(Math.round(costForQuantity(current,quantity).subtotal*.9)):''} required/></label><p className="inline-note">{current?'Current minimum purchase: '+money(costForQuantity(current,quantity).subtotal)+'. ':''}Package quantities apply. Shipping and tax excluded.</p><label className="check-field"><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)}/>Also email me at {user.email}</label>{error&&<p className="error-message" role="alert">{error}</p>}<button className="button dark full" disabled={busy}>{busy?'Saving…':'Create price alert'}</button></form>:<><p>Sign in for target alerts and notifications across devices. You can watch this product on your device without signing in.</p><a className="button dark full" target="_top" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/products/'+product.id)}>Sign in with ChatGPT</a></>}</DialogContent></Dialog>;
}
