'use client';
import {useEffect,useState} from 'react';
import Link from './site-link';
import {BuildOpenAction} from './build-open-action';
import {ProductImage} from './pv-provider';
import {resolveExample,exampleBudget,type ExampleBuild} from '../lib/example-builds';
import type {Product} from '../lib/types';
import {money} from '../lib/domain';
import {productListName} from '../lib/part-comparison';
type ExamplesResponse={examples:ExampleBuild[];products:Product[]};
export function BuildExamples(){
 const [data,setData]=useState<ExamplesResponse>(),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[budget,setBudget]=useState('All'),[purpose,setPurpose]=useState('All');
 useEffect(()=>{const controller=new AbortController();let active=true;const deadline=setTimeout(()=>controller.abort(),15000);setError('');fetch('/api/example-builds',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Could not load example builds.');return r.json() as Promise<ExamplesResponse>;}).then(v=>{if(active)setData(v);}).catch(e=>{if(active)setError(e.name==='AbortError'?'Loading timed out. Please try again.':e.message);}).finally(()=>clearTimeout(deadline));return()=>{active=false;clearTimeout(deadline);controller.abort();};},[attempt]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')setAttempt(n=>n+1);};const interval=setInterval(refresh,120000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',refresh);};},[]);
 const rows=(data?.examples??[]).map(e=>({e,r:resolveExample(e,data!.products)})).filter(({e,r})=>(purpose==='All'||purpose===e.useCase)&&(budget==='All'||budget===exampleBudget(r.total,r.unpriced))).sort((a,b)=>Number(!!a.r.unpriced)-Number(!!b.r.unpriced)||a.r.total-b.r.total);
 return <section id="example-builds" className="example-builds compact-examples"><span id="planning-examples"/><h2 className="sr-only">Example builds</h2>
 <div className="example-compact-toolbar example-pill-toolbar"><div className="example-filter-row"><span>Budget</span><div className="deal-category-shortcuts" role="group" aria-label="Build budget">{[{value:'All',label:'All budgets'},{value:'Low',label:'Low · under $5,000'},{value:'Mid',label:'Mid · $5,000–$9,999'},{value:'High',label:'High · $10,000+'},{value:'Unpriced',label:'Needs current prices'}].map(v=><button type="button" key={v.value} aria-pressed={budget===v.value} onClick={()=>setBudget(v.value)}>{v.label}</button>)}</div></div><div className="example-filter-row"><span>System</span><div className="deal-category-shortcuts" role="group" aria-label="Build system">{['All','Portable','Off-grid','Hybrid / backup','On-grid'].map(v=><button type="button" key={v} aria-pressed={purpose===v} onClick={()=>setPurpose(v)}>{v==='All'?'All systems':v}</button>)}</div></div><span aria-live="polite">{data?`${rows.length} builds · price low to high`:'Loading builds…'}</span></div>
 <p className="example-budget-note">Budget = core equipment only. Mounting, wiring, shipping, tax and installation are additional.</p>
 {!data&&!error&&<p role="status">Loading selected parts and current offers…</p>}{error&&<p role="alert">{error} <button className="text-link" onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>}
 <div className="example-card-grid">{rows.map(({e,r})=>{return <article className="example-build" key={e.id}>
 <div className="example-build-description"><small>{e.useCase==='On-grid'?'On-grid · no backup':e.useCase} · {exampleBudget(r.total,r.unpriced)}{r.unpriced?'':' budget'}</small><h3>{e.name}</h3></div>
 <dl className="example-highlights">{e.highlights.map(h=>{const split=h.match(/^(.+?(?:kWh|kW|W)) (.+)$/);return <div key={h}><dt>{split?.[2]??'System'}</dt><dd>{split?.[1]??h}</dd></div>;})}</dl>
 <ul className="example-card-equipment">{r.selections.map(s=><li key={s.line.productId}><b>{s.line.quantity} ×</b> {s.product?productListName(s.product):'Unavailable product'}</li>)}</ul>
 <div className="example-build-price"><span>{r.unpriced?'Priced equipment subtotal':'Equipment subtotal'}</span><strong>{r.unpriced===r.selections.length?'Price unavailable':money(r.total)}</strong><small>{r.unpriced?`${r.unpriced} selection(s) need a current offer. `:''}Core equipment only.</small>{r.missing?<span role="status">A selected product is unavailable. Copy is disabled until restored.</span>:<BuildOpenAction target={r.build} label="Customize" copy navigate/>}</div>
 <details className="example-build-details"><summary>Parts & details · {r.selections.length} {r.selections.length===1?'selection':'selections'}</summary><div className="example-parts-list">{r.selections.map(s=><div key={s.line.productId}><span className="example-line-photo">{s.product&&<ProductImage product={s.product}/>}<span>{s.line.quantity} ×</span></span><div>{s.product?<Link href={'/products/'+s.product.id}>{productListName(s.product)}</Link>:<strong>Unavailable product</strong>}<small>{s.offer?`${s.offer.retailer} · ${s.cost!.packs} package(s) of ${s.offer.packQuantity}${s.cost!.extraUnits?' · '+s.cost!.extraUnits+' extra units':''} · checked ${s.offer.observedAt.slice(0,16).replace('T',' ')} UTC`:'No fresh in-stock offer'}</small></div><strong>{s.cost?money(s.cost.subtotal):'Unpriced'}</strong></div>)}</div><div className="example-expanded-total"><span>{r.unpriced?'Priced items subtotal':'Total equipment price'}</span><strong>{r.unpriced===r.selections.length?'Price unavailable':money(r.total)}</strong>{r.unpriced>0&&<small>{r.unpriced} selection(s) need current prices.</small>}</div><div className="example-sources">{e.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label} ↗</a>)}</div></details>
 </article>;})}</div>{data&&!rows.length&&<p role="status">No examples match. <button className="text-link" onClick={()=>{setBudget('All');setPurpose('All');}}>Show all builds</button></p>}<p className="example-build-note">Examples are curated equipment lists, separate from community submissions. Subtotals use fresh in-stock offers and whole-package purchase costs. Site-specific installation parts are additional.</p></section>;
}
