'use client';
import {useState} from 'react';
import {Bookmark,FolderOpen,Link2,Plus,Trash2,Users} from 'lucide-react';
import Link from './site-link';
import {usePV,api} from './pv-provider';
import {BuildOpenAction} from './build-open-action';
import {deviceBuildsKey,readDeviceBuilds,isDeviceBuild,purposeLabel} from '../lib/build-library';
import type {SavedBuild} from '../lib/build-library';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from './ui/alert-dialog';

export function BuildLibraryToolbar(){
 const {build,user,draftReady,saving,save,setBuild,notify}=usePV();
 const [dialog,setDialog]=useState<'library'|'copy'|'share'|'more'|null>(null),[saved,setSaved]=useState<SavedBuild[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[publication,setPublication]=useState<string|null>(null),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState<SavedBuild|null>(null);
 const disabled=!draftReady||saving||busy;
 async function loadLibrary(){setLoading(true);setError('');try{const device=readDeviceBuilds(localStorage.getItem(deviceBuildsKey));setSaved(device);if(user){const result=await api('builds');setSaved([...result.builds,...device]);}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function show(which:'library'|'copy'|'share'){
  setDialog(which);setError('');setLink('');
  if(which==='library')await loadLibrary();
  if(which==='copy')setName((build.name.slice(0,93)+' (copy)').slice(0,100));
  if(which==='share'){setDescription('');setPublication(null);if(user&&build.id&&!isDeviceBuild(build.id)){setLoading(true);try{const result=await api('builds/'+build.id);setPublication(result.communityShareId||null);setDescription(result.communityDescription||'');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}}
 }
 async function share(publish:boolean){setBusy(true);setError('');try{const id=await save();if(!id)throw new Error('Save the build before sharing. Check its name and parts, then try again.');const result=await api(publish?'community':'builds/'+id,{method:publish?'POST':'PATCH',body:JSON.stringify(publish?{buildId:id,description}:{})});const url=location.origin+(publish?'/community/':'/share/')+result.shareId;setLink(url);if(publish){setPublication(result.shareId);notify('Your build is now in Community builds.');}else notify('Read-only link created. Use Copy link to share it.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function withdraw(){if(!build.id)return;setBusy(true);setError('');try{await api('community/'+build.id,{method:'DELETE'});setPublication(null);setLink('');notify('Removed from Community builds. Your saved build is still private.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!deleting)return;setBusy(true);setError('');try{if(isDeviceBuild(deleting.id)){const existing=readDeviceBuilds(localStorage.getItem(deviceBuildsKey));localStorage.setItem(deviceBuildsKey,JSON.stringify(existing.filter(b=>b.id!==deleting.id)));}else await api('builds/'+deleting.id,{method:'DELETE'});setBuild(current=>current.id===deleting.id?{name:current.name,lines:current.lines,settings:current.settings}:current);setDeleting(null);await loadLibrary();notify('Saved build deleted. The current draft has been kept.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <>
  <div className="builder-library-actions"><button className="button dark small" disabled={disabled} onClick={()=>save()}><Bookmark size={15}/>{saving?'Saving…':'Save build'}</button><button className="button outline small" disabled={disabled} onClick={()=>show('library')}><FolderOpen size={15}/>Saved builds</button><button className="button outline small" disabled={disabled} onClick={()=>setDialog('more')} aria-haspopup="dialog">More actions</button></div>
  <Dialog open={dialog!==null} onOpenChange={open=>{if(!open&&!busy&&!saving)setDialog(null);}}><DialogContent className={'build-dialog '+(dialog==='library'?'build-library-dialog':'')}><DialogHeader><DialogTitle>{dialog==='more'?'Build actions':dialog==='library'?'Saved builds':dialog==='copy'?'Save a new build':'Share this build'}</DialogTitle><DialogDescription>{dialog==='more'?'Manage the current build, open saved versions, or share it.':dialog==='library'?'Open a saved setup and pick up where you left off.':dialog==='copy'?'Keep the current saved version and give this copy its own name.':'Choose a read-only link or publish a copy for the community.'}</DialogDescription></DialogHeader>
   {dialog==='more'&&<div className="build-more-actions"><BuildOpenAction target={{name:'My solar build',lines:[],settings:{purpose:'offgrid',mount:'roof'}}} label="New build" className="button outline small" onOpened={()=>setDialog(null)}/><button className="button outline small" disabled={disabled} onClick={()=>show('share')}><Link2 size={15}/>Share</button><button className="button outline small" disabled={disabled} onClick={()=>show('copy')}><Plus size={15}/>Save as new</button><button className="button outline small" disabled={disabled} onClick={()=>show('library')}><FolderOpen size={15}/>Saved builds</button><Link className="button outline small" href="/builds/community" onClick={()=>setDialog(null)}><Users size={15}/>Community builds</Link></div>}
   {error&&<p className="error-message" role="alert">{error}</p>}
   {dialog==='library'&&<><div className="build-library-note"><span>{user?'Account builds sync across devices.':'Device builds stay in this browser.'}</span>{!user&&<a className="text-link" href="/signin-with-chatgpt?return_to=%2Fbuild" target="_top">Sign in for account saves</a>}</div>{loading&&<p role="status">Loading your builds…</p>}<div className="saved-build-list">{saved.map(b=><article className="saved-build-item" key={b.id}><div><h3>{b.name}</h3><p>{b.lines.length} parts · {purposeLabel[b.settings.purpose]} · {b.settings.mount==='roof'?'Roof':'Ground'}</p><small>{isDeviceBuild(b.id)?'This device':'Account'} · saved {new Date(b.updatedAt).toLocaleDateString()}{b.communityShareId?' · In community':''}</small></div><div className="flex-actions"><BuildOpenAction target={b} onOpened={()=>setDialog(null)}/>{b.communityShareId&&<Link className="text-link small-text" href={'/community/'+b.communityShareId}>Public version</Link>}<button className="icon-button" disabled={busy} aria-label={'Delete saved build '+b.name} onClick={()=>setDeleting(b)}><Trash2 size={16}/></button></div></article>)}</div>{!loading&&!error&&!saved.length&&<div className="empty-state"><FolderOpen size={26}/><h3>Your next setup belongs here.</h3><p>Name your current build, then choose Save build.</p></div>}<p className="inline-note">Saving an opened build updates it. Save as new keeps a separate version.</p></>}
   {dialog==='copy'&&<form onSubmit={async e=>{e.preventDefault();if(await save({asNew:true,name}))setDialog(null);}}><label className="field">Build name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><p className="inline-note">{user?'Saved privately to your account.':'Saved on this device. You can sign in to save it to your account later.'}</p><button className="button dark" disabled={disabled||!name.trim()} type="submit">{saving?'Saving…':'Save new build'}</button></form>}
   {dialog==='share'&&(!user?<div className="build-share-signin"><p>Your build can stay on this device. Sign in to create a link or publish it.</p><a className="button dark" href="/signin-with-chatgpt?return_to=%2Fbuild" target="_top">Sign in with ChatGPT</a></div>:<><section className="build-share-section"><h3>Share by link</h3><p>Anyone with the link can view the equipment and open their own copy. Analytics location and financial assumptions stay private.</p><button className="button outline small" disabled={disabled||loading} onClick={()=>share(false)}>Create read-only link</button></section><section className="build-share-section"><h3>{publication?'Your community version':'Add to Community builds'}</h3><p>Your build name, parts, quantities, settings, and note will be public. Your account details, analytics location and financial assumptions stay private. Future saves change your private build until you publish an update.</p><label className="field">Build note (optional)<textarea maxLength={500} rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this setup for? Anything another builder should check?"/></label><div className="flex-actions"><button className="button dark small" disabled={disabled||loading||!build.lines.length} onClick={()=>share(true)}>{busy?'Working…':publication?'Publish updated version':'Publish to community'}</button>{publication&&<><Link className="text-link" href={'/community/'+publication}>View public version</Link><button className="text-link" disabled={disabled||loading} onClick={withdraw}>Withdraw from community</button></>}</div></section>{link&&<div className="build-share-link"><label className="field">Build link<input readOnly value={link} aria-label="Build link" onFocus={e=>e.target.select()}/></label><button className="button outline small" onClick={async()=>{try{await navigator.clipboard.writeText(link);notify('Build link copied.');}catch{notify('Select the build link and copy it from the field.');}}}>Copy link</button></div>}</>)}
  </DialogContent></Dialog>
  <AlertDialog open={Boolean(deleting)} onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><AlertDialogContent className="build-dialog"><AlertDialogHeader><AlertDialogTitle>Delete “{deleting?.name}”?</AlertDialogTitle><AlertDialogDescription>This removes the saved version{deleting?.communityShareId?' and its community publication':''}. Your current draft stays available.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="button outline small">Cancel</AlertDialogCancel><button className="button dark small" disabled={busy} onClick={remove}>{busy?'Deleting…':'Delete saved build'}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
