'use client';
import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {BarChart3,Download,MapPin,Plus,Printer,RefreshCw,X} from 'lucide-react';
import {usePV} from './pv-provider';
import Link from './site-link';
import CalculatorChart from './calculator-chart';
import {analyticsDefaults,analyticsFinancials,analyticsRanges,buildAnalyticsInputs,monthNames,validateAnalytics} from '../lib/build-analytics';
import type {AnalyticsLocation,AnalyticsSettings} from '../lib/build-analytics';
import {solarProduction} from '../lib/solar-production';
import type {Report} from '../lib/guide-calculators';
import type {Product} from '../lib/types';
import {analyticsPrerequisites} from '../lib/build-guidance';
import {money} from '../lib/domain';
import type {AddressResult} from '../lib/analytics-location';
import {analyticsReadTool,registerTools,browserToolRegistry} from '../lib/webmcp';
const LocationMap=lazy(()=>import('./analytics-location-map'));
const climateCache=new Map<string,{expires:number;report:Report}>();
const number=(n:number,digits=0)=>n.toLocaleString('en-US',{maximumFractionDigits:digits});

function NumberField({label,value,min,max,step=1,onChange,onValidity,hint}:{label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void;onValidity:(label:string,valid:boolean)=>void;hint?:string}) {
 const [text,setText]=useState(String(value));
 useEffect(()=>{setText(String(value));onValidity(label,true);},[value,label]); // saved-build changes reset field drafts
 const valid=text.trim()!==''&&Number.isFinite(Number(text))&&Number(text)>=min&&Number(text)<=max;
 return <label className="field analytics-field">{label}<input type="number" inputMode="decimal" min={min} max={max} step={step} value={text} aria-invalid={!valid} onChange={e=>{const text=e.target.value,n=Number(text),ok=text.trim()!==''&&Number.isFinite(n)&&n>=min&&n<=max;setText(text);onValidity(label,ok);if(ok)onChange(n);}}/>{!valid?<small className="analytics-input-error">Enter {min}–{max}.</small>:hint&&<small>{hint}</small>}</label>;
}

function InputSection({title,children,id}:{title:string;children:React.ReactNode;id?:string}) {
 const [open,setOpen]=useState(true);
 useEffect(()=>{if(window.matchMedia('(max-width:760px)').matches)setOpen(false);},[]);
 return <details id={id} className="section-card analytics-input-section" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary><h3>{title}</h3></summary><div>{children}</div></details>;
}

export default function BuildAnalyticsReport({products}:{products:Product[]}) {
 const {build,setBuild}=usePV();
 const s=build.settings.analytics??analyticsDefaults,inputs=buildAnalyticsInputs(build,products);
 const capacity=s.capacityOverrideKw??inputs.capacityKw;
 const prerequisites=analyticsPrerequisites({capacityKw:capacity,capacityComplete:inputs.capacityComplete,hasLocation:Boolean(s.location),unpriced:inputs.unpriced,hasCostOverride:s.totalCostOverride!==undefined,selectionCount:build.lines.length}),needsSetup=prerequisites.some(p=>!p.complete);
 const [invalid,setInvalid]=useState<string[]>([]),[query,setQuery]=useState(''),[results,setResults]=useState<AddressResult[]>([]),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState('');
 const [coordinateDraft,setCoordinateDraft]=useState({latitude:'',longitude:''}),[coordinateError,setCoordinateError]=useState('');
 const [climate,setClimate]=useState<{key:string;report?:Report;loading:boolean;error?:string}>({key:'',loading:false}),[retry,setRetry]=useState(0);
 const searchAbort=useRef<AbortController|null>(null),searchVersion=useRef(0);
 const location=s.location;
 function update(patch:Partial<AnalyticsSettings>){setBuild(b=>({...b,settings:{...b.settings,analytics:{...(b.settings.analytics??analyticsDefaults),...patch}}}));}
 function faceShares(n:number){return Array.from({length:n},(_,i)=>i===n-1?100-Math.round(100/n*100)/100*(n-1):Math.round(100/n*100)/100);}
 function setShare(index:number,sharePercent:number){const otherTotal=100-s.faces[index].sharePercent,remaining=100-sharePercent;update({faces:s.faces.map((f,i)=>i===index?{...f,sharePercent}:{...f,sharePercent:remaining*f.sharePercent/otherTotal})});}
 function validity(label:string,valid:boolean){setInvalid(prev=>valid?prev.filter(v=>v!==label):prev.includes(label)?prev:[...prev,label]);}
 function chooseLocation(l:AnalyticsLocation){update({location:l,...(!s.location&&!build.settings.analytics?{faces:s.faces.map(f=>({...f,azimuth:l.latitude<0?0:180}))}:{})});searchVersion.current++;searchAbort.current?.abort();setSearching(false);setResults([]);setSearchError('');}
 useEffect(()=>{setCoordinateDraft({latitude:location?String(location.latitude):'',longitude:location?String(location.longitude):''});setCoordinateError('');},[location?.latitude,location?.longitude]);
 useEffect(()=>()=>{searchVersion.current++;searchAbort.current?.abort();},[]);
 async function search(e:React.FormEvent){e.preventDefault();searchAbort.current?.abort();const controller=new AbortController(),version=++searchVersion.current;searchAbort.current=controller;setSearching(true);setSearchError('');setResults([]);
  try{const r=await fetch('/api/solar-calculator?kind=address',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query}),signal:controller.signal});const data=await r.json() as {error?:string;locations:AddressResult[]};if(!r.ok)throw new Error(data.error||'Address search unavailable.');if(version!==searchVersion.current)return;setResults(data.locations);if(!data.locations.length)setSearchError('No matching locations. Try a city/postal code or pick a map point.');}
  catch(e){if(!controller.signal.aborted&&version===searchVersion.current)setSearchError((e as Error).message);}finally{if(version===searchVersion.current)setSearching(false);}
 }
 const production=useMemo(()=>{
  if(!location||capacity<=0||capacity>1000||!inputs.capacityComplete)return null;
  try{validateAnalytics(s);const arrays=s.faces.map(f=>({capacityKw:capacity*f.sharePercent/100,tilt:f.tilt,azimuth:f.azimuth}));const values={capacityKw:capacity,latitude:location.latitude,longitude:location.longitude,tilt:arrays[0].tilt,azimuth:arrays[0].azimuth,lossesPercent:s.lossesPercent,peakSunHours:s.peakSunHours,annualUsageKwh:10000,electricityRate:0};return {values,arrays,instant:solarProduction(values,arrays)};}catch{return null;}
 },[location?.latitude,location?.longitude,capacity,inputs.capacityComplete,s.faces,s.lossesPercent,s.peakSunHours]);
 const physicalKey=production?JSON.stringify({values:{...production.values,peakSunHours:4},arrays:production.arrays}):'';
 useEffect(()=>{
  if(!production||!physicalKey)return;
  const cached=climateCache.get(physicalKey);if(cached&&cached.expires>Date.now()){setClimate({key:physicalKey,report:cached.report,loading:false});return;}
  const controller=new AbortController();setClimate({key:physicalKey,loading:true});
  const timeout=setTimeout(()=>{void (async()=>{
   try{const params=new URLSearchParams({kind:'climate',inputs:JSON.stringify({...production.values,peakSunHours:4}),arrays:JSON.stringify(production.arrays)});const response=await fetch('/api/solar-calculator?'+params,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(65000)])});const data=await response.json() as Report & {error?:string};if(!response.ok)throw new Error(data.error||'Climate estimate unavailable.');if(!Array.isArray(data.monthly)||data.monthly.length!==12||data.monthly.some((n:unknown)=>typeof n!=='number'||!Number.isFinite(n)||n<0))throw new Error('Climate service returned incomplete data.');if(controller.signal.aborted)return;if(climateCache.size>=40)climateCache.delete(climateCache.keys().next().value!);climateCache.set(physicalKey,{expires:Date.now()+3600000,report:data});setClimate({key:physicalKey,report:data,loading:false});}
   catch(e){if(!controller.signal.aborted)setClimate({key:physicalKey,loading:false,error:(e as Error).message});}
  })();},700);
  return()=>{clearTimeout(timeout);controller.abort();};
 },[physicalKey,retry]);
 const currentClimate=climate.key===physicalKey?climate:undefined;
 const report=currentClimate?.report??production?.instant;
 let financial:ReturnType<typeof analyticsFinancials>|undefined,settingsError='';
 try{validateAnalytics(s);if(report?.monthly)financial=analyticsFinancials(report.monthly,s,inputs.equipmentCost,inputs.unpriced===0,build.settings.purpose);}catch(e){settingsError=(e as Error).message;}
 const isClimate=Boolean(currentClimate?.report),issues=invalid.length>0||Boolean(settingsError);
 const agentReport=useRef<Record<string,unknown>>({});
 agentReport.current={status:issues?'invalid':!production?'needs-location-or-capacity':currentClimate?.loading?'loading':currentClimate?.error?'fallback':'ready',capacityKw:capacity,provider:report?.raw.provider,notice:report?.notice,error:settingsError||currentClimate?.error,invalidFields:invalid,settings:s,report:issues?null:financial};
 useEffect(()=>registerTools([analyticsReadTool(()=>agentReport.current)],browserToolRegistry(),message=>console.warn(message)),[]);
 const field=(key:keyof typeof analyticsRanges,label:string,step=1,hint?:string)=>{const [min,max]=analyticsRanges[key];return <NumberField key={key} label={label} value={s[key]??0} min={min} max={max} step={step} hint={hint} onChange={n=>update({[key]:n})} onValidity={validity}/>;};
 function download(){if(!financial||issues)return;const content=JSON.stringify({buildName:build.name,generatedAt:new Date().toISOString(),settings:s,capacityKw:capacity,equipmentCost:inputs.equipmentCost,unpriced:inputs.unpriced,provider:report?.raw,report:financial,notice:'Long-term estimated monthly production, not a forecast. Monthly load is uniform; self-consumption is an assumption. USD nominal cash flow; not a battery dispatch or tax calculation.'},null,2);const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pvpartpicker-build-analytics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="build-analytics" aria-labelledby="analytics-heading">
  {needsSetup&&<section className="analytics-prerequisites" aria-label="Report prerequisites"><h3>Before generating your report</h3><ul>{prerequisites.map(p=><li key={p.key}><strong>{p.complete?'✓ ':''}{p.label}</strong><span>{p.complete?'Connected to this build.':p.detail}</span>{!p.complete&&p.key==='capacity'&&<Link href="/parts?category=panels&builder=1">Choose solar panels →</Link>}</li>)}</ul><p>Review location, array direction, electricity use and cost assumptions below. This is a production estimate; storage dispatch and installation readiness are not inferred.</p></section>}
  <header className="analytics-heading"><div><h2 id="analytics-heading"><BarChart3 size={20}/> Your build, through the seasons.</h2><p>Choose your location. See monthly energy, savings and the cost of getting there.</p></div><div className="flex-actions analytics-export"><button className="button outline small" disabled={!financial||issues} onClick={download}><Download size={14}/>Download report</button><button className="button outline small" disabled={!financial||issues} onClick={()=>window.print()}><Printer size={14}/>Print</button></div></header>
  <div className="analytics-workspace">
   <div className="analytics-inputs">
    <section className="section-card" id="analytics-location"><h3><MapPin size={17}/> 1. Your location</h3><form className="analytics-search" onSubmit={search}><label className="field">Address, city or postal code<input value={query} maxLength={200} minLength={3} required placeholder="Search your location…" autoComplete="off" onChange={e=>{searchVersion.current++;searchAbort.current?.abort();setSearching(false);setResults([]);setQuery(e.target.value);}}/></label><button className="button dark small" disabled={searching}>{searching?'Searching…':'Find'}</button></form>{searchError&&<p role="status" className="inline-note">{searchError}</p>}{results.length>0&&<ul className="analytics-location-results" aria-label="Matching locations">{results.map((l,i)=><li key={i}><button onClick={()=>chooseLocation(l)}><strong>{l.label}</strong><small>{l.precision} · verify the point on the map</small></button></li>)}</ul>}
     <Suspense fallback={<p role="status">Loading map…</p>}><LocationMap location={location} onChoose={chooseLocation}/></Suspense>
     {location&&<><p className="analytics-selected-location"><strong>{location.label}</strong><span>{location.latitude.toFixed(5)}°, {location.longitude.toFixed(5)}°</span></p><a className="analytics-mobile-result-link button outline small" href="#build-report-results">View your report ↓</a></>}
     <details><summary>Enter coordinates instead</summary><form className="analytics-coordinates" onSubmit={e=>{e.preventDefault();const lat=Number(coordinateDraft.latitude),lon=Number(coordinateDraft.longitude);if(!coordinateDraft.latitude.trim()||!coordinateDraft.longitude.trim()||!Number.isFinite(lat)||Math.abs(lat)>66||!Number.isFinite(lon)||Math.abs(lon)>180){setCoordinateError('Enter latitude −66 to 66 and longitude −180 to 180.');return;}setCoordinateError('');chooseLocation({latitude:lat,longitude:lon,label:'Entered coordinates'});}}><label className="field">Latitude<input type="number" step="any" min={-66} max={66} required value={coordinateDraft.latitude} onChange={e=>setCoordinateDraft(d=>({...d,latitude:e.target.value}))}/></label><label className="field">Longitude<input type="number" step="any" min={-180} max={180} required value={coordinateDraft.longitude} onChange={e=>setCoordinateDraft(d=>({...d,longitude:e.target.value}))}/></label><button className="button outline small">Apply coordinates</button>{coordinateError&&<p role="alert">{coordinateError}</p>}</form></details>
     <p className="micro">Search sends your query to Photon. Map tiles use OpenStreetMap; climate estimates send coordinates to PVGIS. Location and financial assumptions stay out of shared builds.</p>
    </section>
    <InputSection id="analytics-array" title="2. Array & roof"><div className="analytics-derived"><strong>{number(inputs.capacityKw,2)} kW</strong><span>from your selected panels · updates with quantities</span></div>{inputs.unknownSolar.length>0&&<p className="inline-note">{inputs.unknownSolar.length} panel, bundle or unavailable selections need a confirmed total PV rating. Included bundle panels are not counted automatically.</p>}
     <label className="analytics-option"><input type="checkbox" checked={s.capacityOverrideKw!==undefined} onChange={e=>{if(!e.target.checked)setInvalid(prev=>prev.filter(v=>v!=='Total panel capacity (kW)'));update({capacityOverrideKw:e.target.checked?inputs.capacityKw:undefined});}}/> Enter total PV capacity manually</label>{s.capacityOverrideKw!==undefined&&field('capacityOverrideKw','Total panel capacity (kW)',.1,'Use panel nameplate watts, not inverter output or battery kWh.')}
     {s.faces.map((face,i)=><div className="analytics-roof-face" key={i}><div className="analytics-face-heading"><strong>Roof face {i+1}</strong>{s.faces.length>1&&<button className="icon-button" aria-label={'Remove roof face '+(i+1)} onClick={()=>{const faces=s.faces.filter((_,j)=>i!==j);setInvalid(prev=>prev.filter(v=>!new RegExp('^Face '+s.faces.length+' ·').test(v)));update({faces:faces.map((f,i)=>({...f,sharePercent:faceShares(faces.length)[i]}))});}}><X size={14}/></button>}</div><div className="analytics-fields"><NumberField label={`Face ${i+1} · capacity (%)`} value={face.sharePercent} min={s.faces.length===1?100:.01} max={100-.01*(s.faces.length-1)} step={.1} onValidity={validity} onChange={n=>setShare(i,n)}/><NumberField label={`Face ${i+1} · tilt (°)`} value={face.tilt} min={0} max={90} onValidity={validity} onChange={n=>update({faces:s.faces.map((f,j)=>j===i?{...f,tilt:n}:f)})}/><NumberField label={`Face ${i+1} · direction (°)`} value={face.azimuth} min={0} max={360} onValidity={validity} onChange={n=>update({faces:s.faces.map((f,j)=>j===i?{...f,azimuth:n}:f)})}/></div></div>)}
     <p className="micro">0° north · 90° east · 180° south · 270° west. Tilt is measured from horizontal. Shares rebalance automatically to total 100%.</p><button className="button outline small" disabled={s.faces.length>=4} onClick={()=>{const count=s.faces.length+1;update({faces:[...s.faces,{sharePercent:0,tilt:30,azimuth:location&&location.latitude<0?0:180}].map((f,i)=>({...f,sharePercent:faceShares(count)[i]}))});}}><Plus size={14}/>Add roof face</button>
     <div className="analytics-fields">{field('lossesPercent','System losses (%)',1,'PVGIS aggregate system-loss input; default 14%.')}{field('peakSunHours','Fallback sun hours / day',.1,'Only used when climate data is unavailable.')}</div>
    </InputSection>
    <InputSection title="3. Usage & electricity"><div className="analytics-fields">{field('annualUsageKwh','Annual electricity use (kWh)',100)}{field('electricityRate','Retail / avoided rate ($/kWh)',.01)}{build.settings.purpose!=='offgrid'&&field('exportRate','Export credit ($/kWh)',.01,'Enter your utility’s export rate; default $0.')}{field('selfConsumptionPercent','On-site use of generation (%)',1,'Your assumption; capped by monthly electricity use.')}</div><p className="micro">Annual usage is spread evenly across 12 months. Battery selection does not predict self-consumption. {build.settings.purpose==='offgrid'?'Off-grid surplus is valued at $0; the avoided rate is an energy-cost comparison.':'Hourly usage and tariff rules may change actual savings.'}</p></InputSection>
    <InputSection title="4. Investment & payback"><div className="analytics-derived"><strong>{money(inputs.equipmentCost)}</strong><span>current pack-aware equipment subtotal{inputs.unpriced>0?` · ${inputs.unpriced} unpriced selections`:''}</span></div><label className="analytics-option"><input type="checkbox" checked={s.totalCostOverride!==undefined} onChange={e=>{setInvalid(prev=>prev.filter(v=>v!==(e.target.checked?'Installation, shipping & tax ($)':'Total installed cost ($)')));update({totalCostOverride:e.target.checked?inputs.equipmentCost+s.additionalCost:undefined});}}/> Enter a complete installed quote</label><div className="analytics-fields">{s.totalCostOverride!==undefined?field('totalCostOverride','Total installed cost ($)',100,'Replaces equipment subtotal and additional costs.'):field('additionalCost','Installation, shipping & tax ($)',100,'Add costs beyond the selected equipment.')}{field('incentive','Confirmed incentives / rebates ($)',100,'Enter only incentives you expect to receive.')}{field('annualMaintenance','Annual maintenance ($)',10)}</div><details><summary>Long-term assumptions</summary><div className="analytics-fields">{field('degradationPercent','Annual generation decline (%)',.1)}{field('rateEscalationPercent','Annual rate increase (%)',.1)}{field('discountPercent','Discount rate (%)',.1)}</div></details><p className="micro">All costs are USD. No incentive is assumed. Replacement costs, financing and fixed utility charges are excluded; add replacement allowances to costs if needed.</p></InputSection>
   </div>
   <div className="analytics-results" id="build-report-results" aria-busy={currentClimate?.loading}>
    {!location?<div className="analytics-empty"><MapPin size={25}/><h3>Find your place in the sun.</h3><p>Search an address or choose a map point to create your report.</p><small>{capacity>0?'Selected panel quantities are connected; verify array direction and cost assumptions.':'Choose solar panels or enter total PV capacity. No solar array is selected yet.'}</small></div>:!inputs.capacityComplete?<div className="analytics-empty"><h3>Confirm your full array capacity.</h3><p>The known panels total {number(inputs.capacityKw,2)} kW, but some panel or bundle ratings are missing. Enter the complete installed PV capacity in Array & roof to calculate generation and payback for this build.</p></div>:capacity<=0||capacity>1000?<div className="analytics-empty"><h3>Add your solar array.</h3><p>Select panels in Equipment or enter the combined panel capacity here (up to 1,000 kW). Battery capacity and inverter output are not PV generation.</p><Link className="button dark small" href="/parts?category=panels&builder=1">Choose solar panels</Link></div>:<>
     <div className="analytics-source" role="status"><div><strong>{isClimate?'PVGIS climate estimate':currentClimate?.loading?'Updating climate estimate…':'Solar4U instant estimate'}</strong><span>{isClimate?'Long-term monthly averages · auto-updates with your array and location':'Simplified seasonal model · fallback sun-hours assumption'}</span></div><button className="icon-button" aria-label="Refresh climate estimate" disabled={currentClimate?.loading} onClick={()=>{climateCache.delete(physicalKey);setRetry(n=>n+1);}}><RefreshCw size={16}/></button></div>
     {currentClimate?.error&&<p className="inline-note" role="status">{currentClimate.error} Showing the instant model. <button className="text-link" onClick={()=>{climateCache.delete(physicalKey);setRetry(n=>n+1);}}>Retry climate data</button></p>}
     {(issues||settingsError)&&<p className="inline-note" role="alert">{settingsError||'Complete the highlighted inputs to update the report.'}</p>}
     {financial&&!issues&&<>
      <div className="analytics-stats"><div><span>Annual generation</span><strong>{number(financial.annualKwh)} <small>kWh</small></strong><small>{number(financial.annualKwh/365,1)} kWh / day average</small></div><div><span>{build.settings.purpose==='offgrid'?'Annual energy cost offset':'Annual bill savings'}</span><strong>{money(financial.annualSavings)}</strong><small>Before maintenance · year 1</small></div><div><span>Annual energy / use</span><strong>{financial.energyOffsetPercent===null?'—':number(financial.energyOffsetPercent,1)+'%'}</strong><small>Generation ÷ use; not self-sufficiency</small></div><div><span>Simple payback</span><strong>{financial.simplePayback===null?'—':<>{number(financial.simplePayback,1)} <small>years</small></>}</strong><small>{financial.netCost===null?'Complete the installed cost':financial.annualNet<=0?'No positive annual net savings':'Net cost ÷ year-one net savings'}</small></div></div>
      {s.totalCostOverride===undefined&&s.additionalCost===0&&<p className="inline-note">{inputs.unpriced>0?'Enter a complete installed quote to calculate payback; some selected parts have no current price.':'Payback currently uses equipment cost only. Enter installation, shipping and tax or a complete quote for a fuller estimate.'}</p>}
      <div className="section-card analytics-chart"><CalculatorChart title="Monthly solar generation" labels={monthNames} unit="kWh" bars series={[{name:'Solar generation',values:financial.months.map(m=>m.generationKwh),color:'var(--chart-1)'},{name:'Electricity use',values:financial.months.map(m=>m.loadKwh),color:'var(--chart-2)'}]}/><p className="micro">These are typical calendar-month estimates, not next month’s weather forecast. {isClimate?'PVGIS uses historical climate data.':'The instant model uses seasonal geometry and your sun-hours input.'}</p></div>
      <div className="analytics-summary section-card"><h3>Where the energy & money go</h3><dl><div><dt>On-site solar use</dt><dd>{number(financial.usedKwh)} kWh / yr</dd></div><div><dt>{build.settings.purpose==='offgrid'?'Unvalued surplus':'Export / surplus'}</dt><dd>{number(financial.exportedKwh)} kWh / yr</dd></div><div><dt>Net installed cost</dt><dd>{financial.netCost===null?'Needs complete pricing':money(financial.netCost)}</dd></div><div><dt>Year-one savings after maintenance</dt><dd>{money(financial.annualNet)}</dd></div><div><dt>{build.settings.purpose==='offgrid'?'Variable energy cost offset':'Variable electricity bill offset'}</dt><dd>{financial.billOffsetPercent===null?'—':number(financial.billOffsetPercent,1)+'%'}</dd></div><div><dt>Projected break-even</dt><dd>{financial.netCost===null?'Needs complete pricing':financial.breakEvenYear===null?'Not reached within 25 years':number(financial.breakEvenYear,1)+' years'}</dd></div><div><dt>25-year net cash flow</dt><dd>{financial.cashFlow[24].cumulative===null?'Needs complete pricing':money(financial.cashFlow[24].cumulative!)}</dd></div><div><dt>25-year discounted value (NPV)</dt><dd>{financial.npv===null?'Needs complete pricing':money(financial.npv)}</dd></div></dl></div>
      <section className="section-card analytics-monthly"><h3>Month-by-month report</h3><div className="analytics-table-wrap" role="region" tabIndex={0} aria-label="Monthly production and savings"><table><thead><tr><th>Month</th><th>Solar kWh</th><th>On-site kWh</th><th>Surplus kWh</th><th>Offset ($)</th></tr></thead><tbody>{financial.months.map(m=><tr key={m.month}><th scope="row">{m.month}</th><td>{number(m.generationKwh,1)}</td><td>{number(m.usedKwh,1)}</td><td>{number(m.exportedKwh,1)}</td><td>{money(m.savings)}</td></tr>)}</tbody><tfoot><tr><th scope="row">Annual</th><td>{number(financial.annualKwh,1)}</td><td>{number(financial.usedKwh,1)}</td><td>{number(financial.exportedKwh,1)}</td><td>{money(financial.annualSavings)}</td></tr></tfoot></table></div></section>
      {financial.netCost!==null&&<section className="section-card analytics-chart"><CalculatorChart title="25-year cumulative net cash flow" labels={financial.cashFlow.map(r=>String(r.year))} unit="USD" xTitle="Years after installation" series={[{name:'After initial cost & maintenance',values:financial.cashFlow.map(r=>r.cumulative!),color:'var(--chart-3)'}]}/><p className="micro">Nominal rates grow {s.rateEscalationPercent}% / yr; production declines {s.degradationPercent}% / yr. Discounted value uses {s.discountPercent}%. Financing, replacements and tariff changes are not modeled.</p></section>}
      <section className="section-card analytics-method"><h3>How to read this report</h3><p>Solar capacity = selected panel watts × unit quantities. Retailer pack minimums affect the purchase cost, not the number of installed panels. An explicit capacity override is required for panels inside bundles or missing ratings.</p><p>On-site use = the smaller of monthly load or generation × your use percentage. Savings = on-site kWh × retail rate + surplus kWh × export credit. Monthly balance does not model hourly loads, battery dispatch or outage autonomy.</p><p>{isClimate?'PVGIS models fixed crystalline-silicon arrays, free-standing mounting and terrain horizon.':'Solar4U’s simplified seasonal model uses latitude, direction, tilt, loss and sun-hours assumptions.'} Nearby trees/buildings, roof ventilation, snow, bifacial gains and inverter clipping are not individually modeled. Check the Equipment tab’s compatibility notes; this report does not certify the build.</p><p>Saving your build also saves these private assumptions. Published and shared copies omit the location and financial settings. A downloaded report contains your entered location; share it deliberately.</p><a className="text-link" href="https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis/using-pvgis-5/api-non-interactive-service_en" target="_blank" rel="noreferrer">PVGIS methodology & API</a><span> · </span><Link className="text-link" href="/guide/calculators?tool=pv">Explore the Solar4U production calculator</Link></section>
     </>}
    </>}
   </div>
  </div>
 </section>;
}
