'use client';
import {useEffect,useId,useMemo,useState} from 'react';
import {ArrowRight,Battery,CheckCircle2,HelpCircle,Plus,Sparkles,Trash2,AlertTriangle} from 'lucide-react';
import Link from './site-link';
import {ProductImage,usePV} from './pv-provider';
import {productListName} from '../lib/part-comparison';
import {connectionMap,receiverLimits,selectedReceivers,suggestArray,type ConnectionCheck} from '../lib/connection-map';
import type {PVArray,Product,Compatibility} from '../lib/types';

const label=(s:Compatibility['status'])=>s==='match'?'Within listed limits':s==='mismatch'?'Needs attention':'Needs verification';
function Status({value}:{value:Compatibility['status']}){const Icon=value==='match'?CheckCircle2:value==='mismatch'?AlertTriangle:HelpCircle;return <span className={'connection-status status-'+value}><Icon size={13}/>{label(value)}</span>;}
function NumberField({label,value,min,max,onChange,onError}:{label:string;value?:number;min:number;max:number;onChange:(n:number|undefined)=>void;onError:(error:boolean)=>void}){
 const [text,setText]=useState(value===undefined?'':String(value)),errorId=useId();
 useEffect(()=>{setText(value===undefined?'':String(value));onError(false);},[value]);
 const n=text.trim()?Number(text):undefined,error=n!==undefined&&(!Number.isFinite(n)||n<min||n>max||min===1&&!Number.isInteger(n));
 return <label className="connection-field">{label}<input type="number" aria-label={label} aria-describedby={error?errorId:undefined} min={min} max={max} step={min===1?'1':'any'} value={text} aria-invalid={error||min>=1&&!text.trim()} onChange={e=>{const next=e.target.value,parsed=next.trim()?Number(next):undefined,bad=parsed!==undefined&&(!Number.isFinite(parsed)||parsed<min||parsed>max||min===1&&!Number.isInteger(parsed));setText(next);onError(bad||min>=1&&parsed===undefined);if(!bad&&(min<1||parsed!==undefined))onChange(parsed);}}/>{error&&<small id={errorId} role="alert">{min===1?'Enter a whole number':'Enter a number'} from {min} to {max}.</small>}</label>;
}
function PartTitle({product,fallback}:{product?:Product;fallback:string}){return <div className="connection-product">{product?<><ProductImage product={product}/><Link href={'/products/'+product.id} title={product.name}>{productListName(product)}</Link></>:<strong>{fallback}</strong>}</div>;}
function CheckRows({checks,invalid}:{checks:ConnectionCheck[];invalid:boolean}){return <div className="connection-check-table"><table><thead><tr><th>Check</th><th>Calculation / recorded limit</th><th>Result</th></tr></thead><tbody>{checks.map(c=><tr key={c.key}><th scope="row">{c.title}</th><td>{c.detail}{c.source&&<> <a href={c.source} target="_blank" rel="noreferrer">Source</a></>}</td><td><Status value={invalid?'unknown':c.status}/></td></tr>)}</tbody></table></div>;}
const fmt=(n:number|undefined,unit:string)=>n===undefined?'Not documented':`${Number(n.toFixed(2))} ${unit}`;

export function BuildConnectionMap({products,loading,loadError,onRetry}:{products:Product[];loading:boolean;loadError:string;onRetry:()=>void}){
 const {build,setBuild}=usePV();
 const map=useMemo(()=>connectionMap(build,products),[build,products]),arrays=build.settings.pvArrays||[],receivers=selectedReceivers(build,products);
 const batteries=products.filter(p=>build.lines.some(l=>l.productId===p.id)&&p.category==='batteries'&&p.specs.batteryKind!=='Battery cabinets');
 const [errors,setErrors]=useState<Record<string,boolean>>({}),[messages,setMessages]=useState<Record<string,string>>({});
 const invalid=Object.values(errors).some(Boolean),totalAssigned=map.allocations.reduce((n,a)=>n+Math.min(a.used,a.quantity),0),totalPanels=map.allocations.reduce((n,a)=>n+a.quantity,0);
 function error(key:string,bad:boolean){setErrors(e=>({...e,[key]:bad}));}
 function change(id:string,patch:Partial<PVArray>){setMessages(m=>({...m,[id]:''}));setBuild(b=>({...b,settings:{...b.settings,pvArrays:(b.settings.pvArrays||[]).map(a=>a.id===id?{...a,...patch}:a)}}));}
 function add(){const p=map.allocations.find(a=>a.remaining>0)?.panel||map.allocations[0]?.panel;if(!p)return;
  const r=receivers.length===1?receivers[0]:undefined,tracker=r?Array.from({length:receiverLimits(r).count||1},(_,i)=>i+1).find(t=>!arrays.some(a=>a.receiverId===r.id&&a.receiverUnit===1&&a.tracker===t))||1:1;
  setBuild(b=>({...b,settings:{...b.settings,pvArrays:[...(b.settings.pvArrays||[]),{id:crypto.randomUUID(),panelId:p.id,receiverId:r?.id,receiverUnit:1,tracker,series:1,parallel:1,batteryId:batteries.length===1&&r?.category!=='all-in-one'?batteries[0].id:undefined}]}}));
 }
 function remove(id:string){setBuild(b=>({...b,settings:{...b.settings,pvArrays:(b.settings.pvArrays||[]).filter(a=>a.id!==id)}}));setErrors(e=>Object.fromEntries(Object.entries(e).filter(([key])=>!key.startsWith(id+':'))));}
 const unassignedBatteries=batteries.filter(p=>!arrays.some(a=>a.batteryId===p.id));
 return <section id="compatibility" className="builder-connections" aria-labelledby="connections-heading">
  <header className="connection-heading"><div><h2 id="connections-heading">3. System connections</h2><p>Plan each panel string, see which input it uses, and check battery voltage.</p></div><span className="connection-allocation">{totalAssigned} / {totalPanels} panels assigned</span></header>
  {loading&&<p className="connection-warning" role="status">Loading selected equipment’s electrical ratings…</p>}{loadError&&<p className="connection-warning" role="alert">{loadError} <button className="button outline small" onClick={onRetry}>Retry specifications</button></p>}
  <div className="connection-conditions"><NumberField label="Lowest site temperature (°C)" value={build.settings.minimumTemperature} min={-70} max={60} onError={bad=>error('min',bad)} onChange={n=>setBuild(b=>({...b,settings:{...b.settings,minimumTemperature:n}}))}/><NumberField label="Maximum panel cell temperature (°C)" value={build.settings.maximumCellTemperature??70} min={25} max={100} onError={bad=>error('max',bad)} onChange={n=>setBuild(b=>({...b,settings:{...b.settings,maximumCellTemperature:n}}))}/><p>Cold raises panel voltage. Hot cells lower operating voltage. <strong>70°C is a planning assumption</strong>; adjust it for your installation.</p></div>
  {invalid&&<p className="connection-warning" role="alert">Correct the highlighted inputs. Numbers below reflect the last valid values; checks are unverified until corrected.</p>}
  <div className="connection-allocation-list">{map.allocations.map(a=><span key={a.panel.id} className={'status-'+a.status}><strong>{productListName(a.panel)}</strong> · {a.used} / {a.quantity} panels{a.remaining>0?` · ${a.remaining} unassigned`:a.remaining<0?` · ${-a.remaining} too many assigned`:''}</span>)}</div>
  <div className="connection-column-labels" aria-hidden="true"><span>Panel strings</span><span>Inverter / MPPT input</span><span>Battery voltage</span></div>
  {map.arrays.map((row,index)=>{const a=row.array,limits=row.limits,values=row.values;return <article className="connection-array" key={a.id} aria-label={'Array '+(index+1)}>
   <div className="connection-array-bar"><strong>Array {index+1} <small>· {a.series}S × {a.parallel}P · {a.series*a.parallel} panels</small></strong><Status value={invalid?'unknown':row.status}/><button className="icon-button" aria-label={'Remove array '+(index+1)} onClick={()=>remove(a.id)}><Trash2 size={14}/></button></div>
   <div className="connection-flow">
    <div className="connection-node connection-panel-node"><PartTitle product={row.panel} fallback="Panel removed"/><label className="connection-field">Panel model<select aria-label={'Panel model for array '+(index+1)} value={a.panelId} onChange={e=>change(a.id,{panelId:e.target.value})}>{!row.panel&&<option value={a.panelId}>Unavailable panel</option>}{map.allocations.map(p=><option value={p.panel.id} key={p.panel.id}>{productListName(p.panel)}</option>)}</select></label>
     <div className="connection-string-controls"><NumberField label="Panels in series" value={a.series} min={1} max={200} onError={bad=>error(a.id+':series',bad)} onChange={n=>change(a.id,{series:n!})}/><NumberField label="Parallel strings" value={a.parallel} min={1} max={200} onError={bad=>error(a.id+':parallel',bad)} onChange={n=>change(a.id,{parallel:n!})}/></div>
     <div className="connection-string-drawing" role="img" aria-label={`${a.parallel} parallel strings, ${a.series} panels per string`}>{Array.from({length:Math.min(a.parallel,3)},(_,p)=><div key={p}>{Array.from({length:Math.min(a.series,6)},(_,s)=><i key={s}/>)}{a.series>6&&<span>+{a.series-6}</span>}</div>)}{a.parallel>3&&<small>+{a.parallel-3} strings</small>}</div>
     <button className="button outline small connection-autosize" disabled={invalid} onClick={()=>{const result=suggestArray(build,products,a);if(result.layout)change(a.id,result.layout);setMessages(m=>({...m,[a.id]:result.message}));}}><Sparkles size={13}/>Auto-size remaining panels</button>
     {messages[a.id]&&<p className="connection-suggestion" role="status">{messages[a.id]}</p>}
     <dl className="connection-numbers"><div><dt>Array power</dt><dd>{fmt(values.watts,'W')}</dd></div><div><dt>Vmp / Imp at STC</dt><dd>{fmt(values.vmp,'V')} / {fmt(values.imp,'A')}</dd></div><div><dt>Voc / Isc at STC</dt><dd>{fmt(values.voc,'V')} / {fmt(values.isc,'A')}</dd></div></dl>
    </div>
    <ArrowRight className="connection-arrow" size={21} aria-hidden="true"/>
    <div className="connection-node"><PartTitle product={row.receiver} fallback="Choose a solar input"/><label className="connection-field">Solar receiver<select aria-label={'Solar receiver for array '+(index+1)} value={a.receiverId||''} onChange={e=>change(a.id,{receiverId:e.target.value||undefined,receiverUnit:1,tracker:1,batteryId:products.find(p=>p.id===e.target.value)?.category==='all-in-one'?undefined:a.batteryId})}><option value="">Choose inverter / controller / station</option>{a.receiverId&&!row.receiver&&<option value={a.receiverId}>Unavailable receiver</option>}{receivers.map(r=><option key={r.id} value={r.id}>{productListName(r)}</option>)}</select></label>
     <div className="connection-string-controls"><NumberField label="Receiver unit" value={a.receiverUnit} min={1} max={build.lines.find(l=>l.productId===a.receiverId)?.quantity||10000} onError={bad=>error(a.id+':unit',bad)} onChange={n=>change(a.id,{receiverUnit:n!})}/><NumberField label="MPPT input" value={a.tracker} min={1} max={limits.count||200} onError={bad=>error(a.id+':tracker',bad)} onChange={n=>change(a.id,{tracker:n!})}/></div>
     <dl className="connection-numbers"><div data-status={row.checks.find(c=>c.key==='coldVoc')?.status}><dt>Cold Voc / max</dt><dd>{fmt(values.coldVoc,'V')} / {fmt(limits.voc,'V')}</dd></div><div data-status={row.checks.find(c=>c.key==='vmp')?.status}><dt>Vmp / MPPT window</dt><dd>{fmt(values.vmp,'V')} / {limits.vmp?`${limits.vmp[0]}–${limits.vmp[1]} V`:'Not documented'}</dd></div><div data-status={row.checks.find(c=>c.key==='imp')?.status}><dt>Imp / input limit</dt><dd>{fmt(values.imp,'A')} / {fmt(limits.imp,'A')}</dd></div><div data-status={row.checks.find(c=>c.key==='isc')?.status}><dt>Isc / input limit</dt><dd>{fmt(values.isc,'A')} / {fmt(limits.isc,'A')}</dd></div></dl>
    </div>
    <ArrowRight className="connection-arrow" size={21} aria-hidden="true"/>
    <div className="connection-node"><PartTitle product={row.battery} fallback={row.receiver?.category==='all-in-one'?'Integrated battery':'Battery connection'}/>{row.receiver?.category!=='all-in-one'&&<label className="connection-field">Standalone battery<select aria-label={'Battery for array '+(index+1)} value={a.batteryId||''} onChange={e=>change(a.id,{batteryId:e.target.value||undefined})}><option value="">Choose battery / no storage</option>{a.batteryId&&!row.battery&&<option value={a.batteryId}>Unavailable battery</option>}{batteries.map(b=><option key={b.id} value={b.id}>{productListName(b)}</option>)}</select></label>}
     <div className="connection-battery-symbol"><Battery size={28}/><span>{row.battery?build.lines.find(l=>l.productId===row.battery!.id)?.quantity+' batteries selected':row.receiver?.category==='all-in-one'?'Internal storage':'Not assigned'}</span></div>
     {row.batteryChecks.map(c=><div className="connection-battery-check" key={c.key}><strong>{c.title}</strong><Status value={invalid?'unknown':c.status}/><p>{c.detail}</p></div>)}
    </div>
   </div>
   <details className="connection-details"><summary>Detailed calculations &amp; source limits</summary><CheckRows checks={row.checks} invalid={invalid}/><p className="connection-formula">Series multiplies voltage; parallel multiplies current. Cold Voc = panel Voc × series × [1 + Voc coefficient / 100 × (lowest temperature − 25°C)]. Hot/cold Vmp uses its own documented coefficient; Pmax coefficient is not substituted.</p></details>
  </article>;})}
  <div className="connection-actions"><button className="button dark small" disabled={!map.allocations.length||arrays.length>=100} onClick={add}><Plus size={14}/>{arrays.length?'Add another array':'Plan panel strings'}</button>{!map.allocations.length&&<span>Choose solar panels above to start.</span>}{!receivers.length&&map.allocations.length>0&&<span>Add an inverter, MPPT controller or power station to choose its inputs.</span>}</div>
  {receivers.length>0&&<details className="connection-input-inventory"><summary>Input usage · {receivers.length} receiver models</summary>{receivers.map(r=>{const count=receiverLimits(r).count,units=new Set([1,...arrays.filter(a=>a.receiverId===r.id).map(a=>a.receiverUnit)]);return <div key={r.id}><PartTitle product={r} fallback=""/>{Array.from(units).map(unit=><div className="connection-input-slots" key={unit}><strong>Unit {unit}</strong>{count?Array.from({length:count},(_,i)=>{const used=arrays.filter(a=>a.receiverId===r.id&&a.receiverUnit===unit&&a.tracker===i+1);return <span key={i} data-used={used.length>0}>MPPT {i+1} · {used.length>1?'Conflict':used.length?'Assigned':'Free'}</span>;}):<span>Tracker count not documented</span>}</div>)}</div>;})}</details>}
  {unassignedBatteries.length>0&&<p className="connection-warning">Not assigned to a receiver: {unassignedBatteries.map(p=>productListName(p)).join(', ')}. Their voltage connections remain unverified.</p>}
  <p className="connection-footnote">This is an equipment planning map. STC current checks do not include site-specific irradiance, bifacial gain, conductor or fuse sizing. Startup thresholds, optimizers, battery charge/discharge limits and manufacturer approval still need review. Missing or estimated ratings never count as verified. <Link href="/guide/calculators?tool=array">Open string calculator</Link></p>
 </section>;
}
