'use client';
import {useEffect,useState} from 'react';
import Link from './site-link';
import {BuildOpenAction} from './build-open-action';
import {ProductImage} from './pv-provider';
import {resolveExample,type ExampleBuild} from '../lib/example-builds';
import type {Product} from '../lib/types';
import {money} from '../lib/domain';
import {productListName} from '../lib/part-comparison';
type ExamplesResponse={examples:ExampleBuild[];products:Product[]};
export function BuildExamples(){
 const [data,setData]=useState<ExamplesResponse>(),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[filter,setFilter]=useState('All');
 useEffect(()=>{const controller=new AbortController();let active=true;const deadline=setTimeout(()=>controller.abort(),15000);setError('');fetch('/api/example-builds',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Could not load example builds.');return r.json() as Promise<ExamplesResponse>;}).then(v=>{if(active)setData(v);}).catch(e=>{if(active)setError(e.name==='AbortError'?'Loading timed out. Please try again.':e.message);}).finally(()=>clearTimeout(deadline));return()=>{active=false;clearTimeout(deadline);controller.abort();};},[attempt]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')setAttempt(n=>n+1);};const interval=setInterval(refresh,120000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',refresh);};},[]);
 return <section id="example-builds" className="example-builds"><span id="planning-examples"/><header><div><h2>Find a build to make your own.</h2><p>Real equipment, already selected. Explore the parts, then open a copy in the builder.</p></div><span className="example-editorial">PVPartPicker examples</span></header>
 <div className="example-filters" role="group" aria-label="Example build type">{['All','Portable','Off-grid','Hybrid / backup'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>
 {!data&&!error&&<p role="status">Loading selected parts and current offers…</p>}{error&&<p role="alert">{error} <button className="text-link" onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>}
 {data?.examples.filter(e=>filter==='All'||filter===e.useCase).map(e=>{const r=resolveExample(e,data.products);return <article className="example-build" key={e.id}>
 <div className="example-build-photos" aria-label={'Equipment in '+e.name}>{r.selections.map(s=><div key={s.line.productId}>{s.product?<Link href={'/products/'+s.product.id} aria-label={productListName(s.product)}><ProductImage product={s.product}/></Link>:<span>Part unavailable</span>}<small>{s.line.quantity} × {s.product?.category==='kits'?'bundle':s.product?.category==='panels'?'panel':s.product?.category==='batteries'?'battery':'inverter'}</small></div>)}</div>
 <div className="example-build-description"><small>{e.useCase}</small><h3>{e.name}</h3><p>{e.description}</p><ul className="example-highlights">{e.highlights.map(h=><li key={h}>{h}</li>)}</ul><p className="example-included">{e.included}</p></div>
 <div className="example-build-price"><span>{r.unpriced?'Priced equipment subtotal':'Equipment subtotal'}</span><strong>{r.unpriced===r.selections.length?'Price unavailable':money(r.total)}</strong><small>{r.unpriced?`${r.unpriced} selection(s) need a current offer. `:''}Shipping, tax and installation excluded.</small>{r.missing?<span role="status">A selected product is unavailable. Copy is disabled until restored.</span>:<BuildOpenAction target={r.build} label="Open a copy" copy navigate/>}</div>
 <details className="example-build-details"><summary>View parts & quantities · {r.selections.length} {r.selections.length===1?'selection':'selections'}</summary><div className="example-parts-list">{r.selections.map(s=><div key={s.line.productId}><span>{s.line.quantity} ×</span><div>{s.product?<Link href={'/products/'+s.product.id}>{productListName(s.product)}</Link>:<strong>Unavailable product</strong>}<small>{s.offer?`${s.offer.retailer} · ${s.cost!.packs} package(s) of ${s.offer.packQuantity}${s.cost!.extraUnits?' · '+s.cost!.extraUnits+' extra units':''} · checked ${s.offer.observedAt.slice(0,16).replace('T',' ')} UTC`:'No fresh in-stock offer'}</small></div><strong>{s.cost?money(s.cost.subtotal):'Unpriced'}</strong></div>)}</div><h4>Finish for your location</h4><p>{e.remaining}</p><p>Illustrative equipment selection, not a completed installation design. Nominal storage is not usable AC energy. The builder checks available specifications; missing data still needs verification.</p><div className="example-sources">{e.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label} ↗</a>)}</div></details>
 </article>;})}<p className="example-build-note">Examples are curated equipment lists, separate from community submissions. Subtotals use fresh in-stock offers and whole-package purchase costs. Site-specific installation parts are additional.</p></section>;
}
