import Link from './site-link';
import type {CalculatorId} from '../lib/guide-calculators';
const lessons:Record<CalculatorId,{title:string;paragraphs:string[];example:string;checks:string[];guide:string}>={
 pv:{title:'From nameplate power to yearly energy',paragraphs:[
 'Panel capacity is power in kW, measured at laboratory conditions. Production is energy in kWh accumulated over time. Peak sun hours mean an equivalent duration at 1,000 W/m², not the number of daylight hours. Enter a locally appropriate annual-average value for the instant model.',
 'Use separate roof faces when directions or tilt differ. A south-facing and east-facing array need independent estimates; averaging their directions can hide their behavior. Capacity comes from the sum of the face entries. Latitude controls the simplified seasonal pattern, while longitude locates the optional climate calculation.',
 'PVGIS uses historical weather and irradiance to estimate a typical year. Its default terrain horizon does not identify nearby trees, chimneys or buildings. This calculation uses crystalline-silicon technology and free-standing mounting; a close roof mount can have different temperatures and output. Snow, soiling and actual inverter behavior need a more specific study.',
 'Annual energy divided by annual usage is an energy comparison. Even 100% annual coverage can include daytime exports and nighttime imports. Gross energy value is generation multiplied by the rate you enter, so use an export/self-consumption study before treating it as bill savings.'
 ],example:'10 kW × 4 peak sun hours/day × 365 × 0.86 = 12,556 kWh/year before this model’s orientation and tilt factors. A 10 kW array does not produce 10 kWh every hour.',checks:['Use installed DC module capacity, not an AC inverter rating.','Verify roof direction and coordinates; north is 0°, east 90°, south 180°, west 270°.','Compare monthly production with seasonal loads, then model exports and storage separately.'],guide:'production-estimates'},
 battery:{title:'Understand the energy budget',paragraphs:[
 'Nominal battery capacity is not all available at the AC outlet. The tool first applies the usable depth of discharge, then an overall delivery efficiency. The resulting delivered kWh are divided by a constant running load in kW. The runtime chart shows how quickly a larger load spends the same energy budget.',
 'Use the measured average running load of the equipment you want to support. Refrigerators and pumps cycle; compressors can have a startup demand much higher than their average. Runtime does not verify inverter continuous power, surge duration, BMS current or battery communication.',
 'The model starts with a full battery. Aging, cold-temperature restrictions, inverter idle consumption and part-load efficiency can reduce real runtime. If your battery specifies usable rather than nominal capacity, avoid subtracting the same reserve twice.'
 ],example:'5.12 kWh × 90% usable discharge × 90% delivery efficiency = 4.147 kWh delivered. At 500 W, that is about 8.29 hours; at 1,000 W, about 4.15 hours.',checks:['Separate steady watts from startup watts.','Check battery discharge-current and inverter output limits.','Allow for starting state of charge and loads that run continuously.'],guide:'battery-backup'},
 voltage:{title:'Read the conductor chart and color table',paragraphs:[
 'For a two-wire DC circuit, current travels through both the outgoing and return conductors. Enter the distance from source to load once: the tool doubles it. Resistance is specified per 1,000 ft of one conductor at its operating temperature.',
 'The colored table answers two equivalent questions: how much voltage is lost at your current, or how much current fits within your chosen drop budget at a given length. The amps figure is calculated from resistance alone. It is not an allowable thermal ampacity, fuse recommendation or installation approval.',
 'The comparison uses Southwire Class B stranded conductor resistance at 25°C and adjusts it to the temperature you enter. Conductor temperature is not ambient air temperature. The dark curve uses the main tool’s separately entered resistance; the other curves use the comparison table settings.',
 'Longer runs and higher currents increase drop. A larger conductor reduces resistance. Connections, fuses and shunts add losses that this cable-only estimate omits. Constant-power loads can draw more current when voltage falls; use actual worst-case current rather than relying only on nominal battery voltage.'
 ],example:'At 48 V and 30 A, a 50 ft one-way run of 6 AWG uncoated Class B copper at 25°C gives 2 × 50 × 30 × 0.411 / 1,000 = 1.233 V, or 2.57%.',checks:['Choose a drop budget appropriate for the equipment; the example 3% is not a universal rule.','Verify corrected ampacity, insulation, terminal ratings and protection separately.','For three-phase or reactive AC circuits, use an appropriate AC calculation.'],guide:'dc-wiring-protection'},
 cable:{title:'A cable has more than one limit',paragraphs:[
 'The main calculator selects the smallest candidate in Solar4U’s illustrative catalog meeting both its example ampacity and your voltage-drop target. Its 125% continuous-current allowance is a planning assumption. The catalog ampacities are not a replacement for the code table and corrections applicable to your installation.',
 'Use the conductor explorer to compare length, size, copper/aluminum and temperature. This explorer has a separate, sourced resistance dataset; it deliberately does not treat the amps allowed by a drop budget as thermal ampacity. Its settings do not change the illustrative catalog used by the selection card.',
 'For the actual installation, check wiring method, ambient temperature, bundled conductors, insulation temperature rating, terminal rating, wet/UV requirements and equipment instructions. Aluminum needs listed compatible terminations. Fine-strand battery cable and building wire can have different resistance and termination requirements.'
 ],example:'A 30 A continuous-load planning case uses 37.5 A for the illustrative ampacity comparison. A cable that meets that example value may still fail the voltage-drop budget on a long run—or fail real installation corrections.',checks:['Treat the selected gauge as an example candidate, not a final wire schedule.','Use actual manufacturer resistance and corrected installation ampacity.','Review connectors, conduit fill, mechanical protection and overcurrent protection together.'],guide:'dc-wiring-protection'},
 fuse:{title:'Separate rating from fault protection',paragraphs:[
 'This planning example multiplies continuous running current by 125% and rounds upward to an example standard device size. The chart compares that device rating with the corrected conductor ampacity you entered. Zero load does not select a device.',
 'A fuse or breaker must also be suitable for the circuit voltage, AC/DC type and prospective fault current. A battery can deliver a very large short-circuit current; the interrupt rating must cover the actual source. An amperage label alone is insufficient.',
 'PV source circuits, battery circuits, motors and listed equipment may follow different sizing and protection rules. Verify manufacturer maximum protection limits, conductor corrections and the locally adopted rules. A larger fuse is not a remedy for an overloaded conductor.'
 ],example:'40 A continuous load × 1.25 = 50 A. In this example catalog, the next rating is 50 A; an entered corrected ampacity of 45 A fails the comparison.',checks:['Check the protective device’s DC voltage and interrupt ratings.','Place protection according to the circuit and manufacturer instructions.','Compare conductor and equipment maximum ratings before choosing a device.'],guide:'dc-wiring-protection'},
 array:{title:'Series adds voltage; parallel adds current',paragraphs:[
 'Use Voc, Vmp, Isc and Imp from the exact module datasheet at STC. Voc is open-circuit voltage; Vmp is operating voltage at maximum power. Isc is short-circuit current; Imp is operating current at maximum power. Modules in series add voltage; identical parallel strings add current.',
 'Cold cells raise open-circuit voltage. The graph applies your module’s Voc temperature coefficient to the whole string and conservatively retains STC Voc above 25°C. Compare the cold maximum against the controller or inverter absolute input ceiling with appropriate margin.',
 'Passing the cold-voltage test does not ensure that hot Vmp remains inside the MPPT range. Startup voltage, current per tracker, maximum string fuse ratings, connectors, mismatch and shading also matter. The charge-controller tool adds a hot-Vmp check for its limited model catalog.'
 ],example:'A 50 V Voc module, three in series, with −0.30%/°C Voc coefficient at −15°C gives 150 × [1 + 0.003 × 40] = 168 V. A 150 V absolute input ceiling is exceeded.',checks:['Use cell-temperature design assumptions rather than a convenient average.','Do not confuse total array current with current per MPPT.','Check hot Vmp, startup voltage and string protection after the cold-Voc test.'],guide:'mppt-envelope'},
 controller:{title:'Interpret the controller shortlist',paragraphs:[
 'Each model is checked against the complete array you entered. The tool does not automatically split strings across controllers. Parallel connector pairs on these listed models share an MPPT; additional connectors do not create independent trackers.',
 'The voltage chart compares cold Voc with each model’s absolute ceiling. Equality fails: cold Voc must remain below the ceiling. The result cards also evaluate PV short-circuit current, hot Vmp and the actual highest battery charging voltage plus the modeled startup margin.',
 'Array power above the model’s nominal PV power is flagged separately. Manufacturer-approved oversizing can involve clipping, but cannot excuse an excessive voltage or short-circuit current. A preliminary match is limited to the modeled checks and the small documented catalog.'
 ],example:'A nominal 48 V battery may charge at 56.8 V. The modeled 5 V startup margin therefore needs hot array Vmp above 61.8 V—not merely above the nominal 48 V class.',checks:['Confirm charging voltage and battery chemistry settings.','Review whole-string allocation, connectors and per-controller current.','Read the manufacturer oversizing instructions for the exact model.'],guide:'mppt-envelope'},
 tou:{title:'Rate shifting spends energy to save money',paragraphs:[
 'Enter daily consumption and the share used during peak and mid-peak periods. The rest is off-peak. Those shares must total 100% or less. The model shifts the peak and mid-peak energy into off-peak charging and compares the energy charge before and after.',
 'Round-trip efficiency determines how much grid energy is needed to recharge. Discharge efficiency and reserve determine nominal storage capacity. These are different boundaries: do not apply round-trip losses twice, and do not enter a round-trip efficiency greater than the discharge efficiency.',
 'The backup target starts with a full battery and covers your entered autonomy period. Everyday rate shifting can leave less reserve when an outage begins. The savings graph excludes capital cost, battery wear, demand charges, fixed charges, taxes and tariff restrictions; a negative saving means shifting raises the energy charge.'
 ],example:'Delivering 10 kWh with 90% round-trip efficiency requires 11.11 kWh of recharge. At $0.10/kWh off-peak, recharge costs $1.11; avoiding $0.30/kWh peak energy saves $3.00 before wear and other costs.',checks:['Use the actual tariff and permitted charging/export behavior.','Leave realistic outage reserve rather than assuming a full battery every evening.','Compare annual rate-shifting value with battery cost and cycle wear.'],guide:'battery-backup'},
 payback:{title:'Read a scenario, not a guarantee',paragraphs:[
 'The curve begins at the negative net installed cost and adds each year’s modeled net savings. It includes your annual maintenance, production degradation and electricity-rate escalation. The first year in which cumulative cash flow reaches zero is the modeled break-even year.',
 'Annual production multiplied by an electricity rate is only a gross-value assumption. If exports earn less than self-consumed energy, enter a realistic blended value or a separately modeled savings figure. Fixed utility charges often remain even when energy imports decline.',
 'This is an undiscounted scenario: future dollars are added without a discount rate. Financing, replacement batteries or inverters, taxes, tariff changes and structural work are excluded. Incentives default to zero; enter only an incentive confirmed for your location, project and timing.'
 ],example:'A $20,000 net cost and $1,500 first-year net savings suggest about 13.3 years by a simple ratio, but degradation, escalation and maintenance change the cumulative crossing year. Use the year-by-year table to inspect those assumptions.',checks:['Use actual quotes and confirmed incentive eligibility.','Check self-consumption and export compensation before valuing every kWh.','Recalculate with conservative production, future replacement costs and lower rate growth.'],guide:'solar-economics'}
};
export default function CalculatorHelp({id}:{id:CalculatorId}){const h=lessons[id];return <section className="calc-help"><span className="eyebrow">HOW TO USE THIS RESULT</span><h3>{h.title}</h3>{h.paragraphs.map(p=><p key={p}>{p}</p>)}<aside><strong>Worked example</strong><p>{h.example}</p></aside><h4>Before using the result in a build</h4><ul>{h.checks.map(c=><li key={c}>{c}</li>)}</ul><Link href={'/guide/'+h.guide}>Continue with the detailed guide →</Link></section>;}
