'use client';
import {useEffect,useState} from 'react';
import {Users,RefreshCw} from 'lucide-react';
import Link from './site-link';
import {api,usePV,ProductImage} from './pv-provider';
import {BuildOpenAction} from './build-open-action';
import {purposeLabel} from '../lib/build-library';
import type {CommunityBuild} from '../lib/community-builds';
import {bestOffer,costForQuantity,money} from '../lib/domain';

export function CommunityWorkspace({embedded=false}:{embedded?:boolean}){
 const Container=embedded?'section':'main';
 const {products}=usePV();const [builds,setBuilds]=useState<CommunityBuild[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[purpose,setPurpose]=useState(''),[mount,setMount]=useState('');
 async function reload(){setLoading(true);setError('');try{setBuilds((await api('community')).builds);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{reload();},[]);
 const visible=builds.filter(b=>(!purpose||b.build.settings.purpose===purpose)&&(!mount||b.build.settings.mount===mount)&&(!query||(b.build.name+' '+b.description+' '+b.build.lines.map(l=>products.find(p=>p.id===l.productId)?.name||'').join(' ')).toLowerCase().includes(query.trim().toLowerCase())));
 return <Container className={embedded?'community-page community-embedded':'page-container community-page'}><header className="page-intro"><div><div className="eyebrow">BUILD TOGETHER</div>{embedded?<h2>Community builds</h2>:<h1>Community builds</h1>}<p>Explore a shared setup. Open a copy and make it your own.</p></div>{!embedded&&<Link className="button dark small" href="/build">My system builder</Link>}</header><div className="community-toolbar"><label className="field">Search builds<input type="search" placeholder="Build name, part, or note" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field">System purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="">All purposes</option>{Object.entries(purposeLabel).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="field">Panel mounting<select value={mount} onChange={e=>setMount(e.target.value)}><option value="">All mounts</option><option value="roof">Roof</option><option value="ground">Ground</option></select></label><button className="button outline small" disabled={loading} onClick={reload}><RefreshCw size={14}/>Refresh</button></div><p className="community-note">These are equipment lists shared by builders. Check product fit and installation requirements for your site.</p>
  {error&&<div className="error-message" role="alert">{error} <button className="text-link" onClick={reload}>Try again</button></div>}{loading&&<p role="status">Loading community builds…</p>}
  <div className="community-build-list">{visible.map(entry=>{const b=entry.build;let total=0,missing=0;const chosen=b.lines.map(l=>{const product=products.find(p=>p.id===l.productId),offer=product?bestOffer(l.offerId?{...product,offers:product.offers.filter(o=>o.id===l.offerId)}:product,l.quantity):undefined;if(offer)total+=costForQuantity(offer,l.quantity).subtotal;else missing++;return {line:l,product};});return <article className="community-build-item" key={entry.shareId}><div className="community-build-main"><div className="build-labels"><span>{purposeLabel[b.settings.purpose]}</span><span>{b.settings.mount==='roof'?'Roof':'Ground'} mounting</span></div><Link href={'/community/'+entry.shareId}><h2>{b.name}</h2></Link>{entry.description&&<p className="community-description">{entry.description}</p>}<div className="community-build-parts">{chosen.slice(0,3).map(({line,product})=><div key={line.productId}>{product&&<ProductImage product={product}/>}<span><strong>{line.quantity}×</strong> {product?.name||'Unavailable product'}</span></div>)}{chosen.length>3&&<small>+ {chosen.length-3} more parts</small>}</div><small>Published {new Date(entry.publishedAt).toLocaleDateString()} · {b.lines.length} part selections</small></div><div className="community-build-side"><span>{missing?'Priced items subtotal':'Equipment subtotal'}</span><strong>{money(total)}</strong><small>{missing?`${missing} items need current offers`:'Current eligible offers'}<br/>Shipping and tax excluded</small><BuildOpenAction target={b} label="Open a copy" copy navigate/><Link className="text-link" href={'/community/'+entry.shareId}>View parts & quantities</Link></div></article>;})}</div>
  {!loading&&!error&&!visible.length&&<div className="community-empty"><Users size={30}/><h2>{builds.length?'No builds match these filters.':'Make room for the first community build.'}</h2><p>{builds.length?'Try another name, purpose, or mounting type.':'Have a setup to share? In the builder, choose Share, then Publish to community. Your saved builds stay private until you publish one.'}</p>{builds.length?<button className="button outline" onClick={()=>{setQuery('');setPurpose('');setMount('');}}>Clear filters</button>:<div className="flex-actions"><Link className="button dark" href="/build">Open current build</Link><Link className="button outline" href="/builds#example-builds">Explore populated example builds</Link></div>}</div>}
 </Container>;
}
