'use client';
import {useState} from 'react';
import CalculatorChart,{type ChartSeries} from './calculator-chart';
import {conductorComparison,conductorSource,type ConductorMaterial} from '../lib/calculator-exploration';
const palette=['#087e8b','#e48624','#7554b3','#d55275','#45832b','#327ad0'];
export default function ConductorExplorer({voltage,currentA,lengthFt,targetPercent=3,material='copper',enteredResistance}:{voltage:number;currentA:number;lengthFt:number;targetPercent?:number;material?:ConductorMaterial;enteredResistance?:number}){
 const [metal,setMetal]=useState<ConductorMaterial>(material),[temperature,setTemperature]=useState('75'),[target,setTarget]=useState(String(targetPercent)),[mode,setMode]=useState<'amps'|'drop'>('amps'),[selected,setSelected]=useState(['6 AWG','4 AWG','2 AWG','1/0 AWG']);
 const temp=Number(temperature),percent=Number(target),valid=temperature.trim()!==''&&target.trim()!==''&&Number.isFinite(temp)&&temp>=0&&temp<=100&&Number.isFinite(percent)&&percent>=0.25&&percent<=10;
 const lengths=[...new Set([5,10,25,50,75,100,150,200,...(lengthFt>0?[lengthFt]:[])])].sort((a,b)=>a-b);
 const rows=valid?conductorComparison({voltage,currentA,targetPercent:percent,temperatureC:temp,material:metal,lengths}):[];
 const chartLengths=Array.from({length:9},(_,i)=>Math.max(100,lengthFt*1.25)*i/8);
 const series:ChartSeries[]=rows.filter(r=>selected.includes(r.gauge)).map((r,i)=>({name:r.gauge,color:palette[i%palette.length],values:chartLengths.map(l=>2*l*currentA*r.resistance/1000/voltage*100)}));
 if(enteredResistance!==undefined)series.push({name:'Entered resistance',color:'#202b38',values:chartLengths.map(l=>2*l*currentA*enteredResistance/1000/voltage*100)});
 return <section className="conductor-explorer"><div className="calc-section-heading"><div><span className="eyebrow">CONDUCTOR COMPARISON</span><h3>Distance changes the equation</h3></div><span>{voltage.toLocaleString()} V · {currentA.toLocaleString()} A</span></div><p>Compare conductor sizes at your running current. Lengths are <strong>one way</strong>; the calculation includes both outgoing and return conductors.</p>
 <div className="calc-comparison-controls"><label>Material<select value={metal} onChange={e=>setMetal(e.target.value as ConductorMaterial)}><option value="copper">Copper · uncoated</option><option value="aluminum">Aluminum</option></select></label><label>Conductor temperature · °C<input type="number" min="0" max="100" value={temperature} onChange={e=>setTemperature(e.target.value)}/></label><label>Drop budget · %<input type="number" min="0.25" max="10" step="0.25" value={target} onChange={e=>setTarget(e.target.value)}/></label></div>
 {!valid?<p className="guide-input-error" role="alert">Enter 0–100°C and a drop budget of 0.25–10%.</p>:<><fieldset className="calc-series-picker"><legend>Show conductor curves</legend>{rows.map(r=><label key={r.gauge}><input type="checkbox" checked={selected.includes(r.gauge)} onChange={()=>setSelected(selected.includes(r.gauge)?selected.filter(g=>g!==r.gauge):[...selected,r.gauge])}/>{r.gauge}</label>)}</fieldset>
 <CalculatorChart title="Voltage drop versus conductor length" xTitle="One-way length · ft" unit="Voltage drop · %" labels={chartLengths.map(l=>String(Math.round(l*10)/10))} series={[...series,{name:`${percent}% drop budget`,color:'#bd6522',values:chartLengths.map(()=>percent),dashed:true}]}/>
 <div className="calc-table-heading"><h4>{mode==='amps'?'Current available within the drop budget':'Voltage drop at your entered current'}</h4><div className="calc-segmented" aria-label="Conductor table units"><button aria-pressed={mode==='amps'} onClick={()=>setMode('amps')}>Amps</button><button aria-pressed={mode==='drop'} onClick={()=>setMode('drop')}>Drop %</button></div></div>
 <p className="calc-table-warning"><strong>Voltage-drop limits only — not thermal ampacity.</strong> A large amp value here never authorizes that current. The lower installation ampacity, equipment and protection limits still apply.</p>
 <div className="guide-table-wrap calc-heatmap" tabIndex={0} role="region" aria-label="Conductor size and length comparison"><table><caption>{metal==='copper'?'Copper':'Aluminum'} · {temp}°C · {voltage} V · {percent}% budget. ✓ within voltage-drop budget at {currentA} A; ↑ exceeds it.</caption><thead><tr><th scope="col">Conductor</th>{lengths.map(l=><th key={l} scope="col">{l} ft</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.gauge}><th scope="row">{r.gauge}<small>{r.resistance.toFixed(4)} Ω/kft</small></th>{r.cells.map(c=><td key={c.lengthFt} className={c.withinTarget?(c.dropPercent<=percent*.5?'drop-low':'drop-within'):(c.dropPercent<=percent*1.5?'drop-near':'drop-over')} title={`${c.dropPercent.toFixed(2)}% drop at ${currentA} A; ${c.maxCurrentA.toFixed(1)} A voltage-drop budget`}><strong>{mode==='amps'?c.maxCurrentA.toLocaleString('en-US',{maximumFractionDigits:1}):c.dropPercent.toFixed(2)}{mode==='amps'?' A':'%'}</strong><span>{c.withinTarget?'✓':'↑'} {mode==='amps'?c.dropPercent.toFixed(2)+'% at load':c.maxCurrentA.toFixed(1)+' A budget'}</span></td>)}</tr>)}</tbody></table></div><div className="calc-heatmap-legend"><span className="drop-low">≤ half budget</span><span className="drop-within">✓ within budget</span><span className="drop-near">↑ up to 1.5× budget</span><span className="drop-over">↑ over 1.5× budget</span></div>
 <p className="calc-footnote">Resistance: <a href={conductorSource} target="_blank" rel="noopener noreferrer">Southwire Table 2-6 ↗</a>, Class B stranded at 25°C, adjusted using its temperature coefficients. Connections, fuses, shunts and AC reactance are excluded. This comparison uses the settings above; it does not change the main calculator’s entered resistance or illustrative ampacity table.</p></>}
 </section>;
}
