'use client';
import {useState} from 'react';
import Link from './site-link';
import {productListName} from '../lib/part-comparison';
import {TrendingDown,Search,ArrowUpRight,RefreshCw,Eye,Plus} from 'lucide-react';
import {usePV,WatchButton} from './pv-provider';
import {usePriceDrops} from './use-price-drops';
import {money} from '../lib/domain';
import {categories} from '../lib/types';
import {selectDrops} from '../lib/price-drops';
import type {DropPeriod,DropSort} from '../lib/price-drops';
const periods:{id:DropPeriod;label:string}[]=[{id:'day',label:'Daily'},{id:'week',label:'Weekly'},{id:'month',label:'Monthly'},{id:'latest',label:'Latest'}];
export function DealsWorkspace(){
 const{products,watchIds,add}=usePV();const[period,setPeriod]=useState<DropPeriod>('day'),[sort,setSort]=useState<DropSort>('dollars'),[minDollars,setMinDollars]=useState(''),[minPercent,setMinPercent]=useState(''),[category,setCategory]=useState(''),[q,setQ]=useState(''),[watchedOnly,setWatchedOnly]=useState(false),[limit,setLimit]=useState(36);
 const {drops,loading,error,checkedAt,retry}=usePriceDrops(period),productMap=new Map(products.map(p=>[p.id,p]));
 const visible=selectDrops(drops,{sort,minDollars:Number(minDollars)||0,minPercent:Number(minPercent)||0}).filter(d=>{const p=productMap.get(d.productId);return p&&(!category||p.category===category)&&(!watchedOnly||watchIds.includes(p.id))&&(!q||(p.name+' '+p.brand+' '+d.retailer).toLowerCase().includes(q.toLowerCase()));});
 const choose=(id:DropPeriod)=>{setPeriod(id);setLimit(36);if(id==='latest')setSort('latest');};
 return <main className="page-container savings-page"><div className="page-intro"><div><div className="eyebrow"><TrendingDown size={14}/> THE PRICE-DROP RADAR</div><h1>Catch the next power deal.</h1><p>Recorded retailer price drops, ranked by the savings that matter to you.</p></div><Link className="button outline small" href="/watchlist"><Eye size={15}/>My watch list <span className="tiny-count">{watchIds.length}</span></Link></div>
  <div className="savings-periods" role="group" aria-label="Price drop period">{periods.map(p=><button aria-pressed={period===p.id} key={p.id} onClick={()=>choose(p.id)}>{p.label}</button>)}</div>
  <p className="savings-period-note">{period==='latest'?'Most recent price reductions still available, recorded in the last 30 days.':`Current price versus the highest comparable recorded price in the last ${period==='day'?'24 hours':period==='week'?'7 days':'30 days'}.`}</p>
  <div className="savings-filters"><label className="savings-search"><Search size={17}/><span className="sr-only">Search price drops</span><input placeholder="Find a model, brand or retailer…" value={q} onChange={e=>{setQ(e.target.value);setLimit(36);}}/></label><label className="field">Category<select value={category} onChange={e=>{setCategory(e.target.value);setLimit(36);}}><option value="">All parts</option>{categories.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label className="field">Sort drops<select value={sort} onChange={e=>setSort(e.target.value as DropSort)}><option value="dollars">Biggest dollar drop</option><option value="percent">Biggest percentage drop</option><option value="latest">Latest price change</option></select></label><label className="field">Minimum saved ($ / unit)<input type="number" min="0" step="0.01" value={minDollars} placeholder="Any amount" onChange={e=>setMinDollars(e.target.value)}/></label><label className="field">Minimum saved (%)<input type="number" min="0" max="100" step="0.1" value={minPercent} placeholder="Any percentage" onChange={e=>setMinPercent(e.target.value)}/></label></div>
  <div className="savings-toolbar"><span>{loading?'Checking price history…':`${visible.length} recorded ${visible.length===1?'drop':'drops'}`}</span><label className="check-field"><input type="checkbox" checked={watchedOnly} onChange={e=>setWatchedOnly(e.target.checked)}/>Watched products only</label><button className="text-link small-text" onClick={()=>{setQ('');setCategory('');setMinDollars('');setMinPercent('');setWatchedOnly(false);setLimit(36);}}>Reset filters</button></div>
  {error?<div className="notice-panel" role="alert"><p>{error}</p><button className="button outline small" onClick={retry}>Retry history</button></div>:loading?<p className="inline-note" role="status">Reading recorded prices…</p>:visible.length?<div className="savings-list" aria-label="Recorded price drops">{visible.slice(0,limit).map(d=>{const p=productMap.get(d.productId)!;return <article className="savings-row" key={d.offerId}><div className="savings-score"><TrendingDown size={17}/><strong>{money(d.dollars)}</strong><span>{d.percent.toFixed(1)}% saved / unit</span></div><div className="savings-product"><Link href={'/products/'+p.id}>{productListName(p)}</Link><span>{d.retailer} · {d.packQuantity>1?`${d.packQuantity}-unit package`:'Single unit'} · {p.offers.find(o=>o.id===d.offerId)?.condition==='used'?'Used / refurbished':'New'}</span><small>Checked <time dateTime={d.observedAt}>{d.observedAt.slice(0,16).replace('T',' ')} UTC</time> · {d.observations} observations · history in this window starts {d.firstObservedAt.slice(0,10)} · latest change {d.changedAt.slice(0,16).replace('T',' ')} UTC</small></div><div className="savings-price"><del>{money(d.previous)}</del><strong>{money(d.current)}</strong><small>per unit</small>{d.packQuantity>1&&<small>{money(d.purchasePrice)} purchase</small>}</div><div className="savings-actions"><WatchButton product={p}/><button className="icon-button" onClick={()=>add(p.id,d.offerId)} aria-label={'Add '+p.name+' to build'}><Plus size={17}/></button><Link className="icon-button" href={'/products/'+p.id} aria-label={'Price history for '+p.name}><ArrowUpRight size={17}/></Link></div></article>;})}</div>:<div className="empty-state"><TrendingDown size={32}/><h3>{drops.length?'No drops match these filters.':'No confirmed drops in this window yet.'}</h3><p>{drops.length?'Try a lower savings threshold or another category.':'Drops appear after a retailer lowers a recorded price. Keep products on your watch list while history grows.'}</p><Link className="button dark" href="/">Browse parts</Link></div>}
  {!loading&&!error&&visible.length>limit&&<button className="button outline load-more" onClick={()=>setLimit(n=>n+36)}>Show more drops ({visible.length-limit} more)</button>}
  <details className="savings-method"><summary>How price drops are measured</summary><p>Daily, weekly and monthly are rolling windows, not calendar periods. We compare the current in-stock USD price with that offer’s highest recorded price in the window. Latest compares with its most recent different price; unchanged checks keep the drop visible until another price change or expiry.</p><p>Prices are compared within the same retailer offer and package size. Dollar savings are per unit; a pallet or multi-pack still requires buying the whole package. Shipping and tax are excluded. Short tracking history is shown on each result; missing history is never invented. Current offers must have been checked in the last 24 hours.</p></details>
  <div className="savings-updated"><span>{checkedAt?'History checked '+checkedAt.slice(0,16).replace('T',' ')+' UTC':''}</span><button className="text-link small-text" onClick={()=>window.location.reload()}><RefreshCw size={13}/>Refresh prices</button></div>
 </main>;
}
