'use client';
import {useState} from 'react';
import Link from './site-link';
import {productListName,productListVariant} from '../lib/part-comparison';
import {Tag,TrendingDown,Search,ArrowUpRight,RefreshCw,Eye,Plus} from 'lucide-react';
import {usePV,WatchButton,ProductImage} from './pv-provider';
import {usePriceDrops} from './use-price-drops';
import {useSales} from './use-sales';
import {currentSales} from '../lib/sales';
import type {SaleOffer} from '../lib/sales';
import {money} from '../lib/domain';
import {categories} from '../lib/types';
import {selectDrops} from '../lib/price-drops';
import type {DropPeriod,DropSort,PriceDrop} from '../lib/price-drops';
const periods:{id:DropPeriod;label:string}[]=[{id:'day',label:'Daily'},{id:'week',label:'Weekly'},{id:'month',label:'Monthly'},{id:'latest',label:'Latest'}];
export function DealsWorkspace({initialView='sales',initialPeriod='day'}:{initialView?:'sales'|'drops';initialPeriod?:DropPeriod}){
 const{products,watchIds,add}=usePV();const[view,setView]=useState<'sales'|'drops'>(initialView);const[period,setPeriod]=useState<DropPeriod>(initialPeriod),[sort,setSort]=useState<DropSort>(initialPeriod==='latest'?'latest':'percent'),[budget,setBudget]=useState(''),[minDollars,setMinDollars]=useState(''),[minPercent,setMinPercent]=useState(''),[category,setCategory]=useState(''),[q,setQ]=useState(''),[watchedOnly,setWatchedOnly]=useState(false),[limit,setLimit]=useState(36);
 const dropsResult=usePriceDrops(period,view==='drops'),salesResult=useSales(view==='sales');
 const {loading,error,checkedAt,retry}=view==='sales'?salesResult:dropsResult;
 const items:(PriceDrop|SaleOffer)[]=view==='sales'?currentSales(salesResult.sales,products):dropsResult.drops;
 const productMap=new Map(products.map(p=>[p.id,p]));
 const visible=selectDrops(items,{sort,minDollars:Number(minDollars)||0,minPercent:Number(minPercent)||0}).filter(d=>{const p=productMap.get(d.productId);return p&&(!budget||d.purchasePrice<=Number(budget))&&(!category||p.category===category)&&(!watchedOnly||watchIds.includes(p.id))&&(!q||(p.name+' '+p.brand+' '+d.retailer).toLowerCase().includes(q.toLowerCase()));});
 const choose=(id:DropPeriod)=>{setPeriod(id);setLimit(36);if(id==='latest')setSort('latest');};
 return <main className="page-container savings-page"><div className="page-intro"><div><div className="eyebrow"><TrendingDown size={14}/> SALES & PRICE DROPS</div><h1>Deals</h1><p>Find parts below their usual price, or follow recorded price reductions.</p></div><Link className="button outline small" href="/watchlist"><Eye size={15}/>My watch list </Link></div>
  <div className="savings-periods section-pill-nav" role="group" aria-label="Deal view"><button aria-pressed={view==='sales'} onClick={()=>{setView('sales');setLimit(36);}}><span className="section-pill-icon"><Tag size={23} aria-hidden="true"/></span>Retailer sales</button><button aria-pressed={view==='drops'} onClick={()=>{setView('drops');setLimit(36);}}><span className="section-pill-icon"><TrendingDown size={23} aria-hidden="true"/></span>Recorded drops</button></div>
  {view==='drops'&&<div className="savings-periods" role="group" aria-label="Price drop period">{periods.map(p=><button aria-pressed={period===p.id} key={p.id} onClick={()=>choose(p.id)}>{p.label}</button>)}</div>}
  <p className="savings-period-note">{view==='sales'?'Current in-stock offers below a tracked usual price or a retailer’s published regular price. Each result shows its comparison source.':period==='latest'?'Most recent price reductions still available, recorded in the last 30 days.':`Current price versus the highest comparable recorded price in the last ${period==='day'?'24 hours':period==='week'?'7 days':'30 days'}.`}</p>
  <div className="savings-filters"><label className="savings-search"><Search size={17}/><span className="sr-only">Search sales and price drops</span><input placeholder="Find a model, brand or retailer…" value={q} onChange={e=>{setQ(e.target.value);setLimit(36);}}/></label><label className="field">Category<select value={category} onChange={e=>{setCategory(e.target.value);setLimit(36);}}><option value="">All parts</option>{categories.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label className="field">Sort savings<select value={sort} onChange={e=>setSort(e.target.value as DropSort)}><option value="dollars">Biggest dollar saving</option><option value="percent">Biggest percentage saving</option><option value="latest">{view==='sales'?'Recently checked':'Latest price change'}</option></select></label><label className="field">Maximum purchase ($)<input type="number" min="0" step="1" value={budget} placeholder="Any budget" onChange={e=>setBudget(e.target.value)}/></label><label className="field">Minimum saved ($ / unit)<input type="number" min="0" step="0.01" value={minDollars} placeholder="Any amount" onChange={e=>setMinDollars(e.target.value)}/></label><label className="field">Minimum saved (%)<input type="number" min="0" max="100" step="0.1" value={minPercent} placeholder="Any percentage" onChange={e=>setMinPercent(e.target.value)}/></label></div>
  <div className="deal-category-shortcuts" role="group" aria-label="Deal categories">{[{id:'',label:'All parts'},...categories.filter(c=>['panels','batteries','all-in-one','inverters'].includes(c.id))].map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>{setCategory(c.id);setLimit(36);}}>{c.label}</button>)}</div>
  <div className="savings-toolbar"><span>{loading?'Checking price history…':`${visible.length} ${view==='sales'?'sale offers':'recorded drops'}`}</span><label className="check-field"><input type="checkbox" checked={watchedOnly} onChange={e=>setWatchedOnly(e.target.checked)}/>Watched products only</label><button className="text-link small-text" onClick={()=>{setQ('');setCategory('');setMinDollars('');setMinPercent('');setBudget('');setWatchedOnly(false);setLimit(36);}}>Reset filters</button></div>
  {error?<div className="notice-panel" role="alert"><p>{error}</p><button className="button outline small" onClick={retry}>Retry prices</button></div>:loading?<p className="inline-note" role="status">Reading recorded prices…</p>:visible.length?<div className="savings-list" aria-label={view==='sales'?'Current sale offers':'Recorded price drops'}>{visible.slice(0,limit).map(d=>{const p=productMap.get(d.productId)!;return <article className="savings-row" key={d.offerId}><div className="savings-score"><TrendingDown size={17}/><strong>{money(d.dollars)}</strong><span>{d.percent.toFixed(1)}% saved / unit</span></div><div className="savings-product"><Link className="deal-photo" aria-label={productListName(p)} href={'/products/'+p.id}><ProductImage product={p}/></Link><Link href={'/products/'+p.id}>{productListName(p)}</Link><span>{productListVariant(p)}</span><span>{d.retailer} · {p.modelIdentity?.kind==='bundle'?'Bundle':d.packQuantity>1?`${d.packQuantity}-unit package`:'Single unit'} · {p.offers.find(o=>o.id===d.offerId)?.condition==='used'?'Used / refurbished':'New'}</span><small>Checked <time dateTime={d.observedAt}>{d.observedAt.slice(0,16).replace('T',' ')} UTC</time> · {'basis' in d?(d.basis==='history'?`Tracked usual price | ${d.sampleDays} daily checks in the previous 30 days`:'Retailer regular price | advertised reference'):`${d.observations} observations | history starts ${d.firstObservedAt.slice(0,10)} | latest change ${d.changedAt.slice(0,16).replace('T',' ')} UTC`}</small></div><div className="savings-price"><del>{money(d.previous)}</del><strong>{money(d.current)}</strong><small>{p.modelIdentity?.kind==='bundle'?'per bundle':'per unit'}</small>{d.packQuantity>1&&<small>{money(d.purchasePrice)} purchase</small>}</div><div className="savings-actions"><WatchButton product={p}/><button className="icon-button" onClick={()=>add(p.id,d.offerId)} aria-label={'Add '+p.name+' to build'}><Plus size={17}/></button><Link className="icon-button" href={'/products/'+p.id} aria-label={'Price history for '+p.name}><ArrowUpRight size={17}/></Link></div></article>;})}</div>:<div className="empty-state"><TrendingDown size={32}/><h3>{items.length?'No savings match these filters.':view==='sales'?'No verified sale comparisons available.':'No confirmed drops in this window yet.'}</h3><p>{items.length?'Try a lower savings threshold or another category.':view==='sales'?'Sales need a fresh, available offer and a published regular price or enough recent tracking history.':'Drops appear after a retailer lowers a recorded price. Keep products on your watch list while history grows.'}</p><div className="flex-actions">{view==='drops'&&<button className="button dark" onClick={()=>{setView('sales');setLimit(36);}}>See current retailer sales</button>}{view==='drops'&&period!=='latest'&&<button className="button outline" onClick={()=>choose('latest')}>Check latest drops</button>}<Link className="button outline" href="/parts">Browse parts</Link></div></div>}
  {!loading&&!error&&visible.length>limit&&<button className="button outline load-more" onClick={()=>setLimit(n=>n+36)}>Show more offers ({visible.length-limit} more)</button>}
  <details className="savings-method"><summary>How savings are measured</summary>{view==='sales'?<><p>Tracked usual price is the median of the latest in-stock check on each of at least 7 distinct days in the previous 30 completed UTC days. Each day has equal weight. Current-day checks, imported archives, and different package sizes are excluded.</p><p>If tracking history is insufficient, we use the retailer’s published regular or compare-at price. That advertised reference is not proof of the price previously paid or a historical low. A usable tracked usual price takes precedence over an advertised reference, even when it means the product is not on sale.</p></>:<p>Daily, weekly and monthly are rolling windows, not calendar periods. We compare the current in-stock USD price with that offer’s highest recorded price in the window. Latest compares with its most recent different price; unchanged checks keep the drop visible until another price change or expiry.</p>}<p>Prices are compared within the same retailer offer and package size. Dollar savings are per unit; a pallet or multi-pack still requires buying the whole package. Shipping and tax are excluded. Short tracking history is shown on each result; missing history is never invented. Current offers must have been checked in the last 24 hours.</p></details>
  <div className="savings-updated"><span>{checkedAt?'Prices checked '+checkedAt.slice(0,16).replace('T',' ')+' UTC':''}</span><button className="text-link small-text" onClick={retry}><RefreshCw size={13}/>Refresh prices</button></div>
 </main>;
}
