'use client';
import {useState} from 'react';
import Link from './site-link';
import {calculatorDefinitions,calculate,type CalculatorId,type Values,type Report} from '../lib/guide-calculators';
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const draftFor=(id:CalculatorId)=>Object.fromEntries(Object.entries(calculatorDefinitions.find(d=>d.id===id)!.defaults).map(([k,v])=>[k,String(v)]));
export default function CalculatorWorkshop({initialTool}:{initialTool?:string}){
 const first=calculatorDefinitions.find(d=>d.id===initialTool)?.id??'pv';
 const [id,setId]=useState<CalculatorId>(first),[draft,setDraft]=useState<Record<string,string>>(()=>draftFor(first)),[material,setMaterial]=useState<'copper'|'aluminum'>('copper'),[result,setResult]=useState<Report|null>(null),[applied,setApplied]=useState<Values|null>(null),[error,setError]=useState('');
 const d=calculatorDefinitions.find(d=>d.id===id)!;
 function select(next:CalculatorId){setId(next);setDraft(draftFor(next));setResult(null);setApplied(null);setError('');setMaterial('copper');window.history.replaceState(null,'','/guide/calculators?tool='+next);}
 function run(){setResult(null);setApplied(null);try{const v:Values={};for(const f of d.fields){if(!draft[f.key]?.trim())throw new Error(`Enter ${f.label}.`);v[f.key]=Number(draft[f.key]);}const r=calculate(id,v,material);setApplied(v);setResult(r);setError('');}catch(e){setError(e instanceof Error?e.message:'Check your inputs.');}}
 function exportResult(){if(!result||!applied)return;const url=URL.createObjectURL(new Blob([JSON.stringify({calculator:id,methodChecked:'2026-10-04',inputs:applied,...(id==='cable'?{material}:{}),result,source:d.source},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`pvpartpicker-${id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main className="page-container guide-workshop"><nav className="guide-breadcrumb" aria-label="Breadcrumb"><Link href="/guide">Guide</Link><span>/</span><span>Calculators</span></nav><div className="eyebrow">FROM QUESTION TO NUMBERS</div><h1>Calculator workshop</h1><p className="guide-lead">Nine tools adapted from Solar4U. Replace the example inputs with your own and inspect the assumptions.</p><div className="guide-workshop-layout"><nav className="guide-tool-nav" aria-label="Choose a calculator">{calculatorDefinitions.map((c,i)=><button key={c.id} aria-pressed={id===c.id} onClick={()=>select(c.id)}><span>{String(i+1).padStart(2,'0')}</span>{c.name}</button>)}</nav><div className="guide-tool-main"><header><h2>{d.name}</h2><p>{d.description}</p></header><form onSubmit={e=>{e.preventDefault();run();}} noValidate><div className="guide-input-grid">{d.fields.map(f=><label key={f.key} htmlFor={'calc-'+f.key}><span>{f.label}{f.unit&&<small>{f.unit}</small>}</span>{f.choices?<select id={'calc-'+f.key} value={draft[f.key]??''} onChange={e=>{setDraft({...draft,[f.key]:e.target.value});setResult(null);setError('');}}>{f.choices.map(c=><option key={c} value={c}>{c}</option>)}</select>:<input id={'calc-'+f.key} inputMode="decimal" type="number" step={f.step??'any'} min={f.min} max={f.max} value={draft[f.key]??''} onChange={e=>{setDraft({...draft,[f.key]:e.target.value});setResult(null);setError('');}}/>}<small>Range {f.min}–{f.max}{f.step===1?' · whole numbers':''}</small></label>)}{id==='cable'&&<label htmlFor="calc-material"><span>Conductor material</span><select id="calc-material" value={material} onChange={e=>{setMaterial(e.target.value as 'copper'|'aluminum');setResult(null);setError('');}}><option value="copper">Copper</option><option value="aluminum">Aluminum</option></select></label>}</div><div className="guide-calculator-actions"><button className="button dark" type="submit">Calculate</button><button type="button" className="button outline" onClick={()=>{setDraft(draftFor(id));setMaterial('copper');setResult(null);setApplied(null);setError('');}}>Reset example</button><span>Example values are starting points, not recommendations.</span></div>{error&&<p className="guide-input-error" role="alert">{error}</p>}</form>
 {result&&<section className="guide-results" aria-live="polite"><div className="guide-results-heading"><h3>Your estimate</h3><button className="text-link" onClick={exportResult}>Download result ↓</button></div><div className="guide-result-stats">{result.stats.map(s=><div key={s.label}><span>{s.label}</span><strong>{s.value} <small>{s.unit}</small></strong></div>)}</div><p className="guide-result-notice">{result.notice}</p>
 {result.monthly&&<><h4>Modeled seasonal allocation</h4><div className="guide-month-chart" aria-hidden="true">{result.monthly.map((v,i)=><div key={i}><span title={`${months[i]}: ${Math.round(v)} kWh`} style={{height:`${Math.max(0,v/Math.max(1,...result.monthly!)*115)}px`}}/><small>{months[i]}</small></div>)}</div><div className="guide-table-wrap"><table><caption>Monthly estimates, kWh</caption><thead><tr>{months.map(m=><th key={m}>{m}</th>)}</tr></thead><tbody><tr>{result.monthly.map((v,i)=><td key={i}>{Math.round(v).toLocaleString()}</td>)}</tr></tbody></table></div></>}
 {result.controllers&&<div className="guide-controller-results">{result.controllers.map(c=><article key={c.model}><div><h4>{c.model}</h4><strong>{c.preliminaryMatch?'Preliminary match':'Outside modeled limits'}</strong></div><p>{c.nominalPower.toLocaleString()} W nominal PV power at the entered battery class.</p>{c.failures.length>0&&<ul>{c.failures.map(f=><li key={f}>{f}</li>)}</ul>}{c.powerLimited&&<p>Array power exceeds nominal PV power. Manufacturer oversizing review required.</p>}<a href={c.source} target="_blank" rel="noopener noreferrer">Manufacturer limits ↗</a></article>)}</div>}
 {result.cash&&<details className="guide-cash"><summary>See the 25-year cash-flow scenario</summary><div className="guide-table-wrap"><table><thead><tr><th>Year</th><th>Annual savings, USD</th><th>Cumulative after upfront cost, USD</th></tr></thead><tbody>{result.cash.map(r=><tr key={r.year}><td>{r.year}</td><td>{Math.round(r.annualSavings).toLocaleString()}</td><td>{Math.round(r.cumulativeSavings).toLocaleString()}</td></tr>)}</tbody></table></div></details>}</section>}
 <section className="guide-method"><h3>Method & assumptions</h3><p className="guide-method-formula">{d.formula}</p><p>{d.note}</p>{id==='cable'&&<p>The example table’s ampacities are illustrative. Corrected installation ampacity, terminal ratings and local rules must be checked separately. Aluminum terminations require compatible listed hardware.</p>}{id==='payback'&&<p>Incentives default to zero. This is an undiscounted scenario, not an investment forecast; enter only a confirmed eligible incentive. <Link href="/guide/residential-credit-2026">Read the U.S. credit timing update →</Link></p>}{id==='pv'&&<p>For weather-based production modeling: <a href="https://pvwatts.nlr.gov/" target="_blank" rel="noopener noreferrer">PVWatts ↗</a> or <a href={d.source} target="_blank" rel="noopener noreferrer">PVGIS ↗</a>. No climate data is fetched by this workshop.</p>}<p><a href={d.source} target="_blank" rel="noopener noreferrer">{d.sourceName} ↗</a></p><p className="guide-origin">Adapted from the Solar4U project; methods checked October 4, 2026. Use these tools for planning and learning. Results do not replace exact equipment documentation or project-specific electrical, structural and utility review.</p></section></div></div></main>;
}
