import {ArrowUpRight,FileText} from 'lucide-react';
import type {Product} from '../lib/types';
import type {SpecEstimate} from '../lib/specification-estimates';
import {buildSpecification,specificationDisplayGroups} from '../lib/specifications';

const ratings=[['pmax','Maximum power (Pmax)'],['moduleEfficiency','Module efficiency'],['voc','Open-circuit voltage (Voc)'],['vmp','Maximum-power voltage (Vmp)'],['imp','Maximum-power current (Imp)'],['isc','Short-circuit current (Isc)']];
export function ProductSpecifications({product,estimates=[],gap}:{product:Product;estimates?:SpecEstimate[];gap?:string}){
 // Old station/panel evidence must not become a whole-bundle voltage or capacity rating.
 const details=product.category==='kits'?buildSpecification(product):product.specification||buildSpecification(product),panel=details.panelRatings;
 const sources=details.sources;
 const groups=specificationDisplayGroups(product,details),visibleGroups=groups.map(g=>({...g,fields:g.fields.filter(f=>!/^Not (?:verified|published)$/.test(f.value)||estimates.some(e=>e.key===f.key))})).filter(g=>g.fields.length);
 const missingGroups=groups.filter(g=>!visibleGroups.some(v=>v.title===g.title));
 const estimated=(key:string)=>{const e=estimates.find(f=>f.key===key);return e?<span className="spec-estimated-value" title={e.basis}>{e.value} <em className="spec-estimate-badge">estimate</em></span>:null;};
 const reference=(url?:string)=>{const n=sources.findIndex(s=>s.url===url);return n<0?null:<a className="spec-reference" href={'#spec-source-'+(n+1)} aria-label={'Source '+(n+1)}>[{n+1}]</a>;};
 return <section className="product-specifications" aria-label="Product specifications">
  <div className="spec-intro"><h2>{product.category==='kits'?'Bundle specifications':'Specifications'}</h2><p>{product.category==='kits'?'Check the exact included models for electrical ratings. Panel watts, station output and storage capacity describe different components.':details.summary}</p></div>
  {panel&&<section className="section-card panel-ratings"><div className="section-heading"><h3>Panel electrical ratings</h3><span className="small-text muted">Per panel</span></div><div className="table-scroll"><table className="data-table specification-ratings"><caption className="sr-only">STC and {panel.noctLabel||'NOCT'} electrical ratings</caption><thead><tr><th scope="col">Parameter</th><th scope="col">STC</th><th scope="col">{panel.noctLabel||'NOCT'}</th></tr></thead><tbody>{ratings.map(([rating,label])=>{const key=rating==='moduleEfficiency'?'efficiency':rating;return <tr key={key}><th scope="row">{label}</th><td>{panel.stc[key]?<>{panel.stc[key]} {reference(panel.sources?.['stc.'+key])}</>:estimated('stc.'+key)||<span className="spec-unpublished">Not verified</span>}</td><td>{panel.noct[key]?<>{panel.noct[key]} {reference(panel.sources?.['noct.'+key])}</>:<span className="spec-unpublished">Not published</span>}</td></tr>;})}</tbody></table></div><div className="spec-conditions"><p><strong>STC:</strong> 1,000 W/m² irradiance · 25°C cell temperature · AM 1.5.</p><p><strong>{panel.noctLabel||'NOCT'}:</strong> 800 W/m² irradiance · 20°C ambient · 1 m/s wind. Only published electrical ratings are shown.</p></div></section>}
  <div className="specification-groups">{visibleGroups.map(group=><section className="section-card specification-group" key={group.title}><h3>{group.title}</h3><dl>{group.fields.map(f=><div key={f.key}><dt>{f.label}</dt><dd className={f.source?'':'spec-unpublished'}>{f.value==='Not verified'?(estimated(f.key)||f.value):f.value} {reference(f.source)}{f.kind==='listing'&&<span className="spec-reference" title="Attribute from the selected product listing"> · listed</span>}</dd></div>)}</dl></section>)}</div>
  {missingGroups.length>0&&<details className="spec-missing-summary"><summary>Specifications not provided: {missingGroups.map(g=>g.title).join(', ')}</summary><p className="inline-note">These fields were not verified for this exact selection. Use the linked component model or retailer documents for ratings.</p></details>}
  {gap&&<aside className="spec-source-gap"><strong>Why specs are incomplete</strong><p>{gap}</p>{!estimates.length&&<p>No comparable equipment or usable measurements were found to support a meaningful estimate for this item.</p>}</aside>}
  {estimates.length>0&&<section className="section-card spec-estimates" aria-label="Specification estimates"><h3>Estimates for comparison</h3><p className="small-text">Approximate values for planning and comparison. Use the exact model datasheet for wiring, protection, and compatibility checks.</p>{estimates.filter(e=>e.key==='modeledPower'||!specificationDisplayGroups(product,details).flatMap(g=>g.fields).some(f=>f.key===e.key)).map(e=><p key={e.key}><strong>{e.label}:</strong> {estimated(e.key)}</p>)}<details><summary>How these estimates were made</summary>{estimates.map(e=><div className="spec-estimate-method" key={e.key}><strong>{e.label} · {e.value} <em className="spec-estimate-badge">estimate</em></strong><p>{e.basis}</p><ul>{e.references.map(r=><li key={r.url}><a href={r.url} target="_blank" rel="noreferrer">{r.label} <ArrowUpRight size={12}/></a></li>)}</ul></div>)}</details></section>}
  <section className="section-card spec-sources"><h3><FileText size={18}/> Source documents</h3><ol>{sources.map((source,i)=><li key={source.url} id={'spec-source-'+(i+1)}><a href={source.url} target="_blank" rel="noreferrer">{source.label} <ArrowUpRight size={13}/></a><span className="small-text muted">{source.kind==='listing'?'Listing identity; not a datasheet rating':source.kind==='datasheet'?'Datasheet':source.kind==='manual'?'Manual specifications':source.kind==='manufacturer'?'Manufacturer table':'Retailer table'}{source.model?' · '+source.model:''}{source.checkedAt?' · Checked '+source.checkedAt.slice(0,10):''}</span></li>)}</ol>{details.notes.length>0&&<ul className="spec-notes">{details.notes.map(note=><li key={note}>{note}</li>)}</ul>}</section>
 </section>;
}
