'use client';
import React,{createContext,useContext,useEffect,useState} from 'react';
import Link from './site-link';
import {Sun,Bell,Bookmark,Menu,X,ArrowRight,Plus} from 'lucide-react';
import type {Build,Product,CollectionReport} from '../lib/types';
import {bestOffer,costForQuantity,money} from '../lib/domain';
import {registerPVTools} from '../lib/webmcp';
type User={displayName:string;email:string}|null;
interface Context{products:Product[];reports:CollectionReport[];user:User;build:Build;setBuild:React.Dispatch<React.SetStateAction<Build>>;add:(id:string,offerId?:string)=>void;save:()=>Promise<string|undefined>;notify:(s:string)=>void;compare:string[];setCompare:React.Dispatch<React.SetStateAction<string[]>>;}
const initial:Build={name:'My solar build',lines:[],settings:{purpose:'offgrid',mount:'roof'}};
const ctx=createContext<Context|null>(null);
export function usePV(){const value=useContext(ctx);if(!value)throw new Error('PV provider missing');return value;}
export async function api(path:string,options?:RequestInit):Promise<any>{const r=await fetch('/api/'+path,{...options,headers:{'Content-Type':'application/json',...options?.headers}});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Please try again.');return d;}
export function PVProvider({products,reports,user,children}:{products:Product[];reports:CollectionReport[];user:User;children:React.ReactNode}){
 const[build,setBuild]=useState<Build>(initial),[ready,setReady]=useState(false),[notice,setNotice]=useState(''),[compare,setCompare]=useState<string[]>([]),[menu,setMenu]=useState(false);
 useEffect(()=>{try{const v=localStorage.getItem('pvpartpicker-draft');if(v){const p=JSON.parse(v);if(Array.isArray(p.lines)&&p.settings)setBuild(p);}const c=localStorage.getItem('pvpartpicker-compare');if(c){const ids=JSON.parse(c);if(Array.isArray(ids))setCompare(ids.filter(id=>products.some(p=>p.id===id)).slice(0,4));}}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready){localStorage.setItem('pvpartpicker-draft',JSON.stringify(build));localStorage.setItem('pvpartpicker-compare',JSON.stringify(compare));}},[build,compare,ready]);
 useEffect(()=>registerPVTools(products,build,setBuild),[products,build]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(t);},[notice]);
 const add=(id:string,offerId?:string)=>{setBuild(b=>({...b,lines:b.lines.some(l=>l.productId===id)?b.lines.map(l=>l.productId===id?{...l,quantity:Math.min(10000,l.quantity+1),...(offerId?{offerId}:{})}:l):[...b.lines,{productId:id,quantity:1,...(offerId?{offerId}:{})}]}));setNotice('Added to your build.');};
 const save=async()=>{if(!user){setNotice('Sign in with ChatGPT to save. Your draft stays on this device.');return;}try{const r=await api('builds',{method:'POST',body:JSON.stringify(build)});setBuild(b=>({...b,id:r.id}));setNotice('Build saved to your account.');return r.id as string;}catch(e){setNotice((e as Error).message);}};
 return <ctx.Provider value={{products,reports,user,build,setBuild,add,save,notify:setNotice,compare,setCompare}}><header className="site-header"><div className="header-inner"><Link href="/" className="brand" aria-label="PVPartPicker home"><span className="brand-symbol"><Sun size={23}/></span><span>PV<span className="brand-light">PartPicker</span><small>SOLAR, PIECE BY PIECE</small></span></Link><nav className={menu?'primary-nav open':'primary-nav'} aria-label="Main navigation"><Link href="/" onClick={()=>setMenu(false)}>Browse parts</Link><Link href="/build" onClick={()=>setMenu(false)}>System builder <span className="tiny-count">{build.lines.length}</span></Link><Link href="/deals" onClick={()=>setMenu(false)}>Price drops</Link><Link href="/tiers" onClick={()=>setMenu(false)}>Tier lists</Link><Link href="/learn" onClick={()=>setMenu(false)}>Solar basics</Link></nav><div className="header-actions"><Link href="/account?tab=alerts" className="icon-button" aria-label="Your price alerts"><Bell size={19}/></Link>{user?<Link className="account-button" href="/account"><span className="avatar">{user.displayName[0]?.toUpperCase()}</span><span className="desktop">My account</span></Link>:<a className="button small dark" href="/signin-with-chatgpt?return_to=%2Faccount" target="_top">Sign in <ArrowRight size={14}/></a>}<button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div></div></header><div className="market-bar"><span><i/> US retailers · USD</span><span>Build your system. Compare the options. Buy with confidence.</span><span className="desktop">Independent product comparisons</span></div>{children}<footer className="site-footer"><Link className="footer-brand" href="/">☀ PVPartPicker</Link><span>Prices are observed, not guaranteed. Check retailer shipping, tax, and availability.</span><Link href="/learn">Buying guide</Link><Link href="/admin">Administration</Link></footer>{compare.length>0&&<div className="compare-dock"><span><strong>{compare.length}</strong> parts selected</span><Link className="button dark small" href="/compare">Compare parts <ArrowRight size={14}/></Link><button aria-label="Clear comparison" className="icon-button" onClick={()=>setCompare([])}><X size={16}/></button></div>}{notice&&<div className="toast" role="status">{notice}<button className="icon-button" onClick={()=>setNotice('')} aria-label="Dismiss message"><X size={15}/></button></div>}</ctx.Provider>;
}
export function ProductImage({product,className=''}:{product:Product;className?:string}){const[failed,setFailed]=useState(false);return <div className={'product-image '+className}>{product.image&&!failed?<img src={product.image} alt={product.name} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<div className="image-fallback"><Sun size={30}/><span>Image unavailable</span></div>}</div>;}
export function BuildSummary(){const{build,products,setBuild,save,user}=usePV();let subtotal=0,unpriced=0;const lines=build.lines.map(line=>{const p=products.find(p=>p.id===line.productId);const offer=p?(line.offerId?p.offers.find(o=>o.id===line.offerId&&bestOffer({...p,offers:[o]},line.quantity)):bestOffer(p,line.quantity)):undefined;const cost=offer?costForQuantity(offer,line.quantity):null;if(cost)subtotal+=cost.subtotal;else unpriced++;return{line,p,cost};});return <aside className="build-summary"><div className="eyebrow">YOUR SOLAR SYSTEM</div><h3>One part at a time <Sun size={19}/></h3><div className="summary-body">{lines.length?lines.slice(0,4).map(({line,p,cost})=><div className="summary-item" key={line.productId}><span className="qty-pill">{line.quantity}×</span><div><Link href={'/products/'+line.productId}>{p?.name||'Unavailable product'}</Link><small>{cost?money(cost.subtotal):'Needs a current offer'}</small></div><button className="icon-button" aria-label={'Remove '+p?.name} onClick={()=>setBuild(b=>({...b,lines:b.lines.filter(l=>l.productId!==line.productId)}))}><X size={13}/></button></div>):<div className="summary-empty"><span className="empty-sun"><Plus size={23}/></span><p>Your build starts here.</p><small>Add parts to compare your system’s cost and compatibility.</small></div>}{lines.length>4&&<p className="muted small-text">+ {lines.length-4} more parts in your build</p>}</div><div className="summary-total"><span>Equipment subtotal</span><strong>{money(subtotal)}</strong></div><p className="micro">{unpriced?`${unpriced} items need current pricing. `:''}Shipping and tax calculated by retailers.</p><Link className="button dark full" href="/build">{lines.length?'Review your build':'Open system builder'} <ArrowRight size={16}/></Link>{lines.length>0&&<button className="button outline full" onClick={save}><Bookmark size={15}/>{user?'Save build':'Save with ChatGPT'}</button>}<div className="summary-tip"><Sun size={17}/><span>New to solar? <Link href="/learn">Start with the essentials.</Link></span></div></aside>;}
