'use client';
import {useEffect,useState} from 'react';
import {Plus,RefreshCw,Play,Pause,Clock,Activity,Globe,Settings2,ArrowUpRight,X,CheckCircle2,ListTodo} from 'lucide-react';
import Link from './site-link';
import {api,usePV} from './pv-provider';
import type {ScraperSite} from '../lib/scraper-config';
const defaults:ScraperSite={id:'',name:'',origin:'',enabled:true,adapter:'sitemap',startPath:'/sitemap.xml',urls:[],schedule:'interval',frequencyMinutes:360,dailyTime:'06:17',weekdays:[0,1,2,3,4,5,6],delaySeconds:10,jitterSeconds:2,maxPages:24,feedPages:1,usdConfirmed:false};
const date=(s?:string|null)=>s?new Date(s).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const dollars=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const schedule=(s:ScraperSite)=>s.schedule==='manual'?'Manual only':s.schedule==='daily'?`${s.dailyTime} UTC · ${s.weekdays.length===7?'daily':s.weekdays.map(i=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i]).join(', ')}`:`Every ${s.frequencyMinutes<60?s.frequencyMinutes+' min':s.frequencyMinutes/60+' hr'}`;
function Badge({status}:{status:string}){return <span className={'scraper-status status-'+status}>{status.replaceAll('_',' ')}</span>;}
export function detailForSelectedSource<T>(selected:string,loadedSource:string,detail:T):T|null{return selected&&selected===loadedSource?detail:null;}
export function filterScraperRuns<T extends {siteId:string}>(jobs:T[],source:string):T[]{return source==='all'?jobs:jobs.filter(job=>job.siteId===source);}
export function ScraperWorkspace(){
  const {user,notify}=usePV();const [data,setData]=useState<any>(null),[detailSource,setDetailSource]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[live,setLive]=useState(true),[tab,setTab]=useState('sites'),[selected,setSelected]=useState(''),[editing,setEditing]=useState<ScraperSite|null>(null),[urlText,setUrlText]=useState(''),[search,setSearch]=useState(''),[runFilter,setRunFilter]=useState('all'),[run,setRun]=useState<any>(null),[runId,setRunId]=useState(''),[revision,setRevision]=useState(0);
  useEffect(()=>{let active=true,pending=false;const controller=new AbortController();async function load(){if(pending)return;pending=true;try{const result=await api('scraper'+(selected?'?siteId='+encodeURIComponent(selected):''),{signal:controller.signal});if(active){setData(result);setDetailSource(selected);setError('');}if(runId){const detail=await api('scraper/run?id='+encodeURIComponent(runId),{signal:controller.signal});if(active)setRun(detail);}}catch(e){if(active&&!controller.signal.aborted)setError((e as Error).message);}finally{pending=false;if(active)setLoading(false);}}
  queueMicrotask(()=>{if(active){setLoading(true);setError('');void load();}});const timer=live?setInterval(()=>{if(document.visibilityState==='visible')load();},10000):null;return()=>{active=false;controller.abort();if(timer)clearInterval(timer);};
 },[selected,live,revision,runId]);
 async function mutate(value:unknown,message:string){setBusy(true);try{const result=await api('scraper',{method:'POST',body:JSON.stringify(value)});notify(message);setError('');setRevision(n=>n+1);return result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 const edit=(s:ScraperSite)=>{setEditing({...s});setUrlText(s.urls.join('\n'));};
  const jobs=data?.jobs||[],sources=data?.sites||[],active=jobs.filter((j:any)=>['queued','running'].includes(j.status)),done=jobs.filter((j:any)=>!['queued','running'].includes(j.status)),site=sources.find((s:any)=>s.id===selected),latest=(id:string)=>jobs.find((j:any)=>j.siteId===id);
  const detail=detailForSelectedSource(selected,detailSource,data?.detail),visibleRuns=filterScraperRuns(tab==='queue'?active:done,runFilter);
 const editField=(key:keyof ScraperSite,value:unknown)=>setEditing(s=>s?{...s,[key]:value}:s);
 const heartbeat=data?.heartbeat,runnerRecent=heartbeat&&Date.now()-Date.parse(heartbeat.at)<45*60000;
 return <main className="page-container scraper-workspace"><div className="scraper-title"><div><div className="eyebrow">OWNER TOOLS · PRICE COLLECTION</div><h1>Price Scraper</h1><p>Choose your sources. Set the pace. Keep your prices current.</p></div><div className="flex-actions"><Link className="button outline small" href="/admin">Catalog admin</Link>{data&&<button className="button dark small" onClick={()=>edit({...defaults})}><Plus size={15}/>Add site</button>}</div></div>
 {error&&<div className="error-message" role="alert">{error}{!data&&!user&&<p><a className="button dark small" href="/signin-with-chatgpt?return_to=%2Fprice-scraper" target="_top">Sign in as owner</a></p>}</div>}{loading&&!data&&<p role="status">Loading scraper workspace…</p>}
 {data&&<><div className="scraper-stats"><div><Globe size={18}/><span>Sources<strong>{sources.filter((s:any)=>s.enabled).length}<small> / {sources.length} enabled</small></strong></span></div><div><ListTodo size={18}/><span>Queue<strong>{active.length}<small> pending / running</small></strong></span></div><div><CheckCircle2 size={18}/><span>Accepted observations<strong>{jobs.reduce((sum:number,j:any)=>sum+j.progress.inserted,0).toLocaleString()}<small> across recent runs</small></strong></span></div><div><Activity size={18}/><span>Collector<strong className={runnerRecent?'scraper-online':''}>{heartbeat?(runnerRecent?'Connected':'Last seen'):'Awaiting first check-in'}</strong><small>{heartbeat?date(heartbeat.at):'New job history starts with the next run'}</small></span></div></div>
 <div className="scraper-toolbar"><nav className="tab-nav" aria-label="Scraper sections">{[['sites','Sites & settings'],['queue',`Queue (${active.length})`],['history','Run history']].map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="flex-actions"><label className="scraper-live"><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/>Live updates</label><button className="icon-button" aria-label="Refresh scraper data" onClick={()=>setRevision(n=>n+1)}><RefreshCw size={16}/></button></div></div>
 <p className="scraper-runner-note"><Clock size={14}/>Checks due work every 15 minutes; scheduled starts can be delayed. {heartbeat?.runUrl&&<a className="text-link" href={heartbeat.runUrl} target="_blank" rel="noreferrer">Latest collector run <ArrowUpRight size={12}/></a>}<span>Updated {date(data.now)} · times shown in your timezone</span></p>
 {editing&&<section className="section-card scraper-editor"><div className="scraper-section-heading"><h2>{editing.id?'Edit '+editing.name:'Add a price source'}</h2><button className="icon-button" aria-label="Close site editor" onClick={()=>setEditing(null)}><X size={17}/></button></div><form onSubmit={async e=>{e.preventDefault();const result=await mutate({action:'save',id:editing.id,site:{...editing,urls:urlText.split('\n').map(u=>u.trim()).filter(Boolean)}},'Source settings saved.');if(result){setSelected(result.id);setEditing(null);setTab('sites');}}}>
 <div className="scraper-form-grid"><label className="field">Site name<input required maxLength={80} value={editing.name} onChange={e=>editField('name',e.target.value)} placeholder="Solar retailer"/></label><label className="field">Website origin<input required type="url" readOnly={Boolean(editing.id)} value={editing.origin} onChange={e=>editField('origin',e.target.value)} placeholder="https://www.retailer.com"/></label><label className="field">Collection method<select value={editing.adapter} onChange={e=>editField('adapter',e.target.value)}><option value="sitemap">Sitemap + product pages (JSON-LD)</option><option value="pages">Specific product pages (JSON-LD)</option><option value="shopify">Shopify public product feed</option><option value="woocommerce">WooCommerce Store API</option></select></label><label className="field">Schedule<select value={editing.schedule} onChange={e=>editField('schedule',e.target.value)}><option value="interval">Repeat at an interval</option><option value="daily">Daily at a time (UTC)</option><option value="manual">Manual queue only</option></select></label>
 {editing.adapter==='sitemap'&&<label className="field">Starting sitemap path<input required value={editing.startPath} onChange={e=>editField('startPath',e.target.value)} placeholder="/sitemap.xml"/></label>}
 {editing.schedule==='interval'&&<label className="field">Frequency (minutes)<input type="number" min={15} max={10080} required value={editing.frequencyMinutes} onChange={e=>editField('frequencyMinutes',Number(e.target.value))}/><small>15 min minimum · 360 = 6 hours · 1440 = daily</small></label>}
 {editing.schedule==='daily'&&<><label className="field">Time (UTC)<input required type="time" value={editing.dailyTime} onInput={e=>editField('dailyTime',e.currentTarget.value)} onChange={e=>editField('dailyTime',e.target.value)}/></label><fieldset className="scraper-weekdays"><legend>Days of the week</legend>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((label,i)=><label key={i}><input type="checkbox" checked={editing.weekdays.includes(i)} onChange={e=>editField('weekdays',e.target.checked?[...editing.weekdays,i]:editing.weekdays.filter(n=>n!==i))}/>{label}</label>)}</fieldset></>}
 <label className="field">Seconds between requests<input type="number" min={10} max={300} required value={editing.delaySeconds} onChange={e=>editField('delaySeconds',Number(e.target.value))}/><small>One request at a time per source. Published crawl delays take priority.</small></label><label className="field">Random extra delay (seconds)<input type="number" min={0} max={30} required value={editing.jitterSeconds} onChange={e=>editField('jitterSeconds',Number(e.target.value))}/></label>
 {['shopify','woocommerce'].includes(editing.adapter)?<label className="field">Feed pages per run<input type="number" min={1} max={4} required value={editing.feedPages} onChange={e=>editField('feedPages',Number(e.target.value))}/><small>Up to 250 Shopify products or 100 WooCommerce products per page.</small></label>:<label className="field">Product pages per run<input type="number" min={1} max={80} required value={editing.maxPages} onChange={e=>editField('maxPages',Number(e.target.value))}/><small>Known URLs are checked oldest first; each job has a 12-minute time budget.</small></label>}
 </div>{['pages','sitemap'].includes(editing.adapter)&&<label className="field">{editing.adapter==='pages'?'Product URLs (required)':'Priority product URLs (optional)'}<textarea rows={4} value={urlText} onChange={e=>setUrlText(e.target.value)} placeholder="One URL per line, on this website"/><small>Public USD listings with Product JSON-LD. No login or browser challenge bypass.</small></label>}<div className="scraper-save-row">{editing.adapter==='shopify'&&<label><input type="checkbox" required checked={editing.usdConfirmed||false} onChange={e=>editField('usdConfirmed',e.target.checked)}/> Feed prices verified as USD</label>}<label><input type="checkbox" checked={editing.enabled} onChange={e=>editField('enabled',e.target.checked)}/> Source enabled</label><button disabled={busy} className="button dark">{busy?'Saving…':'Save source'}</button></div></form></section>}
 {tab==='sites'&&<><div className="scraper-list-heading"><input aria-label="Search scraper sites" placeholder="Find a site or domain…" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy} className="button outline small" onClick={()=>mutate({action:'queue'},'Enabled sources queued. Existing active jobs are kept.')}><Play size={13}/>Queue all enabled</button></div><div className="table-scroll scraper-table-wrap"><table className="data-table scraper-table"><thead><tr><th>Source</th><th>Method / schedule</th><th>Pace</th><th>Next scheduled</th><th>Last run / offers</th><th>Controls</th></tr></thead><tbody>{sources.filter((s:any)=>(s.name+' '+s.origin).toLowerCase().includes(search.toLowerCase())).map((s:any)=>{const last=latest(s.id);return <tr key={s.id} className={selected===s.id?'scraper-selected':''}><td><button className="scraper-source-name" onClick={()=>setSelected(s.id)}>{s.name}</button><small>{new URL(s.origin).hostname}</small><Badge status={s.enabled?'enabled':'paused'}/></td><td>{schedule(s)}<small>{s.adapter} · {['shopify','woocommerce'].includes(s.adapter)?s.feedPages+' feed pages':s.maxPages+' product pages'} / run</small></td><td>{s.delaySeconds}s + 0–{s.jitterSeconds}s<small>between requests</small></td><td>{s.enabled?s.nextAt?date(s.nextAt):'Manual only':'Paused'}<small>{s.nextAt&&s.enabled&&Date.parse(s.nextAt)<=Date.now()?'Due at next collector check':''}</small></td><td>{last?<Badge status={last.status}/>:<span className="muted">No managed runs yet</span>}<small>{s.stats.offers} tracked offers · latest {date(s.stats.latest)}</small></td><td><div className="scraper-row-actions"><button disabled={busy||!s.enabled} className="button outline small" onClick={()=>mutate({action:'queue',id:s.id},s.name+' queued for the collector.')}><Play size={13}/>Queue now</button><button disabled={busy} className="icon-button" aria-label={(s.enabled?'Pause ':'Resume ')+s.name} onClick={()=>mutate({action:'save',id:s.id,site:{...s,enabled:!s.enabled}},s.name+(s.enabled?' paused.':' resumed.'))}>{s.enabled?<Pause size={15}/>:<Play size={15}/>}</button><button className="icon-button" aria-label={'Edit '+s.name} onClick={()=>edit(s)}><Settings2 size={15}/></button></div></td></tr>;})}</tbody></table></div><p className="inline-note">Queue now adds a job for the next collector check. Pausing cancels queued work and stops running work before its next request; saved prices stay available.</p>
 {tab==='sites'&&site&&!detail&&<div className="notice-panel">{loading?<p role="status">Loading {site.name} listings and observations…</p>:<><p>Details for {site.name} could not load.</p><button className="button outline small" onClick={()=>setRevision(n=>n+1)}>Retry source details</button></>}</div>}{site&&detail&&<section className="section-card scraper-detail"><div className="scraper-section-heading"><div><h2>{site.name}</h2><p>{site.stats.offers} tracked offers · oldest check {date(site.stats.oldest)}</p></div><button className="button outline small" onClick={()=>edit(site)}><Settings2 size={14}/>Settings</button></div><h3>What will be checked</h3>{['shopify','woocommerce'].includes(site.adapter)?<p className="scraper-feed-plan">{site.feedPages} public feed pages · {site.adapter==='shopify'?'/products.json':'/wp-json/wc/store/v1/products'} · parsed variants update existing offers by SKU.</p>:<p className="inline-note">Up to {site.maxPages} product pages: {site.adapter==='sitemap'?'roughly 20% reserved for rotating sitemap discovery, with the rest used for priority and oldest known offers':'only the product URLs configured below'}. Full discovery occurs when the run starts.</p>}
 {site.urls.length>0&&<ul className="scraper-priority">{site.urls.map((u:string)=><li key={u}><a href={u} target="_blank" rel="noreferrer">{u}</a></li>)}</ul>}
 <div className="table-scroll"><table className="data-table"><thead><tr><th>Oldest known listings</th><th>Last observed price</th><th>Last checked</th></tr></thead><tbody>{detail.targets.slice(0,12).map((t:any)=><tr key={t.id}><td><a href={t.url} target="_blank" rel="noreferrer">{t.name||t.url}</a></td><td>{dollars(t.price)}</td><td>{date(t.checkedAt)}</td></tr>)}</tbody></table></div>{!detail.targets.length&&<p className="inline-note">No known offers yet. The first run will inspect the configured source.</p>}<h3>Recent stored observations</h3><p className="inline-note">Observed package prices; open a product for its retailer price-history graph.</p><div className="table-scroll"><table className="data-table"><thead><tr><th>Product</th><th>Package price</th><th>Pack quantity</th><th>Stock</th><th>Observed</th></tr></thead><tbody>{detail.observations.slice(0,30).map((o:any,i:number)=><tr key={i}><td>{o.productId?<Link href={'/products/'+o.productId}>{o.name}</Link>:o.name}</td><td>{dollars(o.price)}</td><td>{o.packQuantity}</td><td>{o.stock.replaceAll('_',' ')}</td><td>{date(o.observedAt)}</td></tr>)}</tbody></table></div>{!detail.observations.length&&<p className="inline-note">No stored observations for this source yet.</p>}</section>}</>}
 {tab!=='sites'&&<><div className="scraper-list-heading"><h2>{tab==='queue'?'Pending & active jobs':'Recent collection runs'}</h2><select aria-label="Filter scrape runs" value={runFilter} onChange={e=>setRunFilter(e.target.value)}><option value="all">All sources</option>{sources.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{tab==='history'&&done.length>0&&<div className="scraper-chart" aria-label="Accepted observations per recent completed run"><div>{done.slice(0,24).reverse().map((j:any)=><button key={j.id} title={`${j.site.name}: ${j.progress.inserted} accepted observations (${j.status})`} aria-label={`Open ${j.site.name} run with ${j.progress.inserted} accepted observations`} onClick={()=>{setRun(null);setRunId(j.id);}} style={{height:Math.max(4,j.progress.inserted/Math.max(1,...done.map((r:any)=>r.progress.inserted))*72)}}/>)}</div><small>Accepted observations per run · oldest → latest · click a bar for details</small></div>}
 <div className="table-scroll scraper-table-wrap"><table className="data-table scraper-table"><thead><tr><th>Source / queued</th><th>Status</th><th>Progress</th><th>Observations</th><th>Message / controls</th></tr></thead><tbody>{visibleRuns.map((j:any)=><tr key={j.id}><td><button className="scraper-source-name" onClick={()=>{setRun(null);setRunId(j.id);}}>{j.site.name}</button><small>{date(j.queuedAt)}</small></td><td><Badge status={j.status}/><small>{j.cancelRequested?'Cancellation requested':date(j.finishedAt||j.startedAt)}</small></td><td>{j.progress.requests} requests · {j.progress.checked} parsed<small>{j.progress.planned} planned {['shopify','woocommerce'].includes(j.site.adapter)?'feed pages':'product pages'} · {j.progress.errors} request errors</small></td><td>{j.progress.inserted} accepted<small>{j.progress.found} parsed offers · {j.progress.quarantined} quarantined</small></td><td><p className="scraper-job-message">{j.progress.message}</p><div className="flex-actions"><button className="text-link" onClick={()=>{setRun(null);setRunId(j.id);}}>View details</button>{['queued','running'].includes(j.status)&&<button disabled={busy||j.cancelRequested} className="button outline small" onClick={()=>mutate({action:'cancel',id:j.id},'Cancellation requested.')}><X size={12}/>Cancel</button>}{tab==='history'&&<button disabled={busy||!sources.find((s:any)=>s.id===j.siteId)?.enabled} className="button outline small" onClick={()=>mutate({action:'queue',id:j.siteId},'A new run has been queued.')}><RefreshCw size={12}/>Run again</button>}</div></td></tr>)}</tbody></table></div>{!visibleRuns.length&&<div className="empty-state"><ListTodo size={26}/><h3>{runFilter!=='all'?'No runs match this source.':tab==='queue'?'The queue is clear.':'Managed run history starts here.'}</h3><p>{runFilter!=='all'?'Choose another source or clear the filter to see all runs.':tab==='queue'?'Queue a source now, or let its schedule add the next job.':'Results appear when the collector runs. Existing prices and legacy reports remain available.'}</p>{runFilter!=='all'&&<button className="button outline small" onClick={()=>setRunFilter('all')}>Show all sources</button>}</div>}
 {tab==='history'&&data.legacy.length>0&&<details className="section-card"><summary>Legacy collection reports</summary><p className="inline-note">Recorded before managed jobs. Per-request progress was not recorded for these runs.</p>{data.legacy.slice(0,6).map((r:any,i:number)=><div className="scraper-legacy" key={i}><time>{date(r.createdAt)}</time>{r.reports.map((p:any,j:number)=><p key={j}><strong>{p.retailer}</strong> · {p.status} · {p.products} products · {p.message}</p>)}</div>)}</details>}</>}
 {runId&&<section className="section-card scraper-run-detail"><div className="scraper-section-heading"><h2>{run?'Run details · '+run.job.site.name:'Loading run…'}</h2><button className="icon-button" aria-label="Close run details" onClick={()=>{setRunId('');setRun(null);}}><X size={17}/></button></div>{run&&<><div className="flex-actions"><Badge status={run.job.status}/><span className="inline-note">{date(run.job.startedAt)} → {date(run.job.finishedAt)}</span></div><p>{run.job.progress.message}</p><p className="inline-note">Settings used: {schedule(run.job.site)} · {run.job.site.delaySeconds}s request spacing · {run.job.site.adapter}</p>{run.job.progress.currentUrl&&<p className="scraper-current">Latest target: {run.job.progress.currentUrl}</p>}<div className="table-scroll"><table className="data-table"><thead><tr><th>Request / time</th><th>Result</th><th>Duration</th><th>Details</th></tr></thead><tbody>{run.events.map((e:any,i:number)=><tr key={i}><td><a href={e.url} target="_blank" rel="noreferrer">{e.url}</a><small>{date(e.at)}</small></td><td><Badge status={e.status}/>{e.httpStatus&&<small>HTTP {e.httpStatus}</small>}</td><td>{e.durationMs}ms</td><td>{e.message}</td></tr>)}</tbody></table></div>{!run.events.length&&<p className="inline-note">No requests recorded yet.</p>}</>}</section>}
 </>}</main>;
}
