'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {calculatorDefinitions,type Report,type Values} from '../lib/guide-calculators';
import {solarProduction,type SolarArray} from '../lib/solar-production';
import CalculatorChart from './calculator-chart';
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const colors=['#087e8b','#dd8829','#7354b0','#c64e72'];
type Face={capacityKw:string;tilt:string;azimuth:string};
type Locality={id:number;label:string;latitude:number;longitude:number};
export default function SolarProductionCalculator(){
 const d=calculatorDefinitions.find(d=>d.id==='pv')!;
 const defaults=()=>Object.fromEntries(Object.entries(d.defaults).map(([k,v])=>[k,String(v)]));
 const [draft,setDraft]=useState(defaults),[multiple,setMultiple]=useState(false),[faces,setFaces]=useState<Face[]>([{capacityKw:'5',tilt:'35',azimuth:'180'},{capacityKw:'5',tilt:'30',azimuth:'90'}]);
 const [query,setQuery]=useState(''),[locations,setLocations]=useState<Locality[]>([]),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(''),[climate,setClimate]=useState<{signature:string;report:Report}|null>(null),[loading,setLoading]=useState(false),[climateError,setClimateError]=useState('');
 const climateRequest=useRef<AbortController|null>(null),locationRequest=useRef<AbortController|null>(null),revision=useRef(0),searchRevision=useRef(0);
 const signature=JSON.stringify([draft,multiple,faces]);
 const local=useMemo(()=>{try{const v:Values={};for(const f of d.fields){if(multiple&&['capacityKw','tilt','azimuth'].includes(f.key)){v[f.key]=d.defaults[f.key];continue;}if(!draft[f.key]?.trim())throw new Error(`Enter ${f.label}.`);v[f.key]=Number(draft[f.key]);}
  let arrays:SolarArray[]|undefined;if(multiple)arrays=faces.map((f,i)=>{if(Object.values(f).some(x=>!x.trim()))throw new Error(`Complete roof face ${i+1}.`);return{capacityKw:Number(f.capacityKw),tilt:Number(f.tilt),azimuth:Number(f.azimuth)};});
  return{values:v,arrays,report:solarProduction(v,arrays),error:''};
 }catch(e){return{error:e instanceof Error?e.message:'Check solar inputs.'};}},[draft,multiple,faces,d.fields]);
 const report=climate?.signature===signature?climate.report:local.report;
 function invalidate(){revision.current++;climateRequest.current?.abort();setLoading(false);setClimateError('');setClimate(null);}
 useEffect(()=>()=>{climateRequest.current?.abort();locationRequest.current?.abort();},[]);
 async function findLocation(){locationRequest.current?.abort();const request=new AbortController(),version=++searchRevision.current;locationRequest.current=request;setSearching(true);setSearchError('');setLocations([]);try{
  const r=await fetch('/api/solar-calculator?'+new URLSearchParams({kind:'location',q:query}),{signal:AbortSignal.any([request.signal,AbortSignal.timeout(12000)])});const data=await r.json() as {error?:string;locations:Locality[]};if(!r.ok)throw new Error(data.error??'Location search unavailable.');if(version===searchRevision.current)setLocations(data.locations);
 }catch(e){if(!request.signal.aborted&&version===searchRevision.current)setSearchError(e instanceof Error?e.message:'Enter coordinates below.');}finally{if(version===searchRevision.current)setSearching(false);}}
 async function getClimate(){if(!local.values)return;climateRequest.current?.abort();const request=new AbortController(),version=++revision.current;climateRequest.current=request;setLoading(true);setClimateError('');try{
  const params=new URLSearchParams({kind:'climate',inputs:JSON.stringify(local.values),...(local.arrays?{arrays:JSON.stringify(local.arrays)}:{})});
  const r=await fetch('/api/solar-calculator?'+params,{signal:AbortSignal.any([request.signal,AbortSignal.timeout(65000)])});const data=await r.json() as Report & {error?:string};if(!r.ok)throw new Error(data.error??'PVGIS is unavailable.');if(version===revision.current)setClimate({signature,report:data});
 }catch(e){if(!request.signal.aborted&&version===revision.current){setClimate(null);setClimateError((e instanceof Error?e.message:'Climate estimate unavailable.')+' Showing the current instant estimate.');}}finally{if(version===revision.current)setLoading(false);}}
 function exportResult(){if(!report||!local.values)return;const url=URL.createObjectURL(new Blob([JSON.stringify({calculator:'pv',methodChecked:'2026-10-05',inputs:local.values,arrays:local.arrays??null,result:report,source:d.source},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pvpartpicker-solar-production.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const fields=d.fields.filter(f=>!multiple||!['capacityKw','tilt','azimuth'].includes(f.key));
 const tiltLabels=[0,15,30,45,60,75,90];
 return <div className="solar-production-calculator"><section className="calc-location"><h3>Where is your system?</h3><form onSubmit={e=>{e.preventDefault();void findLocation();}}><label htmlFor="pv-location">City or postal code<input id="pv-location" value={query} placeholder="e.g. Buffalo, Madrid, Sydney" maxLength={100} onChange={e=>{searchRevision.current++;locationRequest.current?.abort();setSearching(false);setLocations([]);setSearchError('');setQuery(e.target.value);}}/></label><button type="submit" className="button outline" disabled={searching||query.trim().length<2}>{searching?'Searching…':'Find location'}</button></form>{locations.length>0&&<div className="calc-location-results" aria-label="Location results">{locations.map(l=><button key={l.id} onClick={()=>{invalidate();setDraft({...draft,latitude:String(l.latitude),longitude:String(l.longitude)});setQuery(l.label);setLocations([]);}}>{l.label}<small>{l.latitude.toFixed(4)}, {l.longitude.toFixed(4)}</small></button>)}</div>}{searchError&&<p className="guide-input-error" role="alert">{searchError}</p>}<p className="calc-footnote">Search: Open-Meteo / GeoNames. Verify the exact coordinates below; a locality is not a roof location.</p></section>
 <label className="calc-array-switch"><input type="checkbox" checked={multiple} onChange={e=>{invalidate();setMultiple(e.target.checked);}}/>Separate roof faces or arrays</label>
 <div className="guide-input-grid">{fields.map(f=><label key={f.key} htmlFor={'pv-'+f.key}><span>{f.label}<small>{f.unit}</small></span><input id={'pv-'+f.key} type="number" min={f.min} max={f.max} step={f.step??'any'} value={draft[f.key]??''} onChange={e=>{invalidate();setDraft({...draft,[f.key]:e.target.value});}}/>{f.key==='azimuth'?<small>N 0° · E 90° · S 180° · W 270°</small>:f.key==='peakSunHours'?<small>Instant estimate only · equivalent full-sun hours/day</small>:<small>Range {f.min}–{f.max}</small>}</label>)}</div>
 {multiple&&<section className="calc-roof-faces"><div className="calc-section-heading"><h3>Independent roof faces</h3><span>{faces.length} / 12 faces</span></div>{faces.map((face,i)=><fieldset key={i}><legend>Roof face {i+1}</legend><div className="guide-input-grid">{(['capacityKw','tilt','azimuth'] as const).map(key=><label key={key} htmlFor={`face-${i}-${key}`}><span>{key==='capacityKw'?'Capacity · kW':key==='tilt'?'Tilt · °':'Direction · ° from north'}</span><input id={`face-${i}-${key}`} type="number" min="0" max={key==='capacityKw'?1000:key==='tilt'?90:360} step="any" value={face[key]} onChange={e=>{invalidate();setFaces(faces.map((f,j)=>i===j?{...f,[key]:e.target.value}:f));}}/></label>)}</div><button className="text-link" disabled={faces.length===1} onClick={()=>{invalidate();setFaces(faces.filter((_,j)=>j!==i));}}>Remove face {i+1}</button></fieldset>)}<button className="button outline" disabled={faces.length===12} onClick={()=>{invalidate();setFaces([...faces,{capacityKw:'2',tilt:'30',azimuth:'180'}]);}}>+ Add roof face</button><p className="calc-footnote">Capacity is the sum of these faces. Each is modeled separately; shared coordinates, losses and sun-hours apply to all faces.</p></section>}
 <div className="guide-calculator-actions"><button className="button outline" onClick={()=>{invalidate();searchRevision.current++;locationRequest.current?.abort();setSearching(false);setSearchError('');setDraft(defaults());setMultiple(false);setFaces([{capacityKw:'5',tilt:'35',azimuth:'180'},{capacityKw:'5',tilt:'30',azimuth:'90'}]);setQuery('');setLocations([]);}}>Reset example</button><span>Instant estimates update as you edit. Azimuth is measured clockwise from north; tilt is measured from horizontal.</span></div>
 {local.error&&<p className="guide-input-error" role="alert">{local.error}</p>}
 {report&&<section className="guide-results"><div className="guide-results-heading"><h3>Your production estimate</h3><button className="text-link" onClick={exportResult}>Download result ↓</button></div><div className="guide-result-stats" aria-live="polite">{report.stats.map(s=><div key={s.label}><span>{s.label}</span><strong>{s.value} <small>{s.unit}</small></strong></div>)}</div><div className="calc-provider"><strong>{String(report.raw.provider)}</strong><button className="button dark" disabled={loading||!local.values} onClick={()=>void getClimate()}>{loading?'Reading climate data…':'Get PVGIS climate estimate'}</button></div><p className="guide-result-notice">{report.notice}</p><p className="calc-footnote">PVGIS sends coordinates and array parameters to EU JRC. Editing any input restores the current instant estimate. Peak sun hours affect the instant model only.</p>{climateError&&<p className="guide-input-error" role="alert">{climateError}</p>}
 <CalculatorChart title="Monthly solar production" labels={months} unit="kWh / month" xTitle="Month · long-term modeled average" bars series={[{name:'Total solar production',values:report.monthly!,color:'#087e8b'}]}/>
 {multiple&&<CalculatorChart title="Compare roof faces" labels={months} unit="kWh / month" xTitle="Month" series={(report.raw.arrays as {monthlyKwh:number[]}[]).map((a,i)=>({name:'Roof face '+(i+1),values:a.monthlyKwh,color:colors[i%colors.length]}))}/>}
 {local.values&&<CalculatorChart title="Explore tilt · instant-model sensitivity" labels={tiltLabels.map(String)} unit="Annual kWh" xTitle="Tilt from horizontal · °" series={[{name:'All faces at the same test tilt',color:'#dd8829',values:tiltLabels.map(tilt=>Number(solarProduction({...local.values!,tilt},local.arrays?.map(a=>({...a,tilt}))).raw.annualKwh))}]}/>}
 <p className="calc-footnote">The tilt sensitivity chart always uses Solar4U’s simplified model. It holds directions, capacity and the sun-hours assumption fixed; it is not a PVGIS optimization study.</p></section>}
 </div>;
}
