'use client';
import {useState} from 'react';
import Link from './site-link';
import {Eye,Bell,Search,TrendingDown,Plus,ArrowUpRight,RefreshCw} from 'lucide-react';
import {usePV,WatchButton,ProductImage} from './pv-provider';
import {AlertModal} from './product-detail';
import {usePriceDrops} from './use-price-drops';
import {freshOffers,money} from '../lib/domain';
import {categories} from '../lib/types';
import {bestDropsByProduct} from '../lib/price-drops';
import type {Product} from '../lib/types';
export function WatchWorkspace(){
 const{products,user,watchIds,watchReady,watchError,reloadWatch,toggleWatch,add}=usePV(),[q,setQ]=useState(''),[category,setCategory]=useState(''),[sort,setSort]=useState('saved'),[alert,setAlert]=useState<Product|null>(null),[limit,setLimit]=useState(36);
 const{drops,loading,error,retry}=usePriceDrops('month');const reductions=bestDropsByProduct(drops,sort==='percent'?'percent':'dollars');
 const saved=watchIds.map(id=>products.find(p=>p.id===id)).filter((p):p is Product=>Boolean(p));const price=(p:Product)=>{const o=freshOffers(p.offers)[0];return o?o.price/o.packQuantity:Infinity;};
 const visible=saved.filter(p=>(!category||category===p.category)&&(!q||(p.name+' '+p.brand).toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==='dollars'?(reductions.get(b.id)?.dollars||0)-(reductions.get(a.id)?.dollars||0):sort==='percent'?(reductions.get(b.id)?.percent||0)-(reductions.get(a.id)?.percent||0):sort==='price'?price(a)-price(b):watchIds.indexOf(a.id)-watchIds.indexOf(b.id));
 return <main className="page-container watch-page"><div className="page-intro"><div><div className="eyebrow"><Eye size={14}/> YOUR POWER WISH LIST</div><h1>Keep an eye on your next build.</h1><p>Save parts you like, check their prices, and spot recorded reductions.</p></div><Link className="button outline small" href="/deals"><TrendingDown size={15}/>Explore price drops</Link></div>
  <div className="watch-storage-note"><Eye size={17}/><span>{user?'Your watch list syncs to your account.':'Your watch list is saved on this device.'} {user?'Set a target alert for website notifications.':'Sign in to sync across devices and set target-price alerts.'}</span>{!user&&<a className="text-link small-text" target="_top" href="/signin-with-chatgpt?return_to=%2Fwatchlist">Sign in <ArrowUpRight size={13}/></a>}</div>
  {(watchError||error)&&<div role="alert" className="notice-panel"><p>{watchError||error}</p><button className="button outline small" onClick={()=>{reloadWatch();retry();}}>Retry</button></div>}
  <div className="watch-controls"><label className="savings-search"><Search size={17}/><span className="sr-only">Search watch list</span><input placeholder="Search your saved parts…" value={q} onChange={e=>{setQ(e.target.value);setLimit(36);}}/></label><label className="field">Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All watched parts</option>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="field">Sort watch list<select value={sort} onChange={e=>setSort(e.target.value)}><option value="saved">Recently saved</option><option value="dollars">Biggest dollar drop</option><option value="percent">Biggest percentage drop</option><option value="price">Lowest unit price</option></select></label></div>
  <div className="savings-toolbar"><span>{watchReady?`${visible.length} watched ${visible.length===1?'product':'products'}`:'Loading your watch list…'}</span><button className="text-link small-text" onClick={()=>window.location.reload()}><RefreshCw size={13}/>Refresh prices</button></div>
  {!watchReady&&!watchError?<p className="inline-note" role="status">Loading saved products…</p>:visible.length?<div className="watch-list" aria-label="Watched products">{visible.slice(0,limit).map(p=>{const offer=freshOffers(p.offers)[0],drop=reductions.get(p.id);return <article className="watch-row" key={p.id}><Link className="watch-photo" href={'/products/'+p.id}><ProductImage product={p}/></Link><div className="watch-product"><Link href={'/products/'+p.id}>{p.name}</Link><small>{p.brand} · {categories.find(c=>c.id===p.category)?.label}</small><span className={drop?'watch-drop':'muted'}>{loading?'Checking reductions…':error?'Price history unavailable':drop?`${money(drop.dollars)} / unit lower (${drop.percent.toFixed(1)}%) at ${drop.retailer} · last 30 days`:'No confirmed drop in the last 30 days'}</span></div><div className="watch-price"><strong>{offer?money(offer.price/offer.packQuantity):'No fresh offer'}</strong><small>{offer?'In stock · per unit':'Check retailer availability'}</small>{offer&&<small>{offer.retailer}{offer.packQuantity>1?` · ${money(offer.price)} / ${offer.packQuantity} units`:''}</small>}</div><div className="watch-actions"><WatchButton product={p}/><button className="icon-button" aria-label={'Set price alert for '+p.name} onClick={()=>setAlert(p)} title="Set a target-price alert"><Bell size={17}/></button><button className="icon-button" aria-label={'Add '+p.name+' to build'} onClick={()=>add(p.id,offer?.id)}><Plus size={17}/></button></div></article>;})}</div>:watchReady&&<div className="empty-state"><Eye size={32}/><h3>{watchIds.length?'No watched parts match.':'Your next power pick starts here.'}</h3><p>{watchIds.length?'Try a different category or search.':'Tap the eye icon beside any product to add it to your watch list.'}</p><Link className="button dark" href="/">Browse parts</Link></div>}
  {visible.length>limit&&<button className="button outline load-more" onClick={()=>setLimit(n=>n+36)}>Show more watched products</button>}
  {watchIds.length>saved.length&&<p className="inline-note">{watchIds.length-saved.length} saved products are no longer in the catalog. <button className="text-link" onClick={async()=>{for(const id of watchIds.filter(id=>!products.some(p=>p.id===id)))await toggleWatch(id);}}>Remove unavailable products</button></p>}
  <p className="catalog-disclaimer">Watching saves a product to your list. Target-price alerts deliver notifications when their conditions are met. Watch prices and drop prices can come from different retailers; compare the package and purchase minimum before buying.</p>
  {alert&&<AlertModal product={alert} onClose={()=>setAlert(null)}/>}
 </main>;
}
