/* eslint-disable @next/next/no-img-element -- Static, precompressed WebP illustrations served by the Worker; no image transformation service. */
import {notFound} from 'next/navigation';
import Link from '../../../components/site-link';
import {guideArticles,readMinutes,sectionId} from '../../../lib/guide-content';
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props){const {slug}=await params;const a=guideArticles.find(a=>a.slug===slug);return{title:a?.title??'Article not found',description:a?.summary};}
export default async function GuideArticlePage({params}:Props){const {slug}=await params;const a=guideArticles.find(a=>a.slug===slug);if(!a)notFound();const related=guideArticles.filter(x=>x.slug!==a.slug&&x.kind===a.kind).sort((x,y)=>Number(y.topic===a.topic)-Number(x.topic===a.topic)).slice(0,3);
 return <main className="page-container guide-article"><nav className="guide-breadcrumb" aria-label="Breadcrumb"><Link href="/guide">Guide</Link><span>/</span><span>{a.topic}</span></nav><header className="guide-article-header"><div className="guide-row-tags"><span>{a.kind}</span><span>{a.level}</span><span>{readMinutes(a)} min read</span></div><h1>{a.title}</h1><p className="guide-lead">{a.summary}</p><p className="guide-date">Sources checked <time dateTime={a.reviewed}>{a.reviewed}</time>{a.eventDate&&<> · Event / announcement <time dateTime={a.eventDate}>{a.eventDate}</time></>}</p>{a.outcome&&<p className="guide-outcome"><strong>You’ll learn:</strong> {a.outcome}</p>}</header>
 <div className="guide-reading-layout"><aside className="guide-toc"><strong>In this article</strong><nav aria-label="Article contents">{a.sections.map((s,i)=><a key={s.title} href={'#'+sectionId(i)}>{s.title}</a>)}<a href="#sources">Sources & further reading</a></nav><Link className="button outline small" href="/guide/calculators">Calculator workshop →</Link></aside><article className="guide-prose">
 {a.image&&<figure><img src={a.image} alt={a.slug==='panel-technology'?'Concept illustration of a solar panel’s layers':'Concept illustration of a solar equipment wall'} width="1536" height="1024" loading="lazy"/><figcaption>Original Solar4U concept illustration. Not an installation drawing.</figcaption></figure>}
 {a.sections.map((s,i)=><section id={sectionId(i)} key={s.title}><h2>{s.title}</h2>{s.paragraphs?.map((p,j)=><p key={j}>{p}</p>)}{s.formula&&<div className="guide-formula"><span>WORKED METHOD</span><code>{s.formula}</code></div>}{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}{s.columns&&s.rows&&<div className="guide-table-wrap"><table><thead><tr>{s.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{s.rows.map((r,j)=><tr key={j}>{r.map((c,k)=><td key={k}>{c}</td>)}</tr>)}</tbody></table></div>}{s.sources&&<p className="guide-inline-source">Source: {s.sources.map((s,j)=><span key={s.url}>{j>0?' · ':''}<a href={s.url} target="_blank" rel="noopener noreferrer">{s.label} ↗</a></span>)}</p>}</section>)}
 {a.quiz&&<section className="guide-check"><h2>Check your understanding</h2><p>{a.quiz.question}</p><ol type="A">{a.quiz.options.map(o=><li key={o}>{o}</li>)}</ol><details><summary>Show answer and explanation</summary><p><strong>{a.quiz.options[a.quiz.answer]}</strong></p><p>{a.quiz.explanation}</p></details></section>}
 <section id="sources" className="guide-sources"><h2>Sources & further reading</h2><ul>{a.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.label} ↗</a></li>)}</ul><p className="guide-origin">{a.origin??'PVPartPicker editorial guide. Technical examples are illustrative; follow the selected equipment documentation and project-specific requirements.'}</p></section>
 <div className="guide-article-actions">{a.tool&&<Link className="button dark" href={a.tool.href}>{a.tool.label} →</Link>}<Link className="button outline" href="/build">Open system builder</Link></div><section><h2>Keep exploring</h2><div className="guide-related">{related.map(r=><Link href={'/guide/'+r.slug} key={r.slug}><span>{r.topic}</span><strong>{r.title}</strong></Link>)}</div></section></article></div></main>;
}
